### ISSUE TITLE
the expo app just doesn't work with trpc

### ISSUE THREAD

**Issue by 0xShy101** [t3-oss/create-t3-turbo#10]
I tried to run expo app but I got tired of it,

I tried it with 
- Yarn
- NPM
- PNPM

and in two different env
- WSL2
- Windows 11

after a while, this is the error I found and I think it's what stops it from bundling right
![image](https://user-images.githubusercontent.com/79533966/187965546-684ffc8b-bd61-45df-84ab-e7525d22b863.png)

in the terminal shows no errors.

any ideas?

**Comment by juliusmarminge** [comment]
You will have to provide some more context for this. It works out of the box for me after following the `Getting Started` guide in the README.

![CleanShot 2022-09-02 at 11 04 41](https://user-images.githubusercontent.com/51714798/188105202-a8ef9666-eab2-456e-8e8f-23f47e016dbc.png)

**Comment by 0xShy101** [comment]
I did as it says in the getting started guide,I tried again on a WSL2 ubuntu 20.04 machine and here is exactly what I did

- cloned the repo
- run npm install
- did the prisma steps

To be clear at this stage prisma and nextjs works just fine

- changed expo to `expo start --web`
- run `npm run dev` in project root
- I get a prompt from expo to `npx expo install @expo/webpack-config@^0.17.0` to use web support
- cd to apps/expo and run previous command
- run `npm run dev` again in root

No errors in the terminal, when visiting the expo localhost site in the console it shows the previous
error and shows blank page.

It might be different for you because of mac, I couldn't really test it on mac but I did for windows and wsl

**Comment by 0xShy101** [comment]
I don't actually want it in web, It's just in iphone and android gives me a blank page with no warning, but in the web at least I could see it in the console

**Comment by juliusmarminge** [comment]
Alright I could reproduce it now with Expo Web.

However, I am not going to put any effort into fixing this I'm afraid. It works as expected on mobile (at least I can't reproduce any other behavior) which is what most will use Expo for.

> I don't actually want it in web, It's just in iphone and android gives me a blank page with no warning, but in the web at least I could see it in the console

That's interesting that it doesn't work for mobile for you either. That I have been unable to reproduce.

**Comment by juliusmarminge** [comment]
Try changing the content to be displayed, maybe it is not loading the database correctly?

**Comment by juliusmarminge** [comment]
```diff
export const HomeScreen = () => {
  const postQuery = trpc.post.all.useQuery();

  return (
    <SafeAreaView>
      <View className="h-full w-full">
+       <Text className="text-3xl text-cyan-700">Hello World!</Text>
        <FlashList
```

![CleanShot 2022-09-02 at 11 46 19](https://user-images.githubusercontent.com/51714798/188112965-a1e062a8-545b-48f5-ab2f-c288d2fc7a18.png)

**Comment by 0xShy101** [comment]
I will clone a new repo on windows and I'll run a android emulator and tell you how it goes

**Comment by juliusmarminge** [comment]
Please note that you need your Next app to run on port 3000 for the default config to work, since the URL is hardcoded:

https://github.com/t3-oss/create-t3-turbo/blob/33ed43ef01c91c3ec520829cfdc8cc07461f34c2/apps/expo/src/_app.tsx#L12

**Comment by 0xShy101** [comment]
alright I wanted to make sure that I'm not missing something dumb so here is a video of me doing the process from 0 

https://www.youtube.com/watch?v=NcrtK90H5po

note: about the .env, windows handles it differently a little bit but I think that's not important I just want to show the process

**Comment by juliusmarminge** [comment]
> alright I wanted to make sure that I'm not missing something dumb so here is a video of me doing the process from 0 
> 
> 
> 
> https://www.youtube.com/watch?v=NcrtK90H5po
> 
> 
> 
> note: about the .env, windows handles it differently a little bit but I think that's not important I just want to show the process 

Yea that looks right. I can try on my Windows machine and get back to you.

**Comment by juliusmarminge** [comment]
![IMG_0080](https://user-images.githubusercontent.com/51714798/188132562-764c6cd5-14f2-4ab4-ad5a-6af9d083e2a2.jpeg)

Yea there is definitely some weird shenanigans going on with the Android Emulator.

On my iPhone it loads the text but the Android is just loading...

Interesting note is I couldn't get the posts loading on any of the versions when running create-t3-turbo from Windows, didn't test WSL.

**Comment by 0xShy101** [comment]
don't even bother with WSL since it's not very good with emulators, does trpc show for you on iphone? because I think that's where the issue is

**Comment by juliusmarminge** [comment]
> don't even bother with WSL since it's not very good with emulators, does trpc show for you on iphone? because I think that's where the issue is

Not when I run from Windows. It does when I run from Mac. Would be interested to see if it's a networking thing and windows doesn't allow the request to pass through to Expo or something... can't think of anything else that would cause it 🤔

**Comment by 0xShy101** [comment]
> > don't even bother with WSL since it's not very good with emulators, does trpc show for you on iphone? because I think that's where the issue is
> 
> Not when I run from Windows. It does when I run from Mac. Would be interested to see if it's a networking thing and windows doesn't allow the request to pass through to Expo or something... can't think of anything else that would cause it 🤔 

Makes sense since it also didn't work on WSL, I'll try it in my ubuntu linux machine and tell you what happened, it will be weird of it still didn't work there

**Comment by 0xShy101** [comment]
I tried on ubuntu 21.04 and no luck 😢

But nextjs still works.

![image](https://user-images.githubusercontent.com/79533966/188168658-96dba4cf-8c5d-45a2-8b7e-1e36b8396325.jpeg)

**Comment by 0xShy101** [comment]
So I assume for now this repo only really work for mac users, unless if you're not planning to use expo

**Comment by juliusmarminge** [comment]
> So I assume for now this repo only really work for mac users, unless if you're not planning to use expo

I might be able to look into this early next week when I have access to my "better" windows setup with my usual tools.

If you find something before then, feel free to file a PR

**Comment by 0xShy101** [comment]
For sure, I'm joining a hackathon with this stack, I'll finish building for the web then I'll try my hardest to maybe get it working on expo

**Comment by juliusmarminge** [comment]
> For sure, I'm joining a hackathon with this stack, I'll finish building for the web then I'll try my hardest to maybe get it working on expo

Decided to give it another go. Now the content is actually displaying. Just gotta find why the tRPC calls isnt resonding 
![image](https://user-images.githubusercontent.com/51714798/188186133-6e069d7b-c51c-4e21-a65d-aa17002112d9.png)

**Comment by juliusmarminge** [comment]
Cool, got a "fix".

What's happening is the Android Emulator isn't reaching the `localhost:3000` so you have to put in the hostname instead (or a local IP address e.g. `192.168.x.y`) for the trpc url:

```diff
- const url = "http://localhost:3000/api/trpc";
+ const url = "http://192.168.1.166:3000/api/trpc";
```

Then it should work:
![image](https://user-images.githubusercontent.com/51714798/188190681-45b06ddf-e53b-473e-ae8b-30add4c51e12.png)

**Comment by 0xShy101** [comment]
Consider checking this trpc console error when running `expo start --web` it seems to be something with Webpack setup in expo I have no clue but it's as far as I could reach with these errors, I believe fixing that should fix the phone version aswell

Also for me I can't even show the Hello World idk how you did it

![image](https://user-images.githubusercontent.com/79533966/188189431-d95e38cb-f8b4-4b09-b3a2-8a7a7aac070a.png)

**Comment by 0xShy101** [comment]
> Cool, got a "fix".
> 
> 
> 
> What's happening is the Android Emulator isn't reaching the `localhost:3000` so you have to put in the hostname instead (or a local IP address e.g. `192.168.x.y`) for the trpc url:
> 
> 
> 
> ```diff
> 
> - const url = "http://localhost:3000/api/trpc";
> 
> + const url = "http://192.168.x.y:3000/api/trpc";
> 
> ```
> 
> 
> 
> Then it should work:
> 
> ![image](https://user-images.githubusercontent.com/51714798/188190681-45b06ddf-e53b-473e-ae8b-30add4c51e12.png)
> 
> 

Oh cool let me test it

**Comment by juliusmarminge** [comment]
> Oh cool let me test it

I just pushed a version bump too in case that made any difference, test pulling a new clone of the repo.

**Comment by 0xShy101** [comment]
alright, I pulled the last changes and it actually worked!

![image](https://user-images.githubusercontent.com/79533966/188193076-df2c4112-cab7-4807-8e7a-7d04124cafec.png)

and for me, my android respects the safeareaprovider idk why it's that way for you

**Comment by 0xShy101** [comment]
I could update the readme to explain this fix for windows and Linux users if you want this to be the final solution for this error?

**Comment by juliusmarminge** [comment]
Glad it worked out!

> and for me, my android respects the safeareaprovider idk why it's that way for you

This was my first interaction with Android Emulator ever so could be some setting or I just picked a weird phone xd

> I could update the readme to explain this fix for windows and Linux users if you want this to be the final solution for this error?

idk, it should probably be solved a different way so it's more flexible to put your production url in there when you're deploying.

**Comment by 0xShy101** [comment]
maybe we could have it read from a env file and if it's in production it uses a production url and in local it uses a local url

**Comment by juliusmarminge** [comment]
Hello again, I think I made something more modular:

https://github.com/t3-oss/create-t3-turbo/blob/5b1fc969df1742a54086a28d0f6b6b856b240904/apps/expo/src/_app.tsx#L12-L20

Would you mind confirming if this works?

**Comment by 0xShy101** [comment]
yeah, I tried the quick start guide and everything worked great!

I also found a missing step that I had to do in the quick start guide so I updated the Readme file please take a look at it @juliusmarminge 

#14

**Comment by PiotrekPKP** [comment]
Hi @azezsan , were you able to use the dev server in web browser?
I'm facing the same issue with `--web` and it would be easier for me to develop in the browser (not to spin up emulator).
Thanks!

**Comment by azezsan** [comment]
> Hi @azezsan , were you able to use the dev server in web browser?
> 
> I'm facing the same issue with `--web` and it would be easier for me to develop in the browser (not to spin up emulator).
> 
> Thanks!

I haven't really tried after the issue was fixed, I'm using a emulator now, tho i would expect it to work?

**Comment by PiotrekPKP** [comment]
Sadly it doesn't... Maybe I'm doing something wrong tho haha
Nvm, I don't think I need web that much

**Comment by juliusmarminge** [comment]
> Sadly it doesn't... Maybe I'm doing something wrong tho haha
> Nvm, I don't think I need web that much

This project is built with the mindset that you should use NextJS for the web and Expo for iOS/Android.

**Comment by azezsan** [comment]
> Hi @azezsan , were you able to use the dev server in web browser? I'm facing the same issue with `--web` and it would be easier for me to develop in the browser (not to spin up emulator). Thanks!

I'm guessing you're developing on WSL right?

**Comment by PiotrekPKP** [comment]
> > Hi @azezsan , were you able to use the dev server in web browser? I'm facing the same issue with `--web` and it would be easier for me to develop in the browser (not to spin up emulator). Thanks!
> 
> I'm guessing you're developing on WSL right?

I'm using Arch Linux haha

**Comment by juliusmarminge** [comment]
> I did as it says in the getting started guide,I tried again on a WSL2 ubuntu 20.04 machine and here is exactly what I did
> 
> - cloned the repo
> - run npm install
> - did the prisma steps
> 
> To be clear at this stage prisma and nextjs works just fine
> 
> - changed expo to `expo start --web`
> - run `npm run dev` in project root
> - I get a prompt from expo to `npx expo install @expo/webpack-config@^0.17.0` to use web support
> - cd to apps/expo and run previous command
> - run `npm run dev` again in root
> 
> No errors in the terminal, when visiting the expo localhost site in the console it shows the previous
> error and shows blank page.
> 
> It might be different for you because of mac, I couldn't really test it on mac but I did for windows and wsl
> 

Idk but maybe you need this package?

**Comment by PiotrekPKP** [comment]
I've installed it. Web dev server is not necessary tho, thanks for help guys. I think you should focus on the RN -> Android/iOS, Next -> Web approach :)
