### ISSUE TITLE
bug: can't run expo run:ios

### ISSUE THREAD

**Issue by chen-rn** [t3-oss/create-t3-turbo#103]
Some packages(including [react-native-fast-image](https://expo.canny.io/feature-requests/p/react-native-fast-image)) cannot be run on Expo Go, requiring developers to build and run the app locally with `expo run:ios`.

However, running `expo run:ios` results in the following error.

```
@acme/expo:dev: ⚠️  Something went wrong running `pod install` in the `ios` directory.
@acme/expo:dev: Command `pod install` failed.
@acme/expo:dev: └─ Cause: Failed to load 'expo-dev-menu' podspec: 
@acme/expo:dev: [!] Invalid `expo-dev-menu.podspec` file: no implicit conversion of nil into String.
@acme/expo:dev: 
@acme/expo:dev:  #  from /Users/chenwang/Documents/projects/atomic-reading-2.3/node_modules/expo-dev-menu/expo-dev-menu.podspec:24
@acme/expo:dev:  #  -------------------------------------------
@acme/expo:dev:  #  
@acme/expo:dev:  >  folly_flags = '-DFOLLY_NO_CONFIG -DFOLLY_MOBILE=1 -DFOLLY_USE_LIBCPP=1 -DRNVERSION=' + rnVersion + ' -DRNPATCHVERSION=' + rnPatchVersion
@acme/expo:dev:  #  folly_compiler_flags = folly_flags + ' ' + '-Wno-comma -Wno-shorten-64-to-32'
@acme/expo:dev:  #  -------------------------------------------

```

There is a [discussion on the Expo side](https://github.com/expo/expo/issues/20497), but with no solution for pnpm, which create-t3-turbo enforces.

It seems that the problem has to do with hoisting; I tried changing `hoisting=false` and `hoist-pattern[]=!expo-dev-menu` in .npmrc, but I am still getting the same error.

Is anyone else getting this error?

**Comment by juliusmarminge** [comment]
can you provide a repro?

**Comment by chen-rn** [comment]
I started with a blank new repo and was able to get past this error. But is running into #99 now :(

**Comment by juliusmarminge** [comment]
Alright, closing this then, feel free to follow progress of #99
