### ISSUE TITLE
bug: next is including wrong eslint config

### ISSUE THREAD

**Issue by nickreese** [t3-oss/create-t3-turbo#104]
https://github.com/t3-oss/create-t3-turbo/blob/main/apps/nextjs/eslint.config.js

This may have been missed in the recent change to `eslint.config.js`

**Comment by juliusmarminge** [comment]
Fixed in https://github.com/t3-oss/create-t3-turbo/commit/0ee67c015e8cc79be26303e15260046a6647bd5f
