### ISSUE TITLE
Unable to perform db:push after schema change as tablesFilter doesnt seem to be referenced anywhere

### ISSUE THREAD

**Issue by ghandic** [t3-oss/create-t3-turbo#1044]
https://github.com/t3-oss/create-t3-turbo/blob/38c20cd6212482282e896ae0ae1904679fb11324/packages/db/drizzle.config.ts#L13

**Comment by moritzWa** [comment]
Might be related to my discussion/thread https://github.com/t3-oss/create-t3-turbo/discussions/1046?

**Comment by juliusmarminge** [comment]
sorry about htis

fixed in https://github.com/t3-oss/create-t3-turbo/commit/adbe672d86a629c89c00e221c269a137403c0dbe
