### ISSUE TITLE
bug: Console Logs not showing for Next.js backend

### ISSUE THREAD

**Issue by moritzWa** [t3-oss/create-t3-turbo#1050]
### Provide environment information

```
System:
    OS: macOS 14.4.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 689.95 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.12.0 - ~/.nvm/versions/node/v20.12.0/bin/node
    npm: 10.5.0 - ~/.nvm/versions/node/v20.12.0/bin/npm
    pnpm: 9.1.0 - ~/.nvm/versions/node/v20.12.0/bin/pnpm
```

### Describe the bug

I'm not seeing any of the console logs I put in my routes. 

I know this repo implements [loggerLink](https://trpc.io/docs/client/links/loggerLink), but is insufficient.

Maybe this is due to the "terminal tubro ascii layout"?

![image](https://github.com/t3-oss/create-t3-turbo/assets/42035131/f8a07011-ee64-463d-8bd5-423a12568ded)

I noticed that the default [`outputMode`](https://turbo.build/repo/docs/reference/configuration#outputmode) for turbo is `full` which "Displays all output (default)"

So, both of these did nothing:
1. adding `--output-logs=full` to the dev script
2. adding `"outputMode": "full"` to the dev pipeline in the `turbo.json`

Example of stuff I'm trying to log:

<img width="545" alt="image" src="https://github.com/t3-oss/create-t3-turbo/assets/42035131/9d79e8e5-94c5-4ae0-a884-a9a4b0b58b54">

### Link to reproduction

n/a (haven't made any significant changes to the template)

### To reproduce

1. add logs to route like post.ts
2. run pnpm run dev
3. see if they appear in the console

**Comment by moritzWa** [comment]
Also, pls lmk if I should post this in the main t3 repo or the turbo repo instead.

**Comment by RedBeardEth** [comment]
As indicated in the first picture - you need to use the arrow keys to navigate up from @acme/api to @acme/nextjs @moritzWa

**Comment by moritzWa** [comment]
ohh, thank you! Should I add a sentence about this to the README? Or change this text to "Use arrow keys to navigate **between packages**".

**Comment by juliusmarminge** [comment]
Doesnt the UI say?

**Comment by moritzWa** [comment]
@juliusmarminge is there a way to make the logged content full height? Is this part of turbo?

![2024-05-27 13 32 55](https://github.com/t3-oss/create-t3-turbo/assets/42035131/6f72a093-d2be-4d0c-9141-b658846ae184)

**Comment by moritzWa** [comment]
ok nvm found this https://github.com/vercel/turbo/discussions/7802

**Comment by juliusmarminge** [comment]
should be better in turbo 2.0

**Comment by juliusmarminge** [comment]
closing as this is not related to here, but like i said the TUI mode is better / less buggy in 2.0 where it's no longer experimental
