### ISSUE TITLE
bug: npm install fails, eslint 9 not supported by eslint-plugin-import

### ISSUE THREAD

**Issue by RiccardoRomagnoli** [t3-oss/create-t3-turbo#1058]
### Provide environment information

  System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 2.28 GB / 15.89 GB
  Binaries:
    Node: 18.17.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 9.6.7 - C:\Program Files\nodejs\npm.CMD
    pnpm: 9.1.3 - ~\AppData\Local\pnpm\pnpm.EXE

### Describe the bug

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: @pitchpal/eslint-config@0.3.0
npm ERR! Found: eslint@9.3.0
npm ERR! node_modules/eslint
npm ERR!   dev eslint@"^9.2.0" from @pitchpal/eslint-config@0.3.0
npm ERR!   tooling/eslint
npm ERR!     @pitchpal/eslint-config@0.3.0
npm ERR!     node_modules/@pitchpal/eslint-config
npm ERR!       workspace tooling\eslint from the root project
npm ERR!       9 more (@pitchpal/api, @pitchpal/auth, @pitchpal/db, ...)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer eslint@"^2 || ^3 || ^4 || ^5 || ^6 || ^7.2.0 || ^8" from eslint-plugin-import@2.29.1
npm ERR! node_modules/eslint-plugin-import
npm ERR!   eslint-plugin-import@"^2.29.1" from @pitchpal/eslint-config@0.3.0
npm ERR!   tooling/eslint
npm ERR!     @pitchpal/eslint-config@0.3.0
npm ERR!     node_modules/@pitchpal/eslint-config
npm ERR!       workspace tooling\eslint from the root project
npm ERR!       9 more (@pitchpal/api, @pitchpal/auth, @pitchpal/db, ...)
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

### Link to reproduction

reproduce.com

### To reproduce

run npx create-turbo@latest -e https://github.com/t3-oss/create-t3-turbo

**Comment by juliusmarminge** [comment]
Ignoring peerDep range (`npm i --legacy-peer-deps`), have you noticed the plugin failing?

**Comment by RiccardoRomagnoli** [comment]
no, didn't try, but I think the repo should have the dependencies versions sorted out. Did you try to re-lock the pnpm lock file? Cos I also got to change the react version for compatibility between two deps (can't recall now).

**Comment by juliusmarminge** [comment]
> no, didn't try, but I think the repo should have the dependencies versions sorted out. Did you try to re-lock the pnpm lock file? Cos I also got to change the react version for compatibility between two deps (can't recall now).

That's unfortunately quite hard and would stale development, especially now with React 19 coming out there'll be a bunch of peer dep warnings for libs that doesn't update their peer dep range even when it could work without issues
