### ISSUE TITLE
bug: eslint Invalid option '--ext'

### ISSUE THREAD

**Issue by ShooTeX** [t3-oss/create-t3-turbo#107]
### Provide environment information

```  
System:
    OS: macOS 13.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 1.47 GB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 19.2.0 - /nix/store/r68wi7i4g71ndi1qxw3vi6iwsllz7aip-nodejs-19.2.0/bin/node
    Yarn: 1.22.19 - /etc/profiles/per-user/stx/bin/yarn
    npm: 8.19.3 - /nix/store/r68wi7i4g71ndi1qxw3vi6iwsllz7aip-nodejs-19.2.0/bin/npm
```

### Describe the bug

`pnpm lint` throws error on fresh clone:

```
 Packages in scope: @acme/api, @acme/auth, @acme/db, @acme/expo, @acme/nextjs, @acme/tailwind-config
• Running lint in 6 packages
• Remote caching disabled
@acme/nextjs:lint: cache miss, executing 05bd9912c069341f
@acme/expo:lint: cache miss, executing 18c34214a23dba8f
@acme/auth:lint: cache miss, executing 9bfcc2dd7eaffc06
@acme/api:lint: cache miss, executing 8c940869ee734766
@acme/auth:lint: 
@acme/auth:lint: > @acme/auth@0.1.0 lint /Users/stx/dev/create-t3-turbo/packages/auth
@acme/auth:lint: > eslint . --ext .ts,.tsx
@acme/auth:lint: 
@acme/api:lint: 
@acme/api:lint: > @acme/api@0.1.0 lint /Users/stx/dev/create-t3-turbo/packages/api
@acme/api:lint: > eslint . --ext .ts,.tsx
@acme/api:lint: 
@acme/nextjs:lint: 
@acme/nextjs:lint: > @acme/nextjs@0.1.0 lint /Users/stx/dev/create-t3-turbo/apps/nextjs
@acme/nextjs:lint: > SKIP_ENV_VALIDATION=1 next lint
@acme/nextjs:lint: 
@acme/expo:lint: 
@acme/expo:lint: > @acme/expo@0.1.0 lint /Users/stx/dev/create-t3-turbo/apps/expo
@acme/expo:lint: > eslint . --ext ts,tsx
@acme/expo:lint: 
@acme/auth:lint: Invalid option '--ext' - perhaps you meant '-c'?
@acme/api:lint: Invalid option '--ext' - perhaps you meant '-c'?
@acme/expo:lint: Invalid option '--ext' - perhaps you meant '-c'?
@acme/auth:lint:  ELIFECYCLE  Command failed with exit code 2.
@acme/api:lint:  ELIFECYCLE  Command failed with exit code 2.
@acme/expo:lint:  ELIFECYCLE  Command failed with exit code 2.
@acme/auth:lint: ERROR: command finished with error: command (/Users/stx/dev/create-t3-turbo/packages/auth) pnpm run lint exited (1)
command (/Users/stx/dev/create-t3-turbo/packages/auth) pnpm run lint exited (1)
```

### Link to reproduction

https://github.com/ShooTeX/test
https://github.com/ShooTeX/test/actions/runs/3837068737/jobs/6531954758

### To reproduce

`git clone https://github.com/t3-oss/create-t3-turbo.git`
`cd create-t3-turbo`
`pnpm i`
`pnpm lint`

the action also fails with the same error when using this as a template:
https://github.com/ShooTeX/test/actions/runs/3837068737/jobs/6531954758

### Additional information

probably has something to do with the new `eslint.config.js`

I found this related issue:
https://github.com/eslint/eslint/issues/16531

workaround is using `ESLINT_USE_FLAT_CONFIG=false`

I'm not sure if this is an eslint bug, my error or if something is wrong with the new config, since I never used it before :D

edit: I also just realized that `.eslintrc.cjs` got renamed into `eslint.config.js`. If I understand correctly, `eslint.config.js` is the new experimental config with a new structure, so shouldn't they be incompatible?

https://eslint.org/docs/latest/user-guide/configuring/configuration-files-new

**Comment by juliusmarminge** [comment]
Yea. I might have missed a thing or two when migrated... Surprised my CI passes though. Will fix tonight
