### ISSUE TITLE
bug: Doesn't work with any other packagemanager apart from pnpm

### ISSUE THREAD

**Issue by rverma-dev** [t3-oss/create-t3-turbo#1108]
### Provide environment information

NA

### Describe the bug

Trying to use with bun / yarn / npm every generation only generate pnpm code.

### Link to reproduction

npx create-turbo@latest -e https://github.com/t3-oss/create-t3-turbo

### To reproduce

npx create-turbo@latest -e https://github.com/t3-oss/create-t3-turbo

**Comment by noxify** [comment]
Thats not a bug - that's expected.

From the readme:
> or use Turbo's CLI to init your project (use PNPM as package manager):

**Comment by juliusmarminge** [comment]
Yup this repo is made to use pnpm. You can change it if you want but that will require some extra manual work
