### ISSUE TITLE
bug: Can not install dependencies using pnpm

### ISSUE THREAD

**Issue by BlackBeardo** [t3-oss/create-t3-turbo#1109]
### Provide environment information

```
System:
    OS: Windows 11 10.0.22631
    CPU: (4) x64 11th Gen Intel(R) Core(TM) i3-1115G4 @ 3.00GHz
    Memory: 2.38 GB / 7.80 GB
  Binaries:
    Node: 20.12.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.21 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 10.5.0 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.11.0 - ~\AppData\Roaming\npm\pnpm.CMD
    bun: 1.0.21 - ~\.bun\bin\bun.EXE
```

### Describe the bug

while trying command:
`npx create-turbo@latest -e https://github.com/t3-oss/create-t3-turbo` it's failing dependencies installation 

### Link to reproduction

i am sure this is and issue it self

### To reproduce

there is nothing to reproduce. i am having issue while installing dependencies.

### Additional information

pwsh> npx create-turbo@latest -e https://github.com/t3-oss/create-t3-turbo
? Where would you like to create your Turborepo? ./
? Which package manager do you want to use? pnpm

>>> Creating a new Turborepo with:

Application packages
 - apps\auth-proxy
 - apps\expo
 - apps\nextjs
Library packages
 - packages\api
 - packages\auth
 - packages\db
 - packages\ui
 - packages\validators
tooling
 - tooling\eslint
 - tooling\github
 - tooling\prettier
 - tooling\tailwind
 - tooling\typescript

>>  Installing dependencies...
>>> Unexpected error. Please report it as a bug:
Error: Command failed with exit code 1: pnpm install --fix-lockfile
Scope: all 14 workspace projects
 WARN  Ignoring broken lockfile at C:\Users\patel\OneDrive\Desktop\t3-next\trickerr-turbo: Lockfile C:\Users\patel\OneDrive\Desktop\t3-next\trickerr-turbo\pnpm-lock.yaml not compatible with current pnpm
C:\Users\patel\OneDrive\Desktop\t3-next\trickerr-turbo\apps\auth-proxy:
 ERR_PNPM_SPEC_NOT_SUPPORTED_BY_ANY_RESOLVER  eslint@catalog: isn't supported by any available resolver.

This error happened while installing a direct dependency of C:\Users\patel\OneDrive\Desktop\t3-next\trickerr-turbo\apps\auth-proxy
Progress: resolved 1, reused 0, downloaded 0, added 0
    at QB (C:\Users\patel\AppData\Local\npm-cache\_npx\e8c68b66aeb1424f\node_modules\create-turbo\dist\cli.js:12:57)
    at C:\Users\patel\AppData\Local\npm-cache\_npx\e8c68b66aeb1424f\node_modules\create-turbo\dist\cli.js:12:8077
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Fl (C:\Users\patel\AppData\Local\npm-cache\_npx\e8c68b66aeb1424f\node_modules\create-turbo\dist\cli.js:58:2092)
    at async Command.m0 (C:\Users\patel\AppData\Local\npm-cache\_npx\e8c68b66aeb1424f\node_modules\create-turbo\dist\cli.js:83:7484)
    at async Command.parseAsync (C:\Users\patel\AppData\Local\npm-cache\_npx\e8c68b66aeb1424f\node_modules\commander\lib\command.js:936:5) {
  shortMessage: 'Command failed with exit code 1: pnpm install --fix-lockfile',
  command: 'pnpm install --fix-lockfile',
  escapedCommand: 'pnpm install --fix-lockfile',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: 'Scope: all 14 workspace projects\n' +
    ' WARN  Ignoring broken lockfile at C:\\Users\\patel\\OneDrive\\Desktop\\t3-next\\trickerr-turbo: Lockfile C:\\Users\\patel\\OneDrive\\Desktop\\t3-next\\trickerr-turbo\\pnpm-lock.yaml not compatible with current pnpm\n' +
    'C:\\Users\\patel\\OneDrive\\Desktop\\t3-next\\trickerr-turbo\\apps\\auth-proxy:\r\n' +
    " ERR_PNPM_SPEC_NOT_SUPPORTED_BY_ANY_RESOLVER  eslint@catalog: isn't supported by any available resolver.\n" +
    '\n' +
    'This error happened while installing a direct dependency of C:\\Users\\patel\\OneDrive\\Desktop\\t3-next\\trickerr-turbo\\apps\\auth-proxy\n' +
    'Progress: resolved 1, reused 0, downloaded 0, added 0',
  stderr: '',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}

**Comment by juliusmarminge** [comment]
We're using catalogs so you need `pnpm@^9.5`
