### ISSUE TITLE
bug: VSCode Debugging

### ISSUE THREAD

**Issue by mtapiafdez** [t3-oss/create-t3-turbo#112]
### Provide environment information

Create a brand new project from template.

### Describe the bug

Breakpoints are not binding. They bind and work as expected on regular create-t3 (non-monorepo).

### Link to reproduction

 Just set breakpoints in any TRPC router.

### To reproduce

They will not bind in the API routers or anything else.

### Additional information

Awesome work! I'm loving the T3 stack and this Monorepo component. Just having some issues running VSCode debugger and setting breakpoints.

**Comment by juliusmarminge** [comment]
Hmm I don't usually use the debugger myself 🥲 so I wouldn't really know what the issue could be. Maybe it doesn't work when the package is transpiled 🤔 

Does it work for other stuff in other monorepos?

**Comment by PiotrekPKP** [comment]
I've also never used the VS Code debugger, but it seems working for me. What exactly are you running?
My test:
- add a new run configuration from `Run -> Add Configuration` menu, this is my config:
```json
{
      "type": "node",
      "request": "launch",
      "name": "Launch Program",
      "runtimeExecutable": "pnpm",
      "args": ["run", "dev"]
}
```
- add breakpoint in tRPC router (in this example I used the `postRouter` and Prisma call in `create` procedure)
- run the code with debugger using `Run / Start Debugging` menu

**Comment by gnllucena** [comment]
@juliusmarminge I have a local branch that enables debugging in vscode

How can I open a PR for this feature?

![image](https://user-images.githubusercontent.com/2061623/215656301-0c98089d-5c8b-4cf2-b290-ce844927bfb7.png)

**Comment by gnllucena** [comment]
@juliusmarminge, I have a local branch that enables debugging in vscode, I'd love to create a PR for this feature, but I need to figure out how to do it. 

Can you help me with that?

![image](https://user-images.githubusercontent.com/2061623/215656573-c9ecbecc-25c4-48c0-9da7-f4ee5a04005c.png)

**Comment by gnllucena** [comment]
Forked repo with the changes:

https://github.com/gnllucena/create-t3-turbo-debugging

**Comment by juliusmarminge** [comment]
> Forked repo with the changes:
> 
> clone the repo, change `.env.example` to `.env`, run `pnpm db:generate`, place your break points, hit `F5`
> 
> https://github.com/gnllucena/create-t3-turbo-debugging

Hey, thanks for the interest in contributing. In general, the steps will be the same as for Create T3 App, [see contributing guidelines here](https://github.com/t3-oss/create-t3-app/blob/next/CONTRIBUTING.md).

TL:DR; Fork this repo, create a new branch, implement your changes, commit and push. Come back to this repo - you should see a yellow banner where it says `Create Pull Request` and it will auto-detect the recent changes and select the branch for you automatically.
