### ISSUE TITLE
bug: cant even clone the project

### ISSUE THREAD

**Issue by duard** [t3-oss/create-t3-turbo#1126]
### Provide environment information

➜ npx envinfo --system --binaries
Need to install the following packages:
envinfo@7.13.0
Ok to proceed? (y) 

  System:
    OS: Linux 6.5 Ubuntu 22.04.4 LTS 22.04.4 LTS (Jammy Jellyfish)
    CPU: (24) x64 AMD Ryzen 9 5900X 12-Core Processor
    Memory: 35.09 GB / 46.94 GB
    Container: Yes
    Shell: 5.8.1 - /usr/bin/zsh
  Binaries:
    Node: 21.7.2 - ~/.nvm/versions/node/v21.7.2/bin/node
    Yarn: 1.22.22 - ~/.nvm/versions/node/v21.7.2/bin/yarn
    npm: 10.5.0 - ~/.nvm/versions/node/v21.7.2/bin/npm
    pnpm: 8.15.1 - ~/.local/share/pnpm/pnpm
    bun: 1.1.13 - ~/.bun/bin/bun

### Describe the bug

cant start an new app from the description in the readme 

### Link to reproduction

https://github.com/t3-oss/create-t3-turbo

### To reproduce

npx create-turbo@latest -e https://github.com/t3-oss/create-t3-turbo

### Additional information

➜ npx create-turbo@latest -e https://github.com/t3-oss/create-t3-turbo

Need to install the following packages:
create-turbo@2.0.9
Ok to proceed? (y) 
? Where would you like to create your Turborepo? ./my-turborepo
? Which package manager do you want to use? pnpm

>>> Creating a new Turborepo with:

Application packages
 - apps/auth-proxy
 - apps/expo
 - apps/nextjs
Library packages
 - packages/api
 - packages/auth
 - packages/db
 - packages/ui
 - packages/validators
tooling
 - tooling/eslint
 - tooling/github
 - tooling/prettier
 - tooling/tailwind
 - tooling/typescript

>   Installing dependencies...
>>> Unexpected error. Please report it as a bug:
Error: Command failed with exit code 1: pnpm install --fix-lockfile
Scope: all 14 workspace projects
 WARN  Ignoring broken lockfile at /home/cazakino/gigantao/my-turborepo: Lockfile /home/cazakino/gigantao/my-turborepo/pnpm-lock.yaml not compatible with current pnpm
/home/cazakino/gigantao/my-turborepo/apps/auth-proxy:
 ERR_PNPM_SPEC_NOT_SUPPORTED_BY_ANY_RESOLVER  eslint@catalog: isn't supported by any available resolver.

This error happened while installing a direct dependency of /home/cazakino/gigantao/my-turborepo/apps/auth-proxy
Progress: resolved 1, reused 0, downloaded 0, added 0
    at CM (/home/cazakino/.npm/_npx/e8c68b66aeb1424f/node_modules/create-turbo/dist/cli.js:23:57)
    at /home/cazakino/.npm/_npx/e8c68b66aeb1424f/node_modules/create-turbo/dist/cli.js:23:8077
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ph (/home/cazakino/.npm/_npx/e8c68b66aeb1424f/node_modules/create-turbo/dist/cli.js:69:2060)
    at async Command.Eg (/home/cazakino/.npm/_npx/e8c68b66aeb1424f/node_modules/create-turbo/dist/cli.js:94:7448)
    at async Command.parseAsync (/home/cazakino/.npm/_npx/e8c68b66aeb1424f/node_modules/commander/lib/command.js:936:5) {
  shortMessage: 'Command failed with exit code 1: pnpm install --fix-lockfile',
  command: 'pnpm install --fix-lockfile',
  escapedCommand: 'pnpm install --fix-lockfile',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: 'Scope: all 14 workspace projects\n' +
    ' WARN  Ignoring broken lockfile at /home/cazakino/gigantao/my-turborepo: Lockfile /home/cazakino/gigantao/my-turborepo/pnpm-lock.yaml not compatible with current pnpm\n' +
    '/home/cazakino/gigantao/my-turborepo/apps/auth-proxy:\n' +
    " ERR_PNPM_SPEC_NOT_SUPPORTED_BY_ANY_RESOLVER  eslint@catalog: isn't supported by any available resolver.\n" +
    '\n' +
    'This error happened while installing a direct dependency of /home/cazakino/gigantao/my-turborepo/apps/auth-proxy\n' +
    'Progress: resolved 1, reused 0, downloaded 0, added 0',
  stderr: '',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}

**Comment by noxify** [comment]
Try to update pnpm to the latest version.

It seems you are using version 8.

With the latest changes, the repo requires 9.6.0 (?) or newer

**Comment by juliusmarminge** [comment]
Catalogs were introduced in pnpm 9.5

I recommend using corepack which will pick up the version from package json and use that

**Comment by SimonHudec** [comment]
It wouldnt be bad to somehow highlight this information, so less issues of this type are created. I myself ran into this issue
