### ISSUE TITLE
Demo Video

### ISSUE THREAD

**Issue by jloria13** [t3-oss/create-t3-turbo#115]
### Describe the feature you'd like to request

Demo video for running the project 

### Describe the solution you'd like to see

Would be nice if you guys could add to the README a demo video on how to run it and why certain choices were made, and how could something be rewritten like the auth library, if 8 wanted to use a different option 

### Additional information

Example: https://youtu.be/aTEv0-ZBbWk

**Comment by juliusmarminge** [comment]
I'll try to record something later this week

**Comment by jloria13** [comment]
Thank you! Really great work with the stack!

**Comment by juliusmarminge** [comment]
Here you go: https://www.youtube.com/watch?v=XorGkcv1CZo
