### ISSUE TITLE
bug: Module not found: Can't resolve when I add --turbo

### ISSUE THREAD

**Issue by nihilum-labs** [t3-oss/create-t3-turbo#1175]
### Provide environment information

  System:
    OS: Linux 5.15 Ubuntu 22.04.4 LTS 22.04.4 LTS (Jammy Jellyfish)
    CPU: (8) x64 Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
    Memory: 2.96 GB / 11.69 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 20.17.0 - ~/n/bin/node
    npm: 10.8.2 - ~/n/bin/npm
    pnpm: 9.9.0 - ~/.local/share/pnpm/pnpm
    bun: 1.1.26 - ~/.bun/bin/bun

### Describe the bug

Default installation, except that I added in `"dev": "pnpm with-env next dev --turbo"` and a button component to the page.
And I get the error 
```
Module not found: Can't resolve '@acme/ui/button'
1 | import { auth, signIn, signOut } from "@acme/auth";
> 2 | import { Button } from "@acme/ui/button";
| ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
if i remove --turbo everything ok

### Link to reproduction

https://github.com/t3-oss/create-t3-turbo

### To reproduce

Just add --turbo to dev

**Comment by juliusmarminge** [comment]
Report upstream to next please
