### ISSUE TITLE
version conflict:  update shadcn cli usage

### ISSUE THREAD

**Issue by dmetelin** [t3-oss/create-t3-turbo#1178]
### Provide environment information

  System:
    OS: macOS 14.5
    CPU: (8) arm64 Apple M1
    Memory: 457.36 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 21.6.2 - /usr/local/bin/node
    Yarn: 1.22.22 - /usr/local/bin/yarn
    npm: 10.8.1 - /usr/local/bin/npm
    pnpm: 9.9.0 - /opt/homebrew/bin/pnpm
    Watchman: 2024.07.15.00 - /opt/homebrew/bin/watchman

### Describe the bug

Update `pnpm ui-add` to use the new shadcn cli:
https://ui.shadcn.com/docs/cli

```
pnpm dlx shadcn-ui add && prettier src --write --list-different

│
│  ENOENT  Command failed with ENOENT: shadcn-ui add
│ spawn shadcn-ui ENOENT
```

Change to:
```
pnpm dlx shadcn add && prettier src --write --list-different
```

### Link to reproduction

https://ui.shadcn.com/docs/cli

### To reproduce

Update shadcn to the latest version.
Run `pnpm ui-add`

**Comment by Bashamega** [comment]
I would like to work on this

**Comment by Bashamega** [comment]
Should i create a pr?

**Comment by soulful-ramble** [comment]
> Should i create a pr?

Yes, you can fork this repo and pull request. 😊

**Comment by soulful-ramble** [comment]
#1186
