### ISSUE TITLE
`pnpm lint` gives an error after installing `react-navigation`

### ISSUE THREAD

**Issue by ReimagineDigital** [t3-oss/create-t3-turbo#118]
### Provide environment information

Irrelevant for this issue

### Describe the bug

`pnpm lint` shows an error after the installation of `react-navigation`

### Link to reproduction

No link

### To reproduce

1. Clone the template, and add this dependency into the expo project `package.json`:

>     "@react-navigation/native": "^6.1.2",

2. Run `pnpm i`

3. Run `pnpm lint`

You will receive this error:
`Failed to load parser './parser.js' declared in 'package.json » eslint-config-next/core-web-vitals ... Cannot find module 'next/dist/compiled/babel/eslint-parser'`

**Comment by juliusmarminge** [comment]
Strangeeeeeee

Guessing it has to do with hoisting since it seems to look for the parser in the wrong place 🤔. No idea what to do other than disabling the plugin?

**Comment by CarlosBM18** [comment]
Neither do I. I looked at it and the command seems to work removing these lines from the nextjs `package.json`.

` diff
 - "eslintConfig": {
  -  "extends": [
 -     "next",
 -     "next/core-web-vitals"
 -   ]
  }`
  
So, maybe we should remove these or find another workaround.

**Comment by juliusmarminge** [comment]
> Neither do I. I looked at it and the command seems to work removing these lines from the nextjs `package.json`.
> 
> `"eslintConfig": { "extends": [ "next", "next/core-web-vitals" ] }`
> 
> But by removing these lines other lint errors appear. So, we should remove these lines or find another workaround.

That's removing the plugin. Not ideal but...

**Comment by CarlosBM18** [comment]
> > Neither do I. I looked at it and the command seems to work removing these lines from the nextjs `package.json`.
> > `"eslintConfig": { "extends": [ "next", "next/core-web-vitals" ] }`
> > But by removing these lines other lint errors appear. So, we should remove these lines or find another workaround.
> 
> That's removing the plugin. Not ideal but...

Yeah... 🙁

**Comment by CarlosBM18** [comment]
This is still happening @juliusmarminge

**Comment by CarlosBM18** [comment]
This solves the problem: https://github.com/vercel/next.js/issues/38939#issuecomment-1243508653

**Comment by juliusmarminge** [comment]
> This is still happening @juliusmarminge 

Huh? I tried and it didnt error

**Comment by CarlosBM18** [comment]
> > This is still happening @juliusmarminge
> 
> Huh? I tried and it didnt error

Do you have installed the `react-navigation` package?

**Comment by juliusmarminge** [comment]
> > > This is still happening @juliusmarminge
> 
> > 
> 
> > Huh? I tried and it didnt error
> 
> 
> 
> Do you have installed the `react-navigation` package?

I'll try again tomorrow but i know i tested with this exact package before i closed the issue
