### ISSUE TITLE
How to use websockets for live data?

### ISSUE THREAD

**Issue by facinick** [t3-oss/create-t3-turbo#119]
I want to enable live queries over websockets.. how can I make it happen in this repo?

**Comment by juliusmarminge** [comment]
Shouldn't be any difference than any other project. You need a persistent server or use a service such as Soketi or Pusher.

Do you have any reproduction of where this isn't working?

**Comment by juliusmarminge** [comment]
Feel free to reopen with a repro if you face any issues
