### ISSUE TITLE
bug: eslint config fails to load on Cursor IDE whereas it works fine on VSCode

### ISSUE THREAD

**Issue by garshythoel** [t3-oss/create-t3-turbo#1199]
### Provide environment information

  System:
    OS: macOS 15.0
    CPU: (10) arm64 Apple M1 Pro
    Memory: 1.64 GB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.16.0 - ~/.nvm/versions/node/v20.16.0/bin/node
    npm: 10.8.1 - ~/.nvm/versions/node/v20.16.0/bin/npm
    pnpm: 9.11.0 - /opt/homebrew/bin/pnpm

### Describe the bug

Eslint errors/warnings are not functioning inside Cursor IDE even though it works fine in VSCode, i've attempted
1) Restarting ESLint servers
2) Restarting IDEs
3) Fresh Installs

Cursor Details:
Version: 0.41.2
VSCode Version: 1.91.1

VSCode Details:
Version: 1.93.1 (Universal)

ESLint console output on Cursor:
```
[Info  - 7:40:50 PM] ESLint server is running.
[Info  - 7:40:51 PM] ESLint library loaded from: /Users/harshytgoel/Projects/inkrepo/node_modules/eslint/lib/api.js
[Error - 7:40:51 PM] Request textDocument/diagnostic failed.
  Message: Request textDocument/diagnostic failed with message: The "path" argument must be of type string. Received undefined
  Code: -32603 
[Error - 7:40:51 PM] Document pull failed for text document file:///Users/harshytgoel/Projects/inkrepo/apps/nextjs/src/app/layout.tsx
  Message: Request textDocument/diagnostic failed with message: The "path" argument must be of type string. Received undefined
  Code: -32603 
[Error - 7:40:52 PM] Request textDocument/codeAction failed.
  Message: Request textDocument/codeAction failed with message: The "path" argument must be of type string. Received undefined
  Code: -32603 
```

No such errors in VSCode.  Unsure if i'm the only one running into this issue - i have added a loom recording reproduction link.

### Link to reproduction

https://www.loom.com/share/f0653f3eeea647058a08d302413ff732

### To reproduce

1. `npx create-turbo@latest -e https://github.com/t3-oss/create-t3-turbo`
2. add unused variable to `/apps/nextjs/src/app/layout.tsx`
3. restart ESLint server

### Additional information

https://www.loom.com/share/f0653f3eeea647058a08d302413ff732

**Comment by juliusmarminge** [comment]
If it works in vscode then it feels like a cursor issue, no?

**Comment by garshythoel** [comment]
ahhh - good point, lemme open there

**Comment by cipriancaba** [comment]
@garshythoel did you end up opening the issue in Cursor?

**Comment by dnishiyama** [comment]
For those running into this (eslint not working on cursor), this was my fix:

<img width="723" alt="Image" src="https://github.com/user-attachments/assets/f6aaeaa7-e6a8-425d-a4b0-fd5aceaa5f39" />

@cipriancaba
