### ISSUE TITLE
[Improvement] Any plans to include next-auth ?

### ISSUE THREAD

**Issue by johann-taberlet** [t3-oss/create-t3-turbo#12]
Hey there, I first would like to thank you for this amazing job. It's what I was looking for months on the Zart stack and it finally happened with you <3

I'm wondering if you are aware of this [draft PR on next-auth](https://github.com/nextauthjs/next-auth/pull/5240), [(original post here)](https://github.com/nextauthjs/next-auth/discussions/3942#discussioncomment-3450873) that will probably allow us to use next-auth on expo apps and if yes, if your plan is to integrate it when it will be available to fully support the original T3 stack ?

**Comment by juliusmarminge** [comment]
Yes it will be included once there is an official way to do it 👍

**Comment by ZackCgl** [comment]
What do you guys use for auth now?

**Comment by greendesertsnow** [comment]
You basically get stuck with Next-auth once you decide to go through that route.

**Comment by alexnault** [comment]
next-auth is coming to create-t3-turbo https://github.com/t3-oss/create-t3-turbo/pull/36

**Comment by juliusmarminge** [comment]
I've now merged NextAuth for Next.js. Will make it work for Expo once that's possible.
