### ISSUE TITLE
bug: EAS Building an apk from a clean repo fails

### ISSUE THREAD

**Issue by BRDSLY** [t3-oss/create-t3-turbo#120]
### Provide environment information

```
System:
  OS: Windows 10 10.0.19045
  CPU: (24) x64 AMD Ryzen 9 3900X 12-Core Processor
  Memory: 21.68 GB / 31.95 GB
Binaries:
  Node: 16.15.1 - C:\Program Files\nodejs\node.EXE
  npm: 8.14.0 - ~\AppData\Roaming\npm\npm.CMD
```

### Describe the bug

Building an apk using preview profile fails on gradlew on eas.

Originally fixed this unreliably by prebuilding locally and adding `reactNativeVersion = "0.70.5"` to apps/expo/android/build.gradle

expo doctor gives no errors

Continued development with the issue returning and now can't fix it, even with a clean create-t3-turbo repo.

Building clean repo (without prebuilding locally) gives this error on Run gradlew:
```bash
[stderr] FAILURE: Build completed with 2 failures.
[stderr] 1: Task failed with an exception.
[stderr] -----------
[stderr] * Where:
[stderr] Build file '/home/expo/workingdir/build/node_modules/expo/android/build.gradle' line: 9
[stderr] * What went wrong:
[stderr] A problem occurred evaluating project ':expo'.
[stderr] > Cannot invoke method multiply() on null object
[stderr] * Try:
[stderr] > Run with --stacktrace option to get the stack trace.
[stderr] > Run with --info or --debug option to get more log output.
[stderr] > Run with --scan to get full insights.
[stderr] ==============================================================================
[stderr] 2: Task failed with an exception.
[stderr] -----------
[stderr] * Where:
[stderr] Build file '/home/expo/workingdir/build/node_modules/expo/android/build.gradle' line: 78
[stderr] * What went wrong:
[stderr] A problem occurred configuring project ':expo'.
[stderr] > Could not get unknown property 'release' for SoftwareComponentInternal set of type org.gradle.api.internal.component.DefaultSoftwareComponentContainer.
[stderr] * Try:
[stderr] > Run with --stacktrace option to get the stack trace.
[stderr] > Run with --info or --debug option to get more log output.
[stderr] > Run with --scan to get full insights.
[stderr] ==============================================================================
[stderr] * Get more help at https://help.gradle.org
[stderr] BUILD FAILED in 1m 49s
```

The prebuild stage skips metro:
```
› Metro skipped: Project metro.config.js does not match prebuild template.
```
and also has these warnings about peer dependencies:
```
WARN  Issues with peer dependencies found
apps/expo
└─┬ expo-splash-screen
  └─┬ @expo/prebuild-config
    └── ✕ missing peer expo-modules-autolinking@>=0.8.1
Peer dependencies that should be installed:
  expo-modules-autolinking@>=0.8.1
packages/auth
└─┬ @next-auth/prisma-adapter
  └── ✕ missing peer @prisma/client@">=2.26.0 || >=3"
Peer dependencies that should be installed:
  @prisma/client@">=2.26.0 || >=3"
Packages: +1291
```

Thanks for any help, will be happy to provide any more info, I didn't create a reproduction repo purely because I don't actually change anything (Except for in app.json but this will need to be for your own expo account/project).

I am on windows so I cannot use EAS locally, so I'm having to wait 30 minuites in a queue just for my build to fail, so trying to debug this is difficult.

I'd appreciate if somebody could try to reproduce, so I can determine whether it is my environment causing the issues? Maybe my pnpm installation?

### Link to reproduction

https://github.com/t3-oss/create-t3-turbo

### To reproduce

git clone https://github.com/t3-oss/create-t3-turbo
cd create-t3-turbo
pnpm i

// update lines in apps/expo/app.json
4 - "slug": "actual-slug-of-project",
22 - "bundleIdentifier": "ext.yourdomain.projectname"
35 - "projectId": "your-expo-project-id-xxxxxxxxxxxx"

pnpm add -g eas-cli
eas login // Login with account that owns project

cd apps/expo
eas build:configure # Select All

eas build --platform android --profile preview

**Comment by PiotrekPKP** [comment]
I figured out the solution. The thing is, I don't really know how to implement it to this repository.

For whatever reason Expo does not know how to figure out your React Native version. To fix this, you have to edit `build.gradle` file of your project. To get it to your project's directory, run this command:
`npx expo prebuild --platform=android`

Then, open `/android/build.gradle` file and add following things to it:
```gradle
buildscript {
    ext.getPackageJsonVersion = { packageName ->
         new File(['node', '--print', "JSON.parse(require('fs').readFileSync(require.resolve('${packageName}/package.json'), 'utf-8')).version"].execute(null, rootDir).text.trim())
    }
    ext {
        //current code...
        reactNativeVersion = "${ext.getPackageJsonVersion('react-native')}"
        expoPackageVersion = "${ext.getPackageJsonVersion('expo')}"
    }
}
```

**Comment by PiotrekPKP** [comment]
OK, I think I found a solution. I've wrote a plugin that appends those lines into the `build.gradle` file. Will open a pr isoon

**Comment by BRDSLY** [comment]
> Expo does not know how to figure out your React Native version. To fix this, you have to edit `build.gradle` file of your project. To get it to your project's directory, run this command: `npx expo prebuild --platform=android`
> 
> Then, open `/android/build.gradle` file and add following things to it:
> 
> ```groovy-gradle
> buildscript {
>     ext.getPackageJsonVersion = { packageName ->
>          new File(['node', '--print', "JSON.parse(require('fs').readFileSync(require.resolve('${packageName}/package.json'), 'utf-8')).version"].execute(null, rootDir).text.trim())
>     }
>     ext {
>         //current code...
>         reactNativeVersion = "${ext.getPackageJsonVersion('react-native')}"
>         expoPackageVersion = "${ext.getPackageJsonVersion('expo')}"
>     }
> }
> ```

FIXED! Thanks!
So strange how I never specified expoPackageVersion but had multiple successful builds. Something tells me I'm never quite going to understand expo...

**Comment by rodolphoasb** [comment]
@PiotrekPKP, thanks for this! So the only solution atm is to eject?

**Comment by PiotrekPKP** [comment]
> @PiotrekPKP, thanks for this! So the only solution atm is to eject?

I wrote a plugin that appends this code automatically, check up there ^^

**Comment by hichemfantar** [comment]
the plugin seems to have been removed in the expo 50 commit.
https://github.com/t3-oss/create-t3-turbo/commit/7eeef16bc0e8fa0081d427feb93e686d3c98e57c#diff-dc09ba7ebfede1336d437b73c184aaa551a608e54eb3ccb4f4633486a2b41b30
Is the plugin obsolete now? if so what fixed the problem?
