### ISSUE TITLE
feat: include a patch for crypto.getRandomValues() is not available error

### ISSUE THREAD

**Issue by HonestCodeWasTaken** [t3-oss/create-t3-turbo#125]
### Describe the feature you'd like to request

The template isn't as easy to setup due to expo not working well with crypto library, i had to include 
import "react-native-get-random-values";

inside /node_modules/expo/build/environment/getInstallationIdAsync.js

otherwise installing it with pnpm i and then running dev doesnt work on mobile

### Describe the solution you'd like to see

patch-package usage to patch this in expo node_modules

**Comment by juliusmarminge** [comment]
We cant include patches for every possible package by default

**Comment by HonestCodeWasTaken** [comment]
@juliusmarminge I dont have expo-crypto installed
