### ISSUE TITLE
feat: How to handle login and registration in a React Native app using create-t3-app

### ISSUE THREAD

**Issue by martwozniak** [t3-oss/create-t3-turbo#129]
### Describe the feature you'd like to request

Can you provide a simple way to handle login and registration from within the React Native app? I know that next-auth which is used in create-t3-app is unsupported by React Native. 

### Describe the solution you'd like to see

A simple way to log in and register using TRPC, React Native. So that there is full compatibility with the application written in create-t3-app.

### Additional information

Can it be done? Or do I need to use a library other than next-auth in the web application?

**Comment by juliusmarminge** [comment]
https://github.com/t3-oss/create-t3-turbo#what-auth-solution-should-i-use-instead-of-next-authjs-for-expo
