### ISSUE TITLE
Inconsistency issue in quick start

### ISSUE THREAD

**Issue by tmlamb** [t3-oss/create-t3-turbo#13]
The [quickstart](https://github.com/t3-oss/create-t3-turbo#quick-start) guide explains how to configure the local db .env file with a sqlite filesystem url, however the provider configuration in the prisma schema is set to postgresql.

https://github.com/t3-oss/create-t3-turbo/blob/e3f1c4915eea150d8a3a3ec92194696c10adabbe/packages/db/prisma/schema.prisma#L9

I think this leads to an error when running the quickstart instructions as-is:
```bash
$ npm run db-push
...
Error: Schema validation error - Error (query-engine-node-api library)
Error code: P1012
error: Error validating datasource `db`: the URL must start with the protocol `postgresql://` or `postgres://`.
  -->  schema.prisma:10
   | 
 9 |     provider = "postgresql"
10 |     url      = env("DATABASE_URL")
   | 
```
Do you think it would be better to set `provider = "sqlite"` in the template's schema file by default?

**Comment by juliusmarminge** [comment]
Ah yea it was sqlite previously but had to change it since I wanted a deployed version. Should add that step to the guide as well, or just deploy from a different branch

**Comment by tmlamb** [comment]
Sounds good, updating the guide to specify a postgresql setup would also work!

One other related thing you might want to cleanup is the db.sqlite file that's been checked into source:
https://github.com/t3-oss/create-t3-turbo/blob/e3f1c4915eea150d8a3a3ec92194696c10adabbe/packages/db/prisma/db.sqlite

**Comment by juliusmarminge** [comment]
> Sounds good, updating the guide to specify a postgresql setup would also work!
> 
> One other related thing you might want to cleanup is the db.sqlite file that's been checked into source (assuming that was unintended?) https://github.com/t3-oss/create-t3-turbo/blob/e3f1c4915eea150d8a3a3ec92194696c10adabbe/packages/db/prisma/db.sqlite

It was unimtended but i actually kinda like that you have a few posts when you first launch the application so it’s not a completely empty screen.

Welcome for suggestions on how to improve the starting point content wise though, as long as it is kept at a minimum
