### ISSUE TITLE
feat: Add db:generate to getting started steps next to db:push

### ISSUE THREAD

**Issue by kainanaina** [t3-oss/create-t3-turbo#134]
### Describe the feature you'd like to request

Hi. I really like this template DX, but if I haven't checked prisma website, I wouldn't know that it provides typescript generation from schema. Only after checking their docs, I found `db:generate` cli command, which turned out to be in root package.json also, but the tutorial isn't mentioning it, which results in running app with `any` types for all API data.

### Describe the solution you'd like to see

Add `db:generate` to tutorial steps (most likely next to `pnpm db:push`) or add it to `pnpm dev`? I don't know what is the best approach here. Is there a way to listen to prisma schema changes and run generation in dev mode?

**Comment by juliusmarminge** [comment]
db:push also generates

**Comment by kainanaina** [comment]
Ok, that's weird, somehow it didn't happened for me initially. I'll close it assuming that's some weird Windows Powershell bug, thanks.
