### ISSUE TITLE
feat: More details about "browser-like" mobile NextAuth usage

### ISSUE THREAD

**Issue by 5hee75** [t3-oss/create-t3-turbo#138]
### Describe the feature you'd like to request

Please describe in more detail what the solution looks like regarding this comment from the README talking about authentication options for mobile apps.

```if you're dropping the Expo app for something more "browser-like", you can still use Next-Auth.js for those.```

I build mobile apps primarily with Ionic React + Capacitor, so I think this would fall directly under the "browser-like" category.  The whole app runs mostly within a webview on the device.  Everything is built using standard web technologies and components.

The one thing I can't seem to get an answer on with regards to using Next-Auth is how to use it outside the context of the sever-side session provider.  The app would be running completely outside the context of the NextJS server, so how would I leverage the server-side auth from my app?

### Describe the solution you'd like to see

Please provide examples or more explanation about how to leverage NextAuth in the "browser-like" mobile app context.

### Additional information

I'm currently using the Supabase SDK directly on the client for auth and database, but I'm also looking into how to bridge this gap between the client and server - they have some auth helpers to hopefully make this easier.

Either way - I want to sort out auth between client and server so I can use tRPC with my various client apps.  I'm just trying to figure out the best way to do that.

https://supabase.com/docs/guides/auth/auth-helpers/nextjs

https://www.reddit.com/r/Supabase/comments/10qlg3h/client_sdk_vs_trpc_api_pros_and_cons/

**Comment by juliusmarminge** [comment]
If your app is "browser-like" and can handle cookies etc you should be able to just request `<next-app-url>/api/auth/signin?callbackUrl=<other-app-url>`

And handle the session data when it comes back
