### ISSUE TITLE
Deploying to Railway

### ISSUE THREAD

**Issue by DavidIlie** [t3-oss/create-t3-turbo#140]
Hi,

I am having trouble understanding what I'd need to do in order to deploy the nextjs application to Railway.

Thank you

**Comment by juliusmarminge** [comment]
These options seems to do the work for me, you can probably optimize it to don't install a bunch of expo stuff / redeploy when only apps/expo changes too

![CleanShot 2023-02-02 at 11 28 07](https://user-images.githubusercontent.com/51714798/216300072-1808274b-b30c-4cc0-a0bc-4624ba20df49.png)
