### ISSUE TITLE
bug: [TRPCClientError: Network request failed] when mutating post after simply initializing project

### ISSUE THREAD

**Issue by magnusrodseth** [t3-oss/create-t3-turbo#142]
### Provide environment information

```
 System:
    OS: macOS 13.1
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
    Memory: 1.08 GB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 8.5.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
```

### Describe the bug

I have simply initialized the project from the template.

When adding a title and description to a post, and clicking the button for **Publish post**, I get the following (undescriptive) error in the console:

```sh
WARN  [TRPCClientError: Network request failed]
```

### Link to reproduction

https://github.com/magnusrodseth/didactic-octo-meme

### To reproduce

1. Follow the steps described in the `README.md`.
2. Add a title and description to the post.
3. Click **Publish post**.
4. Observe that you get the error listed above in the console.

**Comment by magnusrodseth** [comment]
Closed, as I solved this when running `pnpm dev` from the root project directory. I thought I could simply start the Expo app. @juliusmarminge, perhaps the information should be a bit more clear in the `README.md` ☺️

Anyway, great repo!

**Comment by argcast** [comment]
> Closed, as I solved this when running `pnpm dev` from the root project directory. I thought I could simply start the Expo app. @juliusmarminge, perhaps the information should be a bit more clear in the `README.md` ☺️
> 
> Anyway, great repo!

Could you please detail the steps you did to fix it? I'm facing the same exact issue but starting the `pnpm dev` that triggers an `expo start --ios`from the root directory is not fixing it. What am I missing?

**Comment by magnusrodseth** [comment]
@argcast Are you sure the Next backend **and** the Expo app are running? I simply ran `pnpm dev` from the project directory - nothing more.
