### ISSUE TITLE
Error when trying to use PNPM as package manager

### ISSUE THREAD

**Issue by lucasthevenet** [t3-oss/create-t3-turbo#15]
Hey there, i'm having some trouble using pnpm instead of npm with this template. Maybe someone has some insight on what I'm missing. 

[Here is the repo with the changes I've made so far](https://github.com/lucasthevenet/create-t3-turbo-pnpm)

### Steps I made to change to pnpm
- added `pnpm-workspace.yaml` with corresponding workspaces (apps and packages)
- ran `pnpm install`

Everything seems to install correctly, however, when running, I get a few errors:

(Keep in mind I didn't change anything other than adding  pnpm, and initially everything was running fine before pnpm)

## 1st error
<img width="1024" alt="Screenshot 2022-09-10 175610" src="https://user-images.githubusercontent.com/24488324/189503122-700a81b5-95a1-442d-b41a-201fa6c80d30.png">

However this error dissapeared after I updated **trpc** to `10.0.0-proxy-alpha.73`

## 2nd error

> @acme/nextjs:dev: error - Error: ENOENT: no such file or directory, open 'C:\Users\anon\create-t3-turbo-pnpm\apps\nextjs\.next\server\pages\api\trpc\schema.prisma'
@acme/nextjs:dev:     at Object.openSync (node:fs:585:3)
@acme/nextjs:dev:     at Object.readFileSync (node:fs:453:35)
@acme/nextjs:dev:     at new LibraryEngine (C:\Users\anon\create-t3-turbo-pnpm\node_modules\@prisma\client\runtime\index.js:25992:41)
@acme/nextjs:dev:     at PrismaClient.getEngine (C:\Users\anon\create-t3-turbo-pnpm\node_modules\@prisma\client\runtime\index.js:30454:16)
@acme/nextjs:dev:     at new PrismaClient (C:\Users\anon\create-t3-turbo-pnpm\node_modules\@prisma\client\runtime\index.js:30426:29)
@acme/nextjs:dev:     at eval (webpack-internal:///(api)/../../packages/db/index.ts:8:16)
@acme/nextjs:dev:     at Module.(api)/../../packages/db/index.ts (C:\Users\anon\create-t3-turbo-pnpm\apps\nextjs\.next\server\pages\api\trpc\[trpc].js:175:1) 
@acme/nextjs:dev:     at __webpack_require__ (C:\Users\anon\create-t3-turbo-pnpm\apps\nextjs\.next\server\webpack-api-runtime.js:33:43)
@acme/nextjs:dev:     at eval (webpack-internal:///(api)/../../packages/api/src/context.ts:6:66)
@acme/nextjs:dev:     at Module.(api)/../../packages/api/src/context.ts (C:\Users\anon\create-t3-turbo-pnpm\apps\nextjs\.next\server\pages\api\trpc\[trpc].js:131:1) {
@acme/nextjs:dev:   errno: -4058,
@acme/nextjs:dev:   syscall: 'open',
@acme/nextjs:dev:   code: 'ENOENT',
@acme/nextjs:dev:   path: 'C:\\Users\\anon\\create-t3-turbo-pnpm\\apps\\nextjs\\.next\\server\\pages\\api\\trpc\\schema.prisma',
@acme/nextjs:dev:   clientVersion: '4.3.1'
@acme/nextjs:dev: }
@acme/nextjs:dev: TRPCClientError: invalid json response body at http://localhost:3000/api/trpc/post.all?batch=1&input=%7B%220%22%3A%7B%22json%22%3Anull%2C%22meta%22%3A%7B%22values%22%3A%5B%22undefined%22%5D%7D%7D%7D reason: Unexpected token < in JSON at position 0
@acme/nextjs:dev:     at Function.from (file:///C:/Users/anon/create-t3-turbo-pnpm/node_modules/.pnpm/@trpc+client@10.0.0-proxy-alpha.73_7jrqolvqjpfojvwms5forbwovm/node_modules/@trpc/client/dist/transformResult-106791d7.mjs:13:16)
@acme/nextjs:dev:     at file:///C:/Users/anon/create-t3-turbo-pnpm/node_modules/.pnpm/@trpc+client@10.0.0-proxy-alpha.73_7jrqolvqjpfojvwms5forbwovm/node_modules/@trpc/client/dist/links/httpBatchLink.mjs:199:64
@acme/nextjs:dev:     at runMicrotasks (<anonymous>)
@acme/nextjs:dev:     at processTicksAndRejections (node:internal/process/task_queues:96:5) {
@acme/nextjs:dev:   meta: undefined,
@acme/nextjs:dev:   shape: undefined,
@acme/nextjs:dev:   data: undefined,
@acme/nextjs:dev:   [cause]: FetchError: invalid json response body at http://localhost:3000/api/trpc/post.all?batch=1&input=%7B%220%22%3A%7B%22json%22%3Anull%2C%22meta%22%3A%7B%22values%22%3A%5B%22undefined%22%5D%7D%7D%7D reason: Unexpected token < in JSON at position 0
@acme/nextjs:dev:       at C:\Users\anon\create-t3-turbo-pnpm\node_modules\.pnpm\next@12.2.5_zpnidt7m3osuk7shl3s4oenomq\node_modules\next\dist\compiled\node-fetch\index.js:1:51227
@acme/nextjs:dev:       at runMicrotasks (<anonymous>)
@acme/nextjs:dev:       at processTicksAndRejections (node:internal/process/task_queues:96:5) {
@acme/nextjs:dev:     type: 'invalid-json'
@acme/nextjs:dev:   }
@acme/nextjs:dev: }

At first sight it seems that the import path of prisma's schema is wrong but I can't figure out why this is happening only after installing pnpm. If anyone has some pointer to what could be happening I'd be most grateful.

**Comment by juliusmarminge** [comment]
I'd assume it has to do with PNPM hoisting. I think when I used turborepo + pnpm + prisma previously, I've had to shamefully hoist prisma. Can't remember exactly how

**Comment by lucasthevenet** [comment]
Thanks for the quick response! It seems that placing an `.npmrc` with `shamefully-hoist`="true" solved the issue. Also installing Prisma as a dev dependency on the root equally solved the issue.
