### ISSUE TITLE
bug: EAS Build Error

### ISSUE THREAD

**Issue by Wolfleader101** [t3-oss/create-t3-turbo#153]
### Provide environment information

Creating new worker instance
Using VM template "macos-monterey-12.6-xcode-14.0" running macOS Monterey 12.6
Installed software:
- Xcode 14.0 (14A309)
- Node.js 16.18.1
- Yarn 1.22.17
- pnpm 7.11.0
- npm 8.1.2
- fastlane 2.210.0
- CocoaPods 1.11.3
- Ruby 2.7
- Expo CLI 6.0.0

### Describe the bug

FastLane EAS Build is failing

![image](https://user-images.githubusercontent.com/25214835/216824172-7f7532c6-1b0b-4a6e-b79d-e7dad182bbdb.png)

### Link to reproduction

-

### To reproduce

eas build -p ios --profile development

**Comment by Wolfleader101** [comment]
https://github.com/expo/eas-cli/issues/1674#issuecomment-1418502886

Related to this issue here. Will need a patch to fix

**Comment by juliusmarminge** [comment]
We already have that patch https://github.com/t3-oss/create-t3-turbo/blob/main/patches/react-native@0.70.5.patch
