### ISSUE TITLE
For collaboration

### ISSUE THREAD

**Issue by sunny0714** [t3-oss/create-t3-turbo#154]
Hello, team
This is Sunny Williams who is a full-stack web developer from Canada
I'm not sure if this is the right way, but I'm creating this issue to connect with team

I have seen a job description in Freelancer.com and wanted to work on this project because I'm very familiar with Next.js, React, Typescript, TailwindCSS and Node.js, Express, Hapi, SQL/NoSQL and so on.
https://www.freelancer.com/projects/javascript/Next-Developer-React-Tailwind-TRPC/details

Look forward to hearing from the team soon

Best

**Comment by juliusmarminge** [comment]
Thanks for your interest in the project.

Unfortunately, there's not a whole lot to do here. I just keep it up to date with create-t3-app and maintain all the Expo quirks.

**Comment by sunny0714** [comment]
Okay, thanks for updating me
