### ISSUE TITLE
feat: Automatic post install Prisma database push

### ISSUE THREAD

**Issue by pieter-berkel** [t3-oss/create-t3-turbo#155]
### Describe the feature you'd like to request

In the normal "T3-Stack" there is a postinstall command in package.json that pushes the prism database. Is this also possible with "T3-Turbo"?

### Describe the solution you'd like to see

I would like to see an update where by default there is a postinstall command for pushing the database as in the standard T3-Stack.

**Comment by juliusmarminge** [comment]
i don't think you want to push the schema on postinstall - perhaps generate the types?

**Comment by pieter-berkel** [comment]
At the moment I changed the build -> dependsOn value from db:generate to db:push.

```
// turbo.json

{
  "pipeline": {
    // ...
    "db:push": {
      "inputs": ["prisma/schema.prisma"],
      "cache": false
    },
    "build": {
      "dependsOn": ["^build", "^db:push"],
      "outputs": [".next/**", ".expo/**"]
    },
  },
  // ...
}
```

**Comment by juliusmarminge** [comment]
> Now the database will be updated when a new build is occurred.

That sounds kinda scary NGL...
