### ISSUE TITLE
Android Studio/Prisma Studio Clash

### ISSUE THREAD

**Issue by justindc100** [t3-oss/create-t3-turbo#16]
Android Studio by default runs on the port 5555, which is also the default port for Prisma Studio.  As Android studio will likely be used quite frequently with a package like this, it might be worth defining a different port for Prisma Studio to launch in by default.  

This can easily be changed by adding --port 5000 or whatever port you want it to run on in the dev script on packages/db/package.json

If you think this is worthwhile I can make a quick pr.

**Comment by juliusmarminge** [comment]
Sounds good

**Comment by justindc100** [comment]
PR merged
