### ISSUE TITLE
Does this pattern leak backend into expo app?

### ISSUE THREAD

**Issue by jetaggart** [t3-oss/create-t3-turbo#164]
### Provide environment information

n/a

### Describe the bug

Since we're including the full api as a dependency of the RN app, would this not embed all of our api source code into the expo app and ship it to end users? AFAIK, react native does no tree-shaking, so the simple dependency and import inside of RN would cause the source of our api to be pulled in. This would be bad.

I'm not 100% this happens as I cannot find the source code in the final expo bundle, but I can't don't understand why that wouldn't happen. It makes me nervous. Any insight as to why it's safe or not?

### Link to reproduction

https://github.com/t3-oss/create-t3-turbo

### To reproduce

Not sure

**Comment by amritk** [comment]
I think you only import the types from the api package so you should be ok

**Comment by jetaggart** [comment]
I don't know if that's true. It's in the dependency list and metro does not do tree shaking. Is there something super special about import type that prevents all the underlying source from being included even with two things true?

**Comment by amritk** [comment]
I'm not sure about metro. But I realized that if you export any of the database stuff in API index AND the types then expo doesn't run, even if you only import the types. 

So if you only export + import the types from API index, it shouldn't even import anything else from API into the expo build. Not sure if that explains it but it's easier if u just try it.

**Comment by Tobjoern** [comment]
I'd love to get a clarification

> 

Yes, there is something special about 'import type'. According to the [Ts docs](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-8.html) it gets fully erased.
However, this won't matter, when importing enums and zod schemas, as they can't be used with 'import type'.
Generally I'd love to get further clarification on this very sensitive topic.

**Comment by juliusmarminge** [comment]
I'm not 100% sure about this - not an expert with how RN is bundled etc. If you want to be 100% sure I think you should be good to make the api package a dev dependency and install superjson separately

```diff
  "dependencies": {
-   "@acme/api": "*",
+   "superjson": "1.9.2" 
  },
  "devDependencies": {
+   "@acme/api": "*",
  }
```

```diff
// utils/api.ts
+ import superjson from "superjson";
- import { transformer } from "@acme/api/transformer";

...
```

**Comment by Tobjoern** [comment]
Good point, but when adding the api via dev-dependencies, make sure not to include any enums / schemas,
as these are needed at compile time and must be installed via normal dependencies.

**Comment by jetaggart** [comment]
@juliusmarminge that's a good thought but I don't see how that would not cause runtime issues considering you are depending on that code at runtime, especially in the case of shared validations/zod/etc.

**Comment by Tobjoern** [comment]
> @juliusmarminge that's a good thought but I don't see how that would not cause runtime issues considering you are depending on that code at runtime, especially in the case of shared validations/zod/etc. Even if that did work, it's a really sharp knife. I feel like you make one mistake on how you compile/bundle and you've sucked everything in again.

If you are able to add the lib as a dev dependency, it would resolve the whole issue, but this will only work if actual types are imported, if one uses enums or zod it wouldn't, as these are used at runtime.
One solution would be creating '@acme/api-types', which is solely responsible for providing additional interfaces and zod schemas.

`devDep:
- '@acme/api' 

dep:
- '@acme/api-types'`

@acme/api would have to depend on @acme/api-types then (as a normal non-dev dependency), but I don't think this should be a problem, as we only use the exported api-contracts, without any runtime variables.

**Comment by juliusmarminge** [comment]
You beat me to it, was gonna propose something like that.

I'll try to dig more if this is actually needed or if its safe to just have it as a regular dep too.

**Comment by Tobjoern** [comment]
Just one question: Is it even possible for @acme/api to be solely included as a dev-dependency?
Eventually, the client has to be aware of the actual route names, i.e. 'admin/user/create' etc.
Isn't this only possible, when some of the API's types are available in the runtime, or am I missing something?

**Comment by juliusmarminge** [comment]
> Eventually, the client has to be aware of the actual route names, i.e. 'admin/user/create' etc.
> 
> Isn't this only possible, when some of the API's types are available in the runtime, or am I missing something?

No, no types are included in the runtime bundle, thats how TypeScript works - it's imaginary only present in dev. I've written a post on how the trpc client works here https://trpc.io/blog/tinyrpc-client

**Comment by Tobjoern** [comment]
Thanks, I get it now. I forgot that the actual function calls + names still persist and are able to be parsed.

**Comment by juliusmarminge** [comment]
Thanks for reporting this @jetaggart. I've now moved the api package to be a devDep in the expo app and in hindsight thats how it should be - we're only interested in the types from our trpc router, the runtime code is taken care of by the @trpc/* packages.

If you wanna share validatiors for shared forms between backend and frontend, create a separate package for that - might have to include that in the repo by default so people can understand the mental model were going for

**Comment by jetaggart** [comment]
Ah, that seems like a great solution. Thanks for taking the time to address this, this was my last hurdle to get through before adopting trpc.
