### ISSUE TITLE
During build stage prisma schema is not found and table is not created

### ISSUE THREAD

**Issue by YuPototo** [t3-oss/create-t3-turbo#166]
I clone the template and follow the deployment instruction.

According to Vercel the deployment is successful and I can visit the deployed page: https://play-t3-repo-nextjs.vercel.app/

But trpc is returning 500 error, which says:

```
TRPCClientError: 
Invalid `prisma.post.findMany()` invocation:


The table `public.Post` does not exist in the current database.
    at u.from (https://play-t3-repo-nextjs-76yk4xpwq-yupototo.vercel.app/_next/static/chunks/pages/_app-f241d1fe7123ac18.js:1:21032)
    at https://play-t3-repo-nextjs-76yk4xpwq-yupototo.vercel.app/_next/static/chunks/pages/_app-f241d1fe7123ac18.js:5:80273
```

Clearly, my Postgres DB has no table called `post`. And I can confirm this by checking my railway.app db.

In vercel's building logs I notice one warning line:

```
../../node_modules/@prisma/client postinstall: prisma:warn The postinstall script automatically ran `prisma generate` and did not find your `prisma/schema.prisma`.
```

According to this line `schema.prisma` is not found and `generate` script fails to run.

Anything I can do with this?

Thanks :)

**Comment by juliusmarminge** [comment]
Did you run 'pnpm db:push` after changing the database url?

**Comment by YuPototo** [comment]
> Did you run `pnpm db:push` after changing the database url?

No. I haven't. 

I find that create-t3-app has the same result.

Clearly I don't have enough understanding of how Prisma works :)
