### ISSUE TITLE
How to use env variables in @acme/api

### ISSUE THREAD

**Issue by Tobjoern** [t3-oss/create-t3-turbo#173]
### Provide environment information

-

### Describe the bug

-

### Link to reproduction

-

### To reproduce

-

### Additional information

How would be go about importing/using env variables in '@acme/api'?
AFAIK the variables are merely declared in 'apps/nextjs'.
Are we supposed to add those to the context via 'createInnerTRPCContext' or is there a better / more established way?
Is #135 supposed to solve this very issue?

**Comment by juliusmarminge** [comment]
> Is https://github.com/t3-oss/create-t3-turbo/pull/135 supposed to solve this very issue?

Yea it solves this issue but it introduces some negative side effects for caching (which is why it's still just a draft)

**Comment by juliusmarminge** [comment]
Closing this as its sort of duplicste of #87
