### ISSUE TITLE
bug: expo start --ios|android --tunnel not working

### ISSUE THREAD

**Issue by Aymericr** [t3-oss/create-t3-turbo#179]
### Provide environment information

  **System:**
    OS: macOS 13.2.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 197.02 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  **Binaries:**
    Node: 18.14.0 - ~/.nvm/versions/node/v18.14.0/bin/node
    npm: 9.5.0 - ~/.nvm/versions/node/v18.14.0/bin/npm

### Describe the bug

I cloned and setup the repo properly, could make exverthing work fine until I  `npx expo login` and added `--tunel` to view the app via Expo Go on my iOS.

How can we make tunneling work to play with the app on our phones?

I think the problem comes from the hardcoded `localhost` in the expo directory.

Cheers
A.

### Link to reproduction

https://docs.expo.dev/workflow/expo-cli/#tunneling

### To reproduce

To reproduce add `--tunnel` to `apps/expo/package.json`:
```json
{
  "script": {
    "dev": "expo start --ios --tunnel"
  }
}
```

**Comment by juliusmarminge** [comment]
Not sure about tunnel, I usually launch the apps separetely to launch it on my phone:

<img width="1512" alt="CleanShot 2023-02-23 at 22 01 00@2x" src="https://user-images.githubusercontent.com/51714798/221029349-fc5719dd-c4ff-4450-afcc-8a509413323b.png">

Scanning the QR code opens the app on Expo Go successfully.

**Comment by SayemW** [comment]
I am trying to use github codespaces to develop. I am able to launch the app on my device but when I click on create post nothing happens.

**Comment by juliusmarminge** [comment]
This should be fixed in Expo 49. If you're still experiencing this issue feel free to reopen.

REf: https://docs.expo.dev/more/expo-cli/#tunneling

**Comment by acharlop** [comment]
The process of running expo tunnel is not well documented anywhere, but the process is pretty simple. The tunnel for Metro is provided directly by expo, however the tunnel for the API needs to be provided by you and it might benefit from an update in `getBaseUrl()`.

The steps that worked for me:
1. from root `pnpm dev`
2. in a new terminal run `ngrok http 3000`
3. in `apps/exp/src/utils/api.tsx#getBaseUrl` replace the final line `return 'http://${localhost}:3000'` with the url from step 1
4. in another terminal run from `apps/expo` run `pnpm dev --tunnel`

The url from step 4 can be used to share the app with phones not on your local network!

**Comment by hayata-suenaga** [comment]
@acharlop's solution works for me!
