### ISSUE TITLE
feat: move dotenv-cli to turborepo root project, per turborepo's docs

### ISSUE THREAD

**Issue by mbifulco** [t3-oss/create-t3-turbo#182]
### Describe the feature you'd like to request

I've been running into issues with my db package not getting changes that are saved to my local `.env` file. 

Right now t3-turbo is set up to run `dotenv-cli` under  ~`devDependencies`~ `dependencies` on the various apps/packages within the monorepo.

This conflicts with [turborepo's docs](https://turbo.build/repo/docs/handbook/environment-variables), which add `dotenv-cli` as a `devDependency` on the root project, and to run `turbo XXX` commands with it.

### Describe the solution you'd like to see

1. add `dotenv-cli` as a dev dependency in the project's root Package.json
2. remove `dotenv-cli` as a dev dependency in  `apps/*/package.json` and `packages/*/package.json`
3. in the root `package.json` file, add `dotenv-cli --` as a prefix before the `turbo XYZ` scripts that need environment variables

**Comment by mbifulco** [comment]
Just an update on this -  `manypkg check` reports that having anything in devDependencies on the root `package.json` file for a private repo, so I think the right course of action here is to put `dotenv-cli` in the root project's standard dependencies.

```bash
Run pnpm manypkg check
☔️ error the root package.json contains devDependencies, this is disallowed as devDependencies vs dependencies in a private package does not affect anything and creates confusion.
☔️ info the above errors may be fixable with yarn manypkg fix
Error: Process completed with exit code 1.
```

**Comment by juliusmarminge** [comment]
Yea we can do that 👍

**Comment by juliusmarminge** [comment]
Done
