### ISSUE TITLE
bug: no node_modules in package/db folder

### ISSUE THREAD

**Issue by MadaShindeInai** [t3-oss/create-t3-turbo#189]
### Provide environment information

  System:
    OS: macOS 13.2.1
    CPU: (8) arm64 Apple M1
    Memory: 712.28 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.13.0 - ~/.nvm/versions/node/v18.13.0/bin/node
    Yarn: 1.23.0-20220130.1630 - /opt/homebrew/bin/yarn
    npm: 8.19.3 - ~/.nvm/versions/node/v18.13.0/bin/npm
    Watchman: 2021.09.27.00 - /opt/homebrew/bin/watchman

### Describe the bug

When i stop local development with "control + c" in terminal i see "node_modules missing" warning:
<img width="540" alt="Screenshot 2023-02-26 at 10 12 22" src="https://user-images.githubusercontent.com/50995397/221402231-78609a21-6877-4179-94a4-8f65557833b8.png">  
Node_modules are really do not exist in packages/db folder, but i do not see issues during development or deployment of an app. I checked it on newly created app from template and see the same behaviour.
Is it a feature of turbo/pnpm or a bug that i still did not face during development?

### Link to reproduction

localhost:3000

### To reproduce

1. Init new app with this template
2. run it locally
3. stop it with "control + c" in your terminal
4. check warnings
<img width="698" alt="Screenshot 2023-02-26 at 10 24 21" src="https://user-images.githubusercontent.com/50995397/221402461-bd17cd18-aa7a-40d4-b670-ceebc8ef872c.png">

**Comment by juliusmarminge** [comment]
That's just the way it is since we hoist prisma and all that.

Doesn't  matter functionality wise other than that warning
