### ISSUE TITLE
bug: superejson or trpc (or both) messes with trpc infered types

### ISSUE THREAD

**Issue by kockar96** [t3-oss/create-t3-turbo#191]
### Provide environment information

Versions:
    "@trpc/client": "^10.9.0",
    "@trpc/server": "^10.9.0",
    "superjson": "1.12.2", 

### Describe the bug

You upgraded  "superjson": "1.9.1 -> ^1.12.1" which introduced weird behavior which you can see in the picture below.
<img width="1106" alt="Screenshot 2023-03-02 at 12 13 42" src="https://user-images.githubusercontent.com/116439489/222415155-d4cd7ca3-5ae4-4891-930e-bcab531cb715.png">
****

### Link to reproduction

https://stackoverflow.com/questions/74585421/trpc-mutateasync-returns-nothing/75614613#75614613

### To reproduce

But also suggestions are entirely messed up. But after downgrading it to version '1.9.1' all started working as expected.
I tried with different versions of "superjson" and trpc client and server and it looks like the combination of those two is the problem. The reason I believe that is when versions "@trpc/client": "^10.13.2 -> ^10.9.0" and   "@trpc/server": "^10.13.2 -> ^10.9.0", are installed with  "superjson": "1.9.1 -> ^1.12.1"  the same thing happens.

### Additional information

 This is in WebStorm I haven't tested it in VSCode or other code editors.

Also, I am not sure how to provide you with a link so I will just paste StackOverflow post with people having a problem that is related.

**Comment by juliusmarminge** [comment]
Not sure why i updated it. Reverted down to 1.9 again.
