### ISSUE TITLE
Question: How to hook up psql w/ supabase (expo app)

### ISSUE THREAD

**Issue by rrdesignweb** [t3-oss/create-t3-turbo#193]
Hi there wondering fi someone can point me in the right direction, (bit of a newbie to all this stuff)

I have been testing my expo app on emulator and physical device with `expo start --android` command with no issues using the sqlite provider, I have since switched over to `postgresql` and hosting the db with supabase. Added supbase DATABASE_URL, did my `pnpm db:push` , `prisma migrate dev`, seeded the database etc 

I am now testing with `expo run:android --device ...` as well an eas build testing the build on google play store with internal testing. At first the app was crashing after the splash screen appeared and displaying this message `Failed to get localhost. Please point to your production server.`

<pre>
 const localhost = Constants.manifest?.debuggerHost?.split(":")[0];
   console.log("Manifest", Constants.manifest?.debuggerHost?.split(":")[0])
      if (!localhost) {
        return `http://localhost:8081`; //added this in as I noticed the app was running on this in the console
        throw new Error(
          "Failed to get localhost. Please point to your production server.",
        );
      }
 return `http://${localhost}:3000`;
</pre>

I noticed that the console log I added `console.log("Manifest", Constants.manifest?.debuggerHost?.split(":")[0])` was logging `LOG Manifest undefined` 
I since added as above `return "http://localhost:8081"; //added this in as I noticed the app was running on this in the console` I am not if this is supposed to be correct? 
After I added this the app seems to work and not crash, however there is no data coming through for my trpc useQuery calls (both google play internal testing and expo run testing) I get this error `[TRPCClientError: JSON Parse error: Unexpected token: <]`

Wondering what moving parts i need this to work, example bring in the supabase library i:e

<pre>
import { createClient } from "@supabase/supabase-js";
import AsyncStorage from "@react-native-async-storage/async-storage";

const supabaseURL = `${process.env.SUPABASE_URL}`;
const supabaseAnonKey = `${process.env.SUPABASE_ANON_KEY}`;

export const supabase = createClient(supabaseURL, supabaseAnonKey, {
    db: {
        schema: 'public',
    },
    auth: {
        storage: AsyncStorage,
        autoRefreshToken: true,
        persistSession: true,
        detectSessionInUrl: false,
    },
});
</pre>

Hook it up to trpc someway in context? Or is it somekind of CORS issue? I am not really sure

Thanks in advance!

**Comment by juliusmarminge** [comment]
You need your server running in order for the trpc calls to work, the `getBaseUrl` should point to your server location. If you wanna try your app in a real environment you should therefore deploy the server and point the url there.

For local dev though it should just work I think? Although not sure since I've never really used supabase and especially not the combination of prisma and supabase client, so not sure if there are any restrictions there.
