### ISSUE TITLE
bug: TRPCClientError when running default app on Android

### ISSUE THREAD

**Issue by milmillin** [t3-oss/create-t3-turbo#197]
### Provide environment information

  System:
    OS: Windows 10 10.0.22624
    CPU: (16) x64 Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz
    Memory: 15.45 GB / 31.92 GB
  Binaries:
    Node: 18.14.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.11 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 9.5.0 - C:\Program Files\nodejs\npm.CMD

### Describe the bug

The app cannot connect to the database. The web version can connect just fine.

![Screenshot_1678168642](https://user-images.githubusercontent.com/20612904/223333441-85036537-c5f6-4dcb-bc19-1bbe138803fc.png)
![Screenshot_1678168714](https://user-images.githubusercontent.com/20612904/223333479-0d9982d2-529e-4568-8f3e-ca6f8ebb2217.png)

### Link to reproduction

https://github.com/t3-oss/create-t3-turbo

### To reproduce

Just follow the instruction for Android.
```
pnpm i
# change provider to "sqlite"
cp .env.example .env
pnpm db:push
# change dev script to "expo start --android"
pnpm dev
```

**Comment by juliusmarminge** [comment]
Is it blocking on CORS? Do you have the correct URL set on the expo app? The current `getBaseUrl` might not work in all cases

**Comment by milmillin** [comment]
Yeah, I figured I need to hardcode the IP address in the `getBaseUrl` in `apps/expo/src/utils/api.tsx`.

**Comment by juliusmarminge** [comment]
> Yeah, I figured I need to hardcode the IP address in the `getBaseUrl` in `apps/expo/src/utils/api.tsx`.

If you find a more compatible way to detect the host ip feel free to share. I found the current one is reliable on ios and i know it works on some android / windows setups but prob not the best
