### ISSUE TITLE
Prisma import in examples points to wrong location

### ISSUE THREAD

**Issue by Niclassg** [t3-oss/create-t3-turbo#2]
Hello, awesome template!

When I used the template I simply did a `npm i` in the root and I noticed I got an error in `apps/nextjs/src/pages/api/examples.ts` on line `3` . I had to change the import to `import { prisma } from "../../../../../packages/db"` before the prisma client could be found.

[examples.ts](https://github.com/t3-oss/create-t3-turbo/blob/main/apps/nextjs/src/pages/api/examples.ts#L3)

Please let me know if I did something wrong here.

**Comment by juliusmarminge** [comment]
Ah missed that file.

We shouldn't import like that. Either include the db as a dependency or just rely on tRPC as the bridge between

**Comment by juliusmarminge** [comment]
Fixed!
