### ISSUE TITLE
bug: PrismaClientInitializationError on setup

### ISSUE THREAD

**Issue by simon-v-swyftx** [t3-oss/create-t3-turbo#202]
### Provide environment information

```
  System:
    OS: macOS 13.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 3.05 GB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.14.2 - ~/Library/Caches/fnm_multishells/93213_1678273488789/bin/node
    Yarn: 3.2.4 - ~/Library/Caches/fnm_multishells/93213_1678273488789/bin/yarn
    npm: 9.5.0 - ~/Library/Caches/fnm_multishells/93213_1678273488789/bin/npm
```

### Describe the bug

Hey folks, get the following error when running `pnpm dev`

```
PrismaClientInitializationError: Your schema.prisma could not be found, and we detected that you are using Next.js.
Find out why and learn how to fix this: https://pris.ly/d/schema-not-found-nextjs
```

### Link to reproduction

https://github.com/simon-v-swyftx/turbo

### To reproduce

Generate repo
Remove expo
Use sqlite
copy env
run db:push
run `pnpm dev`
goto `localhost:300`
observe error

### Additional information

Happy to follow the instructions on the article, just wondered if this was meant to be part of the template?

**Comment by PiotrekPKP** [comment]
Your reproduction repo is probably set private (it 404s) :)

Is the `pnpm db:push` command working properly, or does it show errors on both `pnpm db:push` and `pnpm dev`?

**Comment by simon-v-swyftx** [comment]
Welp just cloned on a new PC and it works fine 🤦 the db just have gotten into a bad state. Thanks for your help anyway!
