### ISSUE TITLE
Storybook integration

### ISSUE THREAD

**Issue by Tobjoern** [t3-oss/create-t3-turbo#203]
### Describe the feature you'd like to request

Having the ability to create an easy-to-use storybook implementation.
This may be a separate package, but could also be integrated into the nextjs app itself.

### Describe the solution you'd like to see

I think the feature is self-explanatory.

### Additional information

-

**Comment by juliusmarminge** [comment]
might make a more full-featured template with a bunch more stuff that you could take inspo from, although i don't have the time right now...

**Comment by pegak** [comment]
Something like EpicStack but for T3 stack, @juliusmarminge?

**Comment by juliusmarminge** [comment]
Don't have the bandwidth to do this right now
