### ISSUE TITLE
[Question] API's dependencies

### ISSUE THREAD

**Issue by vcapretz** [t3-oss/create-t3-turbo#208]
Since the api package is a dependency for the native app, how's the flow to include dependencies that are backend only? 
I have tRPC procedures that depend on `stripe` and `firebase-admin` packages, but ideally they wouldn't be included in the app just because I use the api package to get the types and fetch the queries 

Thanks in advance for any clarification 😄

**Comment by juliusmarminge** [comment]
api package id a devDep in the expo app, it only needs to be a prod dep in the nextjs app which serves the api

**Comment by vcapretz** [comment]
ah that makes sense! thank you 🙏
