### ISSUE TITLE
bug: cache always missed

### ISSUE THREAD

**Issue by AlvaroAquijeDiaz** [t3-oss/create-t3-turbo#209]
### Provide environment information

  System:
    OS: macOS 13.2.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 86.66 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 19.8.1 - /opt/homebrew/bin/node
    npm: 9.5.1 - /opt/homebrew/bin/npm
    Watchman: 2023.01.16.00 - /opt/homebrew/bin/watchman

### Describe the bug

I already linked turbo and the vercel project but the cache is always missed on production deployments and local

`pnpm run build` - I need to run this twice for the log to say `cache hit`, but whenever there's any change it misses right away again

```
@zwei/db:db:generate: const prisma = new PrismaClient()
@zwei/db:db:generate: ```
@zwei/www:build: cache hit, replaying output 57cf1f63d1d07df3
@zwei/www:build: 
@zwei/www:build: > @zwei/www@0.1.0 build /Users/a3tech/Developer/personal_projects/id-like-turbo/apps/www
@zwei/www:build: > next build
@zwei/www:build: 
@zwei/www:build: info  - Linting and checking validity of types...
@zwei/www:build: info  - Creating an optimized production build...
@zwei/www:build: info  - Compiled successfully
@zwei/www:build: info  - Collecting page data...
@zwei/www:build: info  - Generating static pages (0/3)
@zwei/www:build: info  - Generating static pages (3/3)
@zwei/www:build: info  - Finalizing page optimization...
@zwei/www:build: 
@zwei/www:build: Route (pages)                              Size     First Load JS
@zwei/www:build: ┌ ○ /                                      3.48 kB         111 kB
@zwei/www:build: ├   /_app                                  0 B             107 kB
@zwei/www:build: ├ ○ /404                                   181 B           107 kB
@zwei/www:build: ├ λ /api/auth/[...nextauth]                0 B             107 kB
@zwei/www:build: └ λ /api/trpc/[trpc]                       0 B             107 kB
@zwei/www:build: + First Load JS shared by all              109 kB
@zwei/www:build:   ├ chunks/framework-19f3649580393c10.js   45.2 kB
@zwei/www:build:   ├ chunks/main-c72d876ee674f970.js        26.9 kB
@zwei/www:build:   ├ chunks/pages/_app-45fd38b829a0f5ad.js  34.2 kB
@zwei/www:build:   ├ chunks/webpack-8fa1640cc84ba8fe.js     750 B
@zwei/www:build:   └ css/a4b4cc2ab19dfa8d.css               2.27 kB
@zwei/www:build: 
@zwei/www:build: λ  (Server)  server-side renders at runtime (uses getInitialProps or getServerSideProps)
@zwei/www:build: ○  (Static)  automatically rendered as static HTML (uses no initial props)
@zwei/www:build: 
```

### Link to reproduction

https://codesandbox.io/p/github/AlvaroAquijeDiaz/turbo-cache-bug/main?workspaceId=fc6d1353-f6d0-46c5-9481-b401aeb46f0e&file=/README.md

### To reproduce

1. clone
2. link turbo to vercel project
3. turbo run build

shows cache miss

### Additional information

I've followed all the steps on the guide about how to setup the project and yet, it doesn't seem to work

**Comment by juliusmarminge** [comment]
> pnpm run build - I need to run this twice for the log to say cache hit, but whenever there's any change it misses right away again

I don't quite understand - what are you changing? Are you not expecting that this change to bust the cache?

**Comment by AlvaroAquijeDiaz** [comment]
what I meant by that was that after changing any file inside the next app, like adding pages or updating a page; the cache is always missed, maybe I'm wrong and this is expected in turborepo?

**Comment by juliusmarminge** [comment]
So for example, are you expecting a cache hit for pageA and pageB if you change pageC or add a new pageD?

**Comment by juliusmarminge** [comment]
Currently, the only app/package that has a `build` script is the nextjs app, but if you add more packages, perhaps a UI pacakge and build that, you should see the benefits of the turbo cache in that changing nextjs wouldn't cause the ui to cache miss. But the cache is not as granular down to individual pages

**Comment by AlvaroAquijeDiaz** [comment]
ah I get it now thanks a lot!
