### ISSUE TITLE
feat: Changesets

### ISSUE THREAD

**Issue by osilkin98** [t3-oss/create-t3-turbo#213]
### Describe the feature you'd like to request

Turborepo currently recommends [changesets](https://github.com/changesets/changesets) as the method of managing dependencies and changes between packages. It would nice to see this integrated into create-t3-turbo.

### Describe the solution you'd like to see

A minimum would just be a working example within the current repo of how changesets can be configured, so that new users could have a reference for how their monorepo should be organized.

**Comment by juliusmarminge** [comment]
The repo doesn't really contain any package that needs versioning. What do you suggest?

**Comment by osilkin98** [comment]
I guess what I'm thinking more of is having the packages getting their version bumped according to semver rules when changes are made to the overall package. I understand that this is more of a demo project, so maybe it's unnecessary, but it would be really useful to see how the versioning of this repo progresses as changes continue to be made. 

In that respect, it would be great to see changesets integrated so that it's clear which packages evolved with what change.

**Comment by juliusmarminge** [comment]
Eehm that's not really the plan for this repo and I don't think I'd want to maintain that. Changes are best tracked by watching PRs. I'll try to be better at naming conventions in that regard.

Gonna go ahead and close this for now. If the request comes up again, I might reconsider.
