### ISSUE TITLE
bug: importing prisma from @acme/db is always type any

### ISSUE THREAD

**Issue by dylanclements** [t3-oss/create-t3-turbo#217]
### Provide environment information

  System:
    OS: macOS 13.2.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 97.52 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.14.2 - ~/.nvm/versions/node/v18.14.2/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 9.5.0 - ~/.nvm/versions/node/v18.14.2/bin/npm

### Describe the bug

`package/db/index.ts` indicates that export { prisma } is type PrismaClient

on import, prisma is always inferred as type any causing lints to fail

`.prisma/client/index.d.ts` contains correct types corresponding to the schema

Thanks

### Link to reproduction

clone the repo

### To reproduce

Clone the repo, `pnpm i`, `cp .env.example .env`, `pnpm db:push`, `pnpm dev`

Observe any `import { prisma } from '@acme/db` where prisma is type any

### Additional information

If this is intended behaviour, could I please be pointed towards some documentation because I'm having a hard time trying to understand.

**Comment by dylanclements** [comment]
<img width="1208" alt="Screenshot 2023-03-23 at 10 41 23 am" src="https://user-images.githubusercontent.com/58539346/227062889-da6ba7ea-9163-4804-80a2-ed0914998930.png">
<img width="403" alt="Screenshot 2023-03-23 at 10 42 06 am" src="https://user-images.githubusercontent.com/58539346/227062968-d4e158ba-5c45-447a-9794-b1dd8190dc13.png">

**Comment by Diogovski** [comment]
i had a problem where, every time i called ctx.prisma it would throw the "any" error, running db:generate and restarting vscode worked, it might solved that

**Comment by juliusmarminge** [comment]
Anyone else able to reproduce it? Works fine on my end

**Comment by dylanclements** [comment]
.prisma was not hoisted in `node_modules/` I believe due to me running pnpm i in `packages/db` directory

After wiping `packages/db/node_modules/`, then `pnpm db:push` and restart eslint and typescript servers, issue was resolved
