### ISSUE TITLE
Issue using Expo Vector Icons

### ISSUE THREAD

**Issue by justindc100** [t3-oss/create-t3-turbo#22]
Potentially an issue with getting to the icons package. I am able to import the icon family in the code and use it, and it auto-fills the names of the available icons, but I cannot get it to display anything.  The following error is displayed in the log.  I checked online for it, and it some people encountered an issue that this error was thrown if their file name had spaces in it, but I cannot see how that would apply here.  I tried this with multiple font families and got the same error on all.

`Error: Downloaded file for asset 'Ionicons.ttf' Located at http://192.168.1.220:19000/assets/../../node_modules/@expo/vector-icons/build/vendor/react-native-vector-icons/Fonts/Ionicons.ttf?platform=android&hash=b3263095df30cb7db78c613e73f9499a?platform=android&dev=true&hot=false failed MD5 integrity check`

Works on a new expo app.

**Comment by justindc100** [comment]
So had a chance to take a look at this, and it looks like it is just having a problem with how turborepo is interacting with how expo is trying to import the icon fonts.  Adding `"@expo/vector-icons": "^12.0.0",` to the expo package.json and running npm install resolves the issue.  I can make a PR to resolve the issue for future users if I get the chance and this ends up being the best solution.

The only issue is that it ends up installing those files twice, so it will marginally increase app size.  There might be a more elegant solution, but this appears to be the quick and dirty fix.

**Comment by juliusmarminge** [comment]
> So had a chance to take a look at this, and it looks like it is just having a problem with how turborepo is interacting with how expo is trying to import the icon fonts.  Adding `"@expo/vector-icons": "^12.0.0",` to the expo package.json and running npm install resolves the issue.  I can make a PR to resolve the issue for future users if I get the chance and this ends up being the best solution.
> 
> 
> 
> The only issue is that it ends up installing those files twice, so it will marginally increase app size.  There might be a more elegant solution, but this appears to be the quick and dirty fix.

I don't quite follow what the issue is. Of course you need to add it to the package.json dependencies if the app uses them? Or is it some issue with peer dependencies or something? Need more context

**Comment by justindc100** [comment]
Sorry, I might not have explained this properly.  Expo Vector icons is a package that is installed by default along with expo, that allow you to easily use Icon libraries without having to install anything normally [](https://docs.expo.dev/guides/icons/).   When I attempted to do this in create t3 turbo, I could import the icons and VSCode would recognize them and have all of the autocomplete, but when I tried to run it, I was getting the error above that it was unable to load the actual font file.  I think this has something to do with the fact that vector icons has a build folder that needs to be in the same directory as the app, and this was not happening without manually adding that line to the expo package.json

**Comment by juliusmarminge** [comment]
> Sorry, I might not have explained this properly.  Expo Vector icons is a package that is installed by default along with expo, that allow you to easily use Icon libraries without having to install anything normally [](https://docs.expo.dev/guides/icons/).   When I attempted to do this in create t3 turbo, I could import the icons and VSCode would recognize them and have all of the autocomplete, but when I tried to run it, I was getting the error above that it was unable to load the actual font file.  I think this has something to do with the fact that vector icons has a build folder that needs to be in the same directory as the app, and this was not happening without manually adding that line to the expo package.json

I see, does it happen on the "latest" version? We had an Expo member here configuring the metro config for monorepo usage so it should look for packages in root too

**Comment by juliusmarminge** [comment]
Just tested this on the latest version and it works just fine to use without additional install: 

![CleanShot 2022-10-04 at 00 22 50](https://user-images.githubusercontent.com/51714798/193696639-5c13ec39-4cd3-414b-b954-5604e3bd559b.png)
