### ISSUE TITLE
Next.js not working

### ISSUE THREAD

**Issue by andredsnogueira** [t3-oss/create-t3-turbo#24]
Since last commit (64ec6ac38cc67786574c945bfac28bdff4803e8c) the Next.js app is not working anymore.
When I run `npm run dev` some errors appear on the console.

`Server Error
TypeError: Cannot read properties of null (reading 'useContext')`

I tried with the previous commit and it was working.

**Comment by juliusmarminge** [comment]
Fixed. Had mismatching React versions... Might have to add some CI into this to catch some dumb errors 😢

Thanks for reporting!
