### ISSUE TITLE
Solito or other crossplatform navigation?

### ISSUE THREAD

**Issue by redbar0n** [t3-oss/create-t3-turbo#25]
I see that [Solito](https://solito.dev) is not included. What is your thinking around including Solito or other tools for unifying navigation across native and web?

**Comment by juliusmarminge** [comment]
This was my reasoning for making this template: https://twitter.com/jullerino/status/1565733252492627968?s=20&t=KGUdrDtuFp84o34ImRgP4g

TLDR; I think Solito, create-kaol-app, zART are all a bit overcomplicated for demonstrating how the t3-stack plays in mobile development. I am however intrigued by the new Expo Router stuff coming so maybe we'll include that 🤔

**Comment by redbar0n** [comment]
Thanks. zART was even less batteries included than this, iirc. I didn't know about [create-kaol-app](https://github.com/chamatt/create-kaol-app), it looks nice.

FYI, if you don't go the Expo Router path, you could use [react-native-url-router](https://github.com/software-mansion-labs/react-native-url-router) which aligns with [React Router](https://reactrouter.com/) even for native.

**Comment by juliusmarminge** [comment]
> Thanks. zART was even less batteries included than this, iirc.

I don't agree with this. zART includes testing, theming and a few other things. Just take a look at the [Expo app's dependency list](https://github.com/trpc/zart/blob/4aaed67ce41ffc3d7e4eb1e7582fa98834f074e6/apps/expo/package.json#L33-L72). It hoisted everything so (at least I) had a hard time tracking what was going on, what was used where, "how is that package using that when it's not a dependency" etc. 

Karl App is a lot of batteries included including Solito.

I am not saying any of these are bad in any way, I am just saying the main goal of this was to aim for a minimal setup of trpc + next + expo.

**Comment by VidunderGunder** [comment]
You guys might like this:
https://github.com/VidunderGunder/create-xp-app
