### ISSUE TITLE
bug: npx @turbo/codemod update complains about yarn command not found?

### ISSUE THREAD

**Issue by codeagencybe** [t3-oss/create-t3-turbo#251]
### Provide environment information

  System:
    OS: macOS 13.2.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 186.05 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.7.0 - ~/.nvm/versions/node/v18.7.0/bin/node
    npm: 9.1.3 - ~/.nvm/versions/node/v18.7.0/bin/npm

### Describe the bug

I got a message about an update available when running turbo build lint. 
When I run the update command, it complains about yarn command missing, while I started everything with pnpm.
I don't and never used yarn anywhere in my project. 

Is this is a bug coming from the t3-turbo stack or something I need to start looking up in turborepo specific? 

<img width="650" alt="image" src="https://user-images.githubusercontent.com/7568546/228557202-2fcf97ac-aad3-4cb7-a052-46fe09019a2f.png">

```
npx @turbo/codemod update --force
WARNING: Git directory is not clean. Forcibly continuing...
? Where is the root of the repo to migrate? .
No codemods required to migrate from 1.8.3 to 1.8.6 

Upgrading turbo from 1.8.3 to 1.8.6 (no codemods required) 

/bin/sh: yarn: command not found
Migration failed
Unable to determine upgrade command
```

### Link to reproduction

n/a

### To reproduce

Run the command

`npx @turbo/codemod update 
`
or 

`npx @turbo/codemod update --force
`
after initializing a t3-turbo project from an older turbo version.

**Comment by juliusmarminge** [comment]
Can't see how this would be caused by anything in this repo. Most likely a turbo issue?

**Comment by juliusmarminge** [comment]
Also try `pnpm dlx @turbo/codemod update`

**Comment by juliusmarminge** [comment]
Just verified the above command works:

<img width="798" alt="CleanShot 2023-04-04 at 00 21 17@2x" src="https://user-images.githubusercontent.com/51714798/229639886-546eef73-f38f-4516-9df3-ce21dfa3d535.png">
