### ISSUE TITLE
Question about which create-t3-thingy to use

### ISSUE THREAD

**Issue by spcbfr** [t3-oss/create-t3-turbo#256]
Say I am building a web app and a mobile app, what's the easiest way to do that using one of you're repos, create-t3-app, create-t3-turbo, [t3-turbo-and-clerk](https://github.com/clerkinc/t3-turbo-and-clerk) or a combination of those?

**Comment by juliusmarminge** [comment]
If you use the clerk template you can probably pick and match a bit. I dont think that repo has kept up with changes lately, but you can always use the clerk parts of it!

**Comment by spcbfr** [comment]
Makes sense, thanks guys @juliusmarminge @nordinvandijk !
