### ISSUE TITLE
bug: ios bundling failed

### ISSUE THREAD

**Issue by nordinvandijk** [t3-oss/create-t3-turbo#257]
### Provide environment information

  System:
    OS: macOS 12.4
    CPU: (8) arm64 Apple M1
    Memory: 357.00 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.15.0 - ~/.nvm/versions/node/v18.15.0/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.5.0 - ~/.nvm/versions/node/v18.15.0/bin/npm

### Describe the bug

error: index.tsx: [BABEL] /Users/nordin/Documents/GitHub/gymapp/apps/expo/index.tsx: Cannot use import statement outside a module (While processing: "/Users/nordin/Documents/GitHub/gymapp/node_modules/nativewind/babel.js")

<img width="1440" alt="Screenshot 2023-03-31 at 19 41 43" src="https://user-images.githubusercontent.com/32980858/229191910-c9461bf4-451d-472d-93ba-728d22de1833.png">

### Link to reproduction

None

### To reproduce

All the normal installation steps and instead of using "expo start --ios", "expo start" for dev script.

### Additional information

NextJS app DOES work.

**Comment by CarlosBM18** [comment]
The same happens to me 🤔

**Comment by juliusmarminge** [comment]
Its the tailwind ts config. Pushed a patch now, will request support for ts config on Nativewind

**Comment by nordinvandijk** [comment]
Works like a charm, babyyyy :) Thnx @juliusmarminge 
<img width="210" alt="Screenshot 2023-04-01 at 14 08 26" src="https://user-images.githubusercontent.com/32980858/229287795-42170bb3-dae0-4e5c-a018-b95ede81bd81.png">
