### ISSUE TITLE
TRPCClientError when running default app on iOS

### ISSUE THREAD

**Issue by johann-taberlet** [t3-oss/create-t3-turbo#26]
I tried to clone and run this repo by following the Readme:

- added Sqlite as the prisma provider
- `echo DATABASE_URL=file:./db.sqlite >> packages/db/.env`
- ran `npm run db-push`
- changed dev script in expo app to `"dev": "expo start --ios"`
- ran `npm run dev` at the root of the project

Next app and Prisma studio run both well without errors/warnings but on the iOS simulator (iPhone 14 Pro Max) a warning appear on expo app at launch and when I try to add a post (posts are not added to the db so mutation fails): 
![SCR-20221003-vfp](https://user-images.githubusercontent.com/9981334/193678699-ff4078f3-30cc-4155-b8ee-51c71c1887f8.png)

This is logged in the console which run the process: 
`WARN  [TRPCClientError: JSON Parse error: Unrecognized token '<']`

Any ideas on what's going wrong here ?

MacOS 12.6
M1 Pro chip
Node v16.17.0

iPhone 14 Pro Max
iOS 16

**Comment by johann-taberlet** [comment]
I actually have this when I run `npm run dev`
![SCR-20221003-vsy](https://user-images.githubusercontent.com/9981334/193680498-118ee5ab-aa51-4470-a974-6b1708e5d5c8.png)

**Comment by juliusmarminge** [comment]
I'll look into it.

> I actually have this when I run `npm run dev`
> ![SCR-20221003-vsy](https://user-images.githubusercontent.com/9981334/193680498-118ee5ab-aa51-4470-a974-6b1708e5d5c8.png)

Those should all be fine to ignore.

**Comment by juliusmarminge** [comment]
![CleanShot 2022-10-04 at 00 05 00](https://user-images.githubusercontent.com/51714798/193694363-efb4f8f1-afb5-41c9-a451-320a7cb64fa8.png)

My app booted perfectly fine with your repro steps.

Can you try and log out the error you are getting from trpc?

```ts
const postQuery = trpc.post.all.useQuery();

console.log(postQuery.error)
```

**Comment by johann-taberlet** [comment]
Oh god, I had an other `next dev` running in the background and that's what causes the issue... Really sorry for the fake issue. It works well now.
I just have an issue with VSCode which doesn't interpret TS correctly in my project but it's the first time I work with tubo repo so maybe something related ?

**nextjs/pages/index.tsx:**

![SCR-20221004-d3c](https://user-images.githubusercontent.com/9981334/193759673-50c85afc-5504-48b8-8d97-6c53251bf48f.png)

**expo/screens/home.tsx:**

![SCR-20221004-d3u](https://user-images.githubusercontent.com/9981334/193759880-673bf959-8d72-4100-aeac-be82a5b9288b.png)

I already tried to restart TS server, reload the window and restart VSCode entirely.

Any ideas ?

**Comment by juliusmarminge** [comment]
Try setting this rule to make sure VSCode knows where to find the Typescript compiler, maybe you are using a different version or something that doesn't match with the project:

https://github.com/t3-oss/create-t3-app/blob/2300e23bd97c81e400f1a4927221fe2dc8e93a07/.vscode/settings.json#L8

**Comment by johann-taberlet** [comment]
Version didn't solve the issue, I had to redefine how to interpret tsx files for both next and expo folder. 
Very weird but as I said it's the first time I work with turbo repo.

Everything seems to work as expected now.

Thanks a lot for everything Julius !
