### ISSUE TITLE
feat: Better typescript language server performance

### ISSUE THREAD

**Issue by jangrunicke** [t3-oss/create-t3-turbo#277]
### Describe the feature you'd like to request

After growing my application using this template I am now running into heavy performance issues with my typescript language server. I basically have to restart the server multiple times when working on any file. I already increased the server memory but it does not really fix this issue.

### Describe the solution you'd like to see

I am no expert on this, but I think Theo mentioned in one of his videos that he has the same issues with his projects and that there might be a way to tell the ts-server which contents should basically be "lazy loaded" as far as I understood.

**Comment by juliusmarminge** [comment]
Project References is what you're reaching for I think.

Should prob set that up - don't have bandwidth now though so PRs accepted!

**Comment by jangrunicke** [comment]
Okay, I was not aware of the project reference concept. When trying it out and reading a bit more about it I found this
https://turborepo.com/posts/you-might-not-need-typescript-project-references from where I learned how the current implementation works (at least I think it does so). But there I also found this out:

"This pattern rocks because it saves you from extra needless or duplicative build steps. It also gives you all the editor benefits of project references but without any configuration."

So I doubt that project references will increase my editor's performance. Do you have any other ideas on how we could improve the performance?

**Comment by Geebrox** [comment]
> Okay, I was not aware of the project reference concept. When trying it out and reading a bit more about it I found this https://turborepo.com/posts/you-might-not-need-typescript-project-references from where I learned how the current implementation works (at least I think it does so). But there I also found this out:
> 
> "This pattern rocks because it saves you from extra needless or duplicative build steps. It also gives you all the editor benefits of project references but without any configuration."
> 
> So I doubt that project references will increase my editor's performance. Do you have any other ideas on how we could improve the performance?

Could you let me know if you were able to solve that? If yes, can you please describe the solution you came up with?

**Comment by ashutosh887** [comment]
@Geebrox @jangrunicke @juliusmarminge 
I would like to work on this one!
Please assign
