### ISSUE TITLE
feat: Migrate to NextJS 13 App Directory Pattern?

### ISSUE THREAD

**Issue by mikecfisher** [t3-oss/create-t3-turbo#280]
### Describe the feature you'd like to request

NextJS App Directory is almost stable. Seems like it's a good time to migrate. 

### Describe the solution you'd like to see

Migrate from Pages to App

### Additional information

I'm happy to do this and submit a PR for this but just wanted to check there was interest before doing so.

**Comment by Rykuno** [comment]
The mutations are still TBD i believe in the app dir. I'm assuming its a bit ways off if they have not even released the RFC. https://beta.nextjs.org/docs/data-fetching/mutating.

**Comment by juliusmarminge** [comment]
Will do once we do it in create-t3-app
