### ISSUE TITLE
bug: Creating expo updates from monorepo 'create-t3-turbo'

### ISSUE THREAD

**Issue by RitaGuyAvrahamCom** [t3-oss/create-t3-turbo#294]
### Provide environment information

 System:
    OS: macOS 13.3.1
    CPU: (8) arm64 Apple M1
    Memory: 152.17 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.14.2 - /usr/local/bin/node
    npm: 9.5.1 - /usr/local/bin/npm

### Describe the bug

When creating an expo eas update, there is not a single error, but when I scanning the application barcode, it crashes. 
I tested creating expo eas updates with default app (not monorepo) with the same versions, all was good

### Link to reproduction
exp://u.expo.dev/update/141f0853-2af4-43f4-a649-8f8006984c25

### To reproduce

- clone this 'create-t3-turbo'
- in the expo terminal run 'eas update'
- go to the https://expo.dev/accounts/`youraccount`/projects/`nameproject`/updates
- scan barcodes
On the ios you see that app is crashed
On the android, you will see loading

(Also you can try to use link higher, it was created original from 'create-t3-turbo')

**Comment by juliusmarminge** [comment]
Make sure to follow all the steps in the Readme, you need to point the trpc api to your production server, the default `getBaseUrl` uses the debugger host which is not available when the app is built 

https://github.com/t3-oss/create-t3-turbo/blob/656965aff7db271e5e080242c4a3ce4dad5d25f8/apps/expo/src/utils/api.tsx
