### ISSUE TITLE
pnpm dev error

### ISSUE THREAD

**Issue by rndy28** [t3-oss/create-t3-turbo#30]
Hi there, iam experiencing an issue after running pnpm dev

reproduce:
```
git clone https://github.com/t3-oss/create-t3-turbo
cd create-t3-turbo && pnpm i
// change db provider in prisma.schema
echo DATABASE_URL=file:./db.sqlite >> packages/db/.env
pnpm db-push
pnpm dev
// open localhost:3000
```
logs
```
@acme/nextjs:dev: error - Error: ENOENT: no such file or directory, open '/home/rndy/Documents/programming-related/Projects/portfolios/goodiebook-turborepo/apps/nextjs/.next/server/pages/api/trpc/schema.prisma'
@acme/nextjs:dev:     at Object.openSync (node:fs:594:3)
@acme/nextjs:dev:     at Object.readFileSync (node:fs:462:35)
@acme/nextjs:dev:     at new LibraryEngine (webpack-internal:///(api)/../../packages/db/node_modules/@prisma/client/runtime/index.js:26943:41)
@acme/nextjs:dev:     at PrismaClient.getEngine (webpack-internal:///(api)/../../packages/db/node_modules/@prisma/client/runtime/index.js:31383:16)
@acme/nextjs:dev:     at new PrismaClient (webpack-internal:///(api)/../../packages/db/node_modules/@prisma/client/runtime/index.js:31355:29)
@acme/nextjs:dev:     at eval (webpack-internal:///(api)/../../packages/db/index.ts:8:16)
@acme/nextjs:dev:     at Object.(api)/../../packages/db/index.ts (/home/rndy/Documents/programming-related/Projects/portfolios/goodiebook-turborepo/apps/nextjs/.next/server/pages/api/trpc/[trpc].js:374:1)
@acme/nextjs:dev:     at __webpack_require__ (/home/rndy/Documents/programming-related/Projects/portfolios/goodiebook-turborepo/apps/nextjs/.next/server/webpack-api-runtime.js:33:42)
@acme/nextjs:dev:     at eval (webpack-internal:///(api)/../../packages/api/src/context.ts:6:66)
@acme/nextjs:dev:     at Object.(api)/../../packages/api/src/context.ts (/home/rndy/Documents/programming-related/Projects/portfolios/goodiebook-turborepo/apps/nextjs/.next/server/pages/api/trpc/[trpc].js:330:1) {
@acme/nextjs:dev:   errno: -2,
@acme/nextjs:dev:   syscall: 'open',
@acme/nextjs:dev:   code: 'ENOENT',
@acme/nextjs:dev:   path: '/home/rndy/Documents/programming-related/Projects/portfolios/goodiebook-turborepo/apps/nextjs/.next/server/pages/api/trpc/schema.prisma',
@acme/nextjs:dev:   clientVersion: '4.4.0'
@acme/nextjs:dev: }
```

issue still persisted after  adding shamefully-hoist="true" to .npmrc

**Comment by juliusmarminge** [comment]
Have you tried running a `pnpm clean` and reinstalled the devs after adding the `.npmrc`?

**Comment by juliusmarminge** [comment]
Can't repro with your steps:

![CleanShot 2022-10-08 at 15 10 16](https://user-images.githubusercontent.com/51714798/194709272-97d7ebbe-e2b0-412b-9f26-8ad4e8770c87.png)

![CleanShot 2022-10-08 at 15 10 58](https://user-images.githubusercontent.com/51714798/194709275-363958de-dc0c-4a3f-9dda-16fc5b07d896.png)

**Comment by rndy28** [comment]
Thank your for the quick response. Its working now, but new error pop up

![2022-10-08-20:19:59-screenshot](https://user-images.githubusercontent.com/61275105/194709648-264e80b4-2ed3-4615-806b-f0f1afa520a2.png)

**Comment by juliusmarminge** [comment]
> Thank your for the quick response. Its working now, but new error pop up
> 
> ![2022-10-08-20:19:59-screenshot](https://user-images.githubusercontent.com/61275105/194709648-264e80b4-2ed3-4615-806b-f0f1afa520a2.png)

Again, I wasn't able to repro with your steps, you have a repo I can check? Are you getting this error if you pull a fresh version?

**Comment by rndy28** [comment]
> > Thank your for the quick response. Its working now, but new error pop up
> > ![2022-10-08-20:19:59-screenshot](https://user-images.githubusercontent.com/61275105/194709648-264e80b4-2ed3-4615-806b-f0f1afa520a2.png)
> 
> Again, I wasn't able to repro with your steps, you have a repo I can check? Are you getting this error if you pull a fresh version?

No i dont have, i dont get what you're saying, but iam just clone the repo and then follow the quick start in the readme

**Comment by juliusmarminge** [comment]
Here's a video of me pulling a fresh version without any errors: https://share.cleanshot.com/kgejQR

What node and pnpm versions you on?

**Comment by rndy28** [comment]
> Here's a video of me pulling a fresh version without any errors: https://share.cleanshot.com/kgejQR
> 
> What node and pnpm versions you on?

pnpm: 7.11.0
node: 16.17.1

**Comment by rndy28** [comment]
I also try change trpc version following this #15, but the error still there

**Comment by juliusmarminge** [comment]
can you push your repo and I can check if I get the error?

**Comment by rndy28** [comment]
> can you push your repo and I can check if I get the error?

[here](https://github.com/rndy28/t3-turborepo)

**Comment by juliusmarminge** [comment]
Cool yea I got the error now, I can see you're on a bit old versions and since you haven't really started yet, I'd recommend just cloning the latest version of this repo and start from there

**Comment by rndy28** [comment]
ohh, ok. Thank you!

**Comment by juliusmarminge** [comment]
reopen if the issue still persists after you pull latest

**Comment by rndy28** [comment]
> reopen if the issue still persists after you pull latest

Its working smoothly now. Thank you!
