### ISSUE TITLE
feat: Switch to yarn workspaces for the starter template (or make a branch)

### ISSUE THREAD

**Issue by pencilcheck** [t3-oss/create-t3-turbo#301]
### Describe the feature you'd like to request

I been noticing that all RN projects are supported better with yarn, everytime I use pnpm it just crash or having weird errors. It would be nice to have a starter that allow people to use yarn right away without worrying about pnpm

### Describe the solution you'd like to see

Switch to yarn, it is quite easy and straightforward conversion

**Comment by juliusmarminge** [comment]
Nope. All other templates out there use Yarn, go take a look there for reference.

I hate yarn and the support for pnpm gets better every update
