### ISSUE TITLE
Consider changing `@acme` to `@repo`

### ISSUE THREAD

**Issue by mmkal** [t3-oss/create-t3-turbo#308]
### Describe the feature you'd like to request

Right now the `@acme` name is a kind of "contagious" tech debt for users of this template, as an old colleague used to call it. When you run the create command, you can either find-and-replace all the instances of `@acme/` and change it to something like `@my-company/`, or you just leave it, and add more and more `import { ... } from '@acme/...'` statements over time.

Changing it has the disadvantage of drifting further from the template, so that applying updates later requires fiddling and more find-and-replace (which will disincentivize ever looking at this template again), and not changing it has the disadvantage of seeing an irrelevant and confusing fake team name littered all over the place.

### Describe the solution you'd like to see

Change `@acme` to something generic, that users might conceivably be happy with leaving as-is. An example that comes to mind is `@repo` - it'd actually be quite intuitive that `import { ... } from '@repo/db'` is a monorepo import, which is a nice hint to newcomers that it's part of the code that the team is managing themselves, rather than an external library, not under this repo's control.

### Additional information

It hadn't occurred to me before, but "leaking" a company name into undifferentiated code now seems to me like a bad thing, so I might actually have convinced myself in writing this issue that a package name like `@repo/db` is _better_ than a package name like `@acme/db`, even at a company named "Acme".

**Comment by nordinvandijk** [comment]
The npm scope is used for users and organizations (https://docs.npmjs.com/cli/v9/using-npm/scope). I therefore think that `@repo` is not a good name. Something like `@myorg` would be simpler to understand than `@acme` because `@acme` is a specific term. However, that specificity also makes it a good "learning moment". Perhaps mentioning this `@acme` point in the readme would be a good solution?

**Comment by mmkal** [comment]
Given this repo is a boilerplate, the scope can't correspond to an npm org since orgs need to have a particular owner. So I still think something generic would be better. `@myorg/` meets that requirement too but the "my" prefix makes it seem like a toy example/a little un-serious.

**Comment by juliusmarminge** [comment]
most codebases i've seen adapt the pattern that they have their product be the scope.

cal.com uses `@calcom/prisma` `@calcom/trpc` etc, i've seen this in other places too.

it might not be the company name - if your company works on multiple project this would likely be the project name, rigth? whatever i put in there will have to be changed, and so i don't see how any name is more generic than others? sure we could do `@changeme/api` or something (lol) but I don't see how that would be better?

**Comment by nordinvandijk** [comment]
> Given this repo is a boilerplate, the scope can't correspond to an npm org since orgs need to have a particular owner. So I still think something generic would be better. `@myorg/` meets that requirement too but the "my" prefix makes it seem like a toy example/a little un-serious.

I just like to name my private packages the same way as public npm packages. But I guess that's just preference. 

Just saw Vercel blog post using acme as well (https://vercel.com/blog/vercel-spaces), so that's reassuring. I would just leave it this way and only add some documentation.
