### ISSUE TITLE
bug: App crashes on start after installation on Android 

### ISSUE THREAD

**Issue by zanzlender** [t3-oss/create-t3-turbo#314]
### Provide environment information

  System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz
    Memory: 678.18 MB / 7.84 GB
  Binaries:
    Node: 18.15.0 - C:\Program Files\nodejs\node.EXE
    npm: 9.5.0 - C:\Program Files\nodejs\npm.CMD

### Describe the bug

This happens after creating a new repo from template, installing and setting up everything correctly. 

After I build only the .apk to try it out on Android, I can install the application on my phone (Huawei Mate 20 Pro) but it crashes as soon as it opens. More specifically, the Splash screen appears then it just closes.

There are no warnings, error messages or something like that. However, on the Expo app it works normally.

### Link to reproduction

Create a new project from the template and install

### To reproduce

In `/apps/expo/App.config.ts` I had to add package and version code so that EAS could build (if eas:configure works for you then you skip the first step)

```
android: {
  package: "com.yourcompany.yourappname",
  versionCode: 1,
  adaptiveIcon: {
    foregroundImage: "./assets/icon.png",
    backgroundColor: "#1F104A",
  },
},
```

then to build only .apk with EAS I had to add this in `/apps/expo/eas.json`

```
{
  build: {
    . . . 
    "test": {
      "android": {
        "buildType": "apk",
        "resourceClass": "large"
      }
    }, 
    . . .
  }
}
```

and finally, after logging in with EAS run `eas build --platform android --profile test`.

Afterwards you can download the .apk file from Expo and send it to your mobile phone, install it and try to run. (when trying to run it crashes)

**Comment by juliusmarminge** [comment]
Closing as stale - if the above didn't solve it for you, please reopen
