### ISSUE TITLE
What should I use instead of Next-Auth?

### ISSUE THREAD

**Issue by LansPeti** [t3-oss/create-t3-turbo#33]
Excuse me, if this isn't actually an issue, but I just want to know the best way of authentication with this stack, because I love it.

**Comment by juliusmarminge** [comment]
You need to make your own solution since nextauth doesnt work on native yet.

Maybe try auth0 or something like that?

**Comment by alexnault** [comment]
@LansPeti next-auth is coming to create-t3-turbo! https://github.com/t3-oss/create-t3-turbo/pull/36

**Comment by AshSimmonds** [comment]
I use Auth0 - tried half a dozen other ways and they were all much more convoluted and fragile.

Actually, here's the release notes from a couple months ago once I got it sorted:  
  
>After some harrowing times trying to get Supabase and NextAuth and that Iron one and a few other options trying to work, I was pulling my hair out cos NextJS/React/Supabase are right now in flux between major version stuff, and so getting all the pieces working together just kept failing.  
>
>Out of the blue I got an email from Auth0 mob who I haven't thought about for years. I think back in 2018 I had to implement auth but Auth0 was utterly awful to deal with getting working on AngularJS, and the boss hated the interstitial going away from the site for logging, and not "owning" the user data, and that it might eventually cost money, and various other things so I'd forgotten.  
>
>Anyhoo tried it for shits n giggles simply because I'd just wasted 2 days undoing a whole auth system that almost worked, but failed at crucial things and was still janky as hell, especially with React and it's useState() nightmares. Well, took less than 15mins to get Auth0 working, and it's really easy to get the data directly on the page to deal with straight away.  
>
>WHY IS AUTH STILL SO DIFFICULT? Ugh, I never want to deal with login stuff again, it sucks all the fun out of creating cool stuff.  
>
>Guess we'll never really trust each other.

**Comment by valerius21** [comment]
@juliusmarminge is the template currently working with expo now? I can't really tell from the merge messages and it's not working in my app either 😄 

Also, I was seeing this PR draft and it seems to be inactive for the time being https://github.com/nextauthjs/next-auth/pull/5240

**Comment by juliusmarminge** [comment]
> @juliusmarminge is the template currently working with expo now? I can't really tell from the merge messages and it's not working in my app either 😄 
> 
> 
> 
> Also, I was seeing this PR draft and it seems to be inactive for the time being https://github.com/nextauthjs/next-auth/pull/5240

Says in readme auth package doesn't work with expo just yet.

**Comment by jayp97** [comment]
Has any work been done on creating a solution to get next-auth working with expo? Once this is solved this will be an absolute game changer for cross platform development.

**Comment by valerius21** [comment]
@jayp97 https://github.com/nextauthjs/next-auth/pull/5240#issuecomment-1312543851 it seems to be abandoned for expo at the moment. I am trying to get clerk.dev working as a temporary solution. The last problem I am currently facing is making authenticated tRPC calls from react native. They also have [documentation](https://clerk.dev/docs/nextjs/trpc) on implementing their auth-provider service with tRPC

**Comment by valerius21** [comment]
I have worked up a solution with RN and tRPC capable of authentication and authed-tRP-requests. If there is any interest, HMU.

**Comment by jseitel** [comment]
@valerius21 color me interested!

**Comment by valerius21** [comment]
@jseitel I'll write something up after the weekend and link it :)

**Comment by JClackett** [comment]
@valerius21 Yes please!

**Comment by valerius21** [comment]
> @jayp97 [nextauthjs/next-auth#5240 (comment)](https://github.com/nextauthjs/next-auth/pull/5240#issuecomment-1312543851) it seems to be abandoned for expo at the moment. I am trying to get clerk.dev working as a temporary solution. The last problem I am currently facing is making authenticated tRPC calls from react native. They also have [documentation](https://clerk.dev/docs/nextjs/trpc) on implementing their auth-provider service with tRPC

and 


> I have worked up a solution with RN and tRPC capable of authentication and authed-tRP-requests. If there is any interest, HMU.

Took the time to write something up. I still think that using `next-auth` and supabase for example should be possible, even though it's not mentioned in the article. Maybe this  leads to something :)

https://www.valerius.me/posts/adding-authentication-and-authorization-to-create-t3-turbo-incl-expo-with-clerkdev

@JClackett @jseitel

**Comment by ebg1223** [comment]
If anyone is still looking for a solution, i've had this setup for a bit, just packaged it up to share:

https://github.com/ebg1223/create-t3-turbolito

clerk.dev auth, along with solito and expo router.

**Comment by Sn0wye** [comment]
> If anyone is still looking for a solution, i've had this setup for a bit, just packaged it up to share:
> 
> https://github.com/ebg1223/create-t3-turbolito
> 
> clerk.dev auth, along with solito and expo router.

working fine?

**Comment by ebg1223** [comment]
@Sn0wye working well for me! I am using this setup in production. I created this repo by moving over the code from a functional app, but as that app continues development, I am trying to keep the repo consistent but may fall behind. If you run into issues, let me know, I may have the solution and just forgot to move it to the template repo.

**Comment by Sn0wye** [comment]
> 

I'm analyzing which one works the best for me between Auth0 and clerk.dev, and clerk.dev is looking the best for now.

**Comment by ebg1223** [comment]
@Sn0wye I switched over from auth0. Too many weird dependency issues and legacy stuff. Clerk.dev is definitely new, not perfect, but they are extremely responsive to issues, and are actively contributing to the community to make auth in the react ecosystem as easy as possible. They are sponsoring Auth.js(formerly nextjs), which could end up being a viable alternative when they launch react native support, if you want to host your own.

**Comment by Sn0wye** [comment]
Yep, probably going with clerk.dev, that'll be a lot of work anyways

**Comment by Sn0wye** [comment]
Hey @ebg1223 where should I put the callback url?

**Comment by VidunderGunder** [comment]
You guys might like this:
https://github.com/VidunderGunder/create-xp-app

**Comment by jseitel** [comment]
out of curiosity, has anyone tried setting up passport.js and exposing it through api route(s)? from what I remember of the architecture it /should/ work on both web and mobile

**Comment by perkinsjr** [comment]
Hi there! 

James from Clerk.dev here. We heard through some channels that you were looking for alternatives, so we created a Clerk template. It's open source and uses best practices with Clerk, TRPC, etc. Very easy to extend and use as needed and works the same as the original t3-turbo. 

Things we added:

- Protected routes implemented at Expo
- OAuth for Discord
- User Management in the next.js app
- Context and middleware for TRPC 

Coming soon:

- Sign-in page for Expo (email, password)

You can check it out here: https://github.com/clerkinc/t3-turbo-and-clerk

**Comment by paulclark** [comment]
@perkinsjr thanks for offering a solution! I tried a fresh clone of your repo + a fresh clerk.dev account, copied API keys into `.env` + `_app.tsx`, and enabled Discord in the dashboard, and am getting the following error plus a console warning:

> @acme/expo:dev:  LOG  error signing in Something went wrong during the Sign in OAuth flow. Please ensure that all sign in requirements are met.

Console warning is:

> WARN  Linking requires a build-time setting `scheme` in the project's Expo config (app.config.js or app.json) for production apps, if it's left blank, your app may crash. The scheme does not apply to development in the Expo client but you should add it as soon as you start working with Linking to avoid creating a broken build. Learn more: https://docs.expo.dev/guides/linking/

Screenshots below:

<img width="1507" alt="Screenshot 2022-12-27 at 5 35 49 PM" src="https://user-images.githubusercontent.com/1505422/209743623-d2773db5-fb90-4aba-98a3-efd8b6e99fc1.png">

![simulator_screenshot_A5CD87F7-590E-47A9-99E9-02DE46D2F719](https://user-images.githubusercontent.com/1505422/209743671-0b0bf708-4009-4f9c-850a-3364709c18cc.png)

**Comment by perkinsjr** [comment]
> @perkinsjr thanks for offering a solution! I tried a fresh clone of your repo + a fresh clerk.dev account, copied API keys into `.env` + `_app.tsx`, and enabled Discord in the dashboard, and am getting the following error plus a console warning:
> 
> 
> 
> > @acme/expo:dev:  LOG  error signing in Something went wrong during the Sign in OAuth flow. Please ensure that all sign in requirements are met.
> 
> 
> 
> Console warning is:
> 
> 
> 
> > WARN  Linking requires a build-time setting `scheme` in the project's Expo config (app.config.js or app.json) for production apps, if it's left blank, your app may crash. The scheme does not apply to development in the Expo client but you should add it as soon as you start working with Linking to avoid creating a broken build. Learn more: https://docs.expo.dev/guides/linking/
> 
> 
> 
> Screenshots below:
> 
> 
> 
> <img width="1507" alt="Screenshot 2022-12-27 at 5 35 49 PM" src="https://user-images.githubusercontent.com/1505422/209743623-d2773db5-fb90-4aba-98a3-efd8b6e99fc1.png">
> 
> 
> 
> ![simulator_screenshot_A5CD87F7-590E-47A9-99E9-02DE46D2F719](https://user-images.githubusercontent.com/1505422/209743671-0b0bf708-4009-4f9c-850a-3364709c18cc.png)
> 
> 

Did you try and sign in before Sign up?

This error usually occurs if the user doesn't exist in the database. 

Please open an issue in our repo if this happens when using sign up and I can track down the issue.

**Comment by juliusmarminge** [comment]
Thanks @perkinsjr for making an official integration repository. I'll close this issue now and added a link to your integration in the root readme.
