### ISSUE TITLE
Should I move eslint, typescript etc to the devDependencies?

### ISSUE THREAD

**Issue by MendyLanda** [t3-oss/create-t3-turbo#331]
I don't know what's the best practice, so I didn't create a PR for that.
I'm thinking of moving to devDependencies the follwing:
 - @acme/eslint-config
 - @ianvs/prettier-plugin-sort-imports
 - @types/prettier
 - eslint
 - prettier
 - prettier-plugin-tailwindcss
 - typescript
 
 Even less sure about these:
 - turbo
 - @manypkg/cli
 
 Current state:

<img width="484" alt="image" src="https://user-images.githubusercontent.com/54242706/235321843-ca7f838f-8f00-4ce8-8257-f04a7c07fd9e.png">

**Comment by juliusmarminge** [comment]
Doesnt matter for private packages https://github.com/Thinkmill/manypkg#root-has-devdependencies
