### ISSUE TITLE
Consider running tRPC as it's own service.

### ISSUE THREAD

**Issue by MendyLanda** [t3-oss/create-t3-turbo#335]
Currently the tRPC api is deployed  with next using the app in apps/nextjs

For me, I found running tRPC in its own separated next app is much more intuitive. 

Especially if you have multiple nextjs apps that use the same api, it can be hard to understand why it's implemented in one and not the others.

Both [cal.com](https://github.com/calcom/cal.com) and [Rallly](https://github.com/lukevella/rallly) uses this approach in their monorepo.

I'd be happy to create a PR if you agree this way is better.

**Comment by juliusmarminge** [comment]
That's added complexity for no reason. I get the argument when you have multiple apps but when you don't it doesn't make sense to me.

> Both [cal.com](https://github.com/calcom/cal.com) and [Rallly](https://github.com/lukevella/rallly) uses this approach in their monorepo.

Well that's not true. Cal exposes their api from their web app.
