### ISSUE TITLE
[Expo Web] webpack errors when expo start --web

### ISSUE THREAD

**Issue by nrowley** [t3-oss/create-t3-turbo#34]
Hi

I'm having an issue with expo running the project on web.

steps to reproduce:
1. clone repo
2. cd apps/expo and `npx expo install @expo/webpack-config@^0.17.0` (this is what the expo cli tells us to install for web to work)
3. change expo/package.json dev script to `expo start --web`
4. in monorepo root, `pnpm run dev`

you should see an error like this:

![Screenshot 2022-10-14 at 14 28 33](https://user-images.githubusercontent.com/47508642/195859384-fba677a2-c2bc-4070-a27e-2218602377a3.png)

**Comment by nrowley** [comment]
@byCedric any ideas here?

**Comment by juliusmarminge** [comment]
Same error as #10

Not sure whats going on. Not using ReactNative Web

**Comment by nrowley** [comment]
hmm that's a shame, was interested in trying react native web and seeing whether it was a viable option for a project

**Comment by juliusmarminge** [comment]
Just looking at the error it looks to be ESM related

**Comment by nrowley** [comment]
@juliusmarminge yeah definitely looks like a webpack config error, i'm not familiar with webpack configs at all :(

**Comment by juliusmarminge** [comment]
I'd just stay with using Nextjs for the web and stay as far away from RN Web as possible ;)
