### ISSUE TITLE
feat: Next to web apps Astro example

### ISSUE THREAD

**Issue by pijusz** [t3-oss/create-t3-turbo#340]
### Describe the feature you'd like to request

We currently have apps: "expo" and "nextjs".

I can easily imagine third type of page: static pages, which are nice to create with Astro.
Expo - native app
Nextjs - web app
Astro - static site

With Astro I would love to share some ui components that would be used by NextJS App. And furthermore even multiple astro apps.

### Describe the solution you'd like to see

3rd app -> Astro static pages

**Comment by juliusmarminge** [comment]
Move to #348
