### ISSUE TITLE
feat: capacitor integration

### ISSUE THREAD

**Issue by peplocanto** [t3-oss/create-t3-turbo#343]
### Describe the feature you'd like to request

I think that capacitors is more functional than expo in this kind of starter kit.
In place of expo that require splitted / duplicated code or expo + solito, capacitors could be an easy solution to obtain native mobile apps from an unique codebase.

### Describe the solution you'd like to see

An example of implementation by Simon Grimm [video](https://www.youtube.com/watch?v=xQKtDgJXrlM)

**Comment by juliusmarminge** [comment]
Not the biggest fan of these solutions - partially why I haven't included Solito either...

The 2 apps are very similar now - but as the complexity grows, I think you're much better off building them as separate entities, only reusing certain shared packages (for example API)
