### ISSUE TITLE
feat: cli tool with plugins/templates system

### ISSUE THREAD

**Issue by PiotrekPKP** [t3-oss/create-t3-turbo#348]
### Describe the feature you'd like to request

This project is a perfect starter for apps that require both mobile and web version.

However, I often find myself adding other apps manually (like docs, static site etc.).
I also see that from time to time there appears an issue regarding adding another type of app / package.

### Describe the solution you'd like to see

I think it would be a nice idea to have to kind of tool (maybe another CLI? Maybe merge it to create-t3-app repo?) that would allow people to customize their packages and apps and include specific apps / packages. I would also make the Next app obligatory as it initializes tRPC endpoints for Expo app.

### Suggested templates
- **(app)** **(oligatory)** NextJS web app
- **(app)** Expo mobile app
- **(app)** Docs with Nextra (maybe other starter you'd recommend)
- **(app)** Astro static website
- **(app)** Vanilla NextJS web app
- **(app)** Vanilla Expo mobile app
- **(package)** **(oligatory)** tRPC
- **(package)** **(oligatory)** configs
- **(package)** **(oligatory)** auth
- **(package)** **(oligatory)** db
- **(package)** i18n hooks for both apps?
- **(package)** UI package, maybe we could also have shadcn's UI components version?

### Additional information

I would be down to work on a tool / templates if you'd like to implement this idea. I think it would be kinda cool to just use something like `npx create-t3-turbo@latest --docs --ui` to initialize an app with eg. docs app and ui package for next and docs app :)

**Comment by juliusmarminge** [comment]
Would be cool - there's also chrome extension and electron app we can do.

I made a repo here which was supposed to be a "massive" t3-monorepo with lots of apps, but haven't touched it in a while: https://github.com/juliusmarminge/t3-twin-turbo

Would be cool with a CLI putting everything together 🔥

**Comment by PiotrekPKP** [comment]
> 

Good to know! I think we could use this repo after upgrading a few apps. I think I can scaffold some kind of a cli and re-use those apps from the twin-turbo repo this week :)

**Comment by juliusmarminge** [comment]
If you still want to do this feel free to pick it up, but I'm gonna go ahead and close this as stale and not something I intend to work on personally.

**Comment by PiotrekPKP** [comment]
No problem! I'm sorry I haven't done anything but I had a lot of stuff to do lately. I'll try to implement it when I have some time and motivation :)
