### ISSUE TITLE
bug: Trying to set the trpc context for expo

### ISSUE THREAD

**Issue by thegirlyoucallryan** [t3-oss/create-t3-turbo#367]
### Provide environment information

in Next it uses Session but I do not believe next/auth and expo mix so I am not sure how to set up the context and the docs are still using next, session.  

Is there anyone who can show me sample code or a repo that has used this with next and expo because I am just new to this and not understanding how to connect everything.

### Describe the bug

I do not have access to session when calling from expo (i dont think)  I do have an auth store in redux that has the token, userId etc that maybe I could plug in but I have no idea how or which direction to go.

### Link to reproduction

https://www.prisma.io/docs/guides/other/troubleshooting-orm/help-articles/nextjs-prisma-client-monorepo

### To reproduce

start a mono repo, write your schema,  try to access ctx in your mutation ctx to do things like connect a new mutation to a userId in  your prisma model

**Comment by RishivikramN** [comment]
You need to use the express adapter provided by the tRPC and host the backend separately. I am trying myself to do this still. I will update here once I complete it.

https://trpc.io/docs/server/adapters/express

**Comment by juliusmarminge** [comment]
next-auth doesnt support expo yet. Hopeful we can put something together once they have released v5.

I did some stuff here which sort of works, so the plan is to get some of that merged upstream in v5 https://github.com/t3-oss/create-t3-turbo/pull/133
