### ISSUE TITLE
bug: Some dependencies are incompatible with the installed expo version

### ISSUE THREAD

**Issue by TobiasJacob** [t3-oss/create-t3-turbo#372]
### Provide environment information

tobiasjacob@tobiasjacob-ThinkPad-P15-Gen-2i:~/garden-diary/apps/expo$ npx envinfo --system --binaries

  System:
    OS: Linux 5.19 Ubuntu 22.04.2 LTS 22.04.2 LTS (Jammy Jellyfish)
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz
    Memory: 19.80 GB / 31.08 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 18.16.0 - ~/.local/share/pnpm/node
    npm: 9.5.1 - ~/.local/share/pnpm/npm

### Describe the bug

When running `pnpm run dev` it complains about

`
Some dependencies are incompatible with the installed expo version:
  @shopify/flash-list@1.4.3 - expected version: 1.4.0
  react-native-safe-area-context@4.5.2 - expected version: 4.5.0
  @types/react@18.2.6 - expected version: ~18.0.27
  typescript@5.0.4 - expected version: ^4.9.4
Your project may not work correctly until you install the correct versions of the packages.
Install individual packages by running npx expo install @shopify/flash-list@1.4.0 react-native-safe-area-context@4.5.0 @types/react@~18.0.27 typescript@^4.9.4
`

### Link to reproduction

https://github.com/hackathon-ufrt/garden-diary

### To reproduce

Clone this repo, run `pnpm install`, change `    "dev": "expo start --ios",` to `    "dev": "expo start --android",` in apps/expo/package.json and `pnpm run dev` with android studio setup.

**Comment by TobiasJacob** [comment]
Could probably be fixed by adjusting the versions of the mentioned packages in apps/expo/package.json.

**Comment by juliusmarminge** [comment]
Has this caused any issues for you?

I believe Expo just had really strict peerDeps and only bumps when they have tested themselves. This is kinda stupid imo and I've never run into issues with for example using TS5
