### ISSUE TITLE
bug: Vercel commands in the README file is incorrect

### ISSUE THREAD

**Issue by ushiradineth** [t3-oss/create-t3-turbo#373]
### Provide environment information

  System:
    OS: macOS 13.0
    CPU: (10) arm64 Apple M2 Pro
    Memory: 4.28 GB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.16.0 - ~/.nvm/versions/node/v18.16.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.16.0/bin/yarn
    npm: 9.5.1 - ~/.nvm/versions/node/v18.16.0/bin/npm

### Describe the bug

Not a bug in the repo itself, but the vercel commands in the README file is incorrect, the proper commands are attached below
<img width="900" alt="image" src="https://github.com/t3-oss/create-t3-turbo/assets/70438264/26318634-559b-4dfd-bc87-ba221ef80b93">

### Link to reproduction

-

### To reproduce

-

**Comment by juliusmarminge** [comment]
Nowadays vercel configures this automatically. You should be able to just remove the overrides.

You should know that your build command, while it will work, wont benefit from Turbo - since you're not running the build task with turbo

**Comment by ushiradineth** [comment]
You are right, I failed to notice about turbo, however the deployment fails without the overrides, thats why i made this issue so any other devs can use these overrides to get it working, ill look into it again and update this issue if i find something.

**Comment by juliusmarminge** [comment]
These settings are the ones vercel automatically sets for me these days and they work out of the box: 
<img width="950" alt="CleanShot 2023-05-24 at 20 38 36@2x" src="https://github.com/t3-oss/create-t3-turbo/assets/51714798/cf0996e7-fb80-40e8-9d4d-95e622577d7f">

**Comment by ushiradineth** [comment]
I get this error with those commands
<img width="1255" alt="image" src="https://github.com/t3-oss/create-t3-turbo/assets/70438264/fba25c5e-8fd9-443b-9ab4-df2b408b2ec1">
