### ISSUE TITLE
feat: Split eslint configs

### ISSUE THREAD

**Issue by Geebrox** [t3-oss/create-t3-turbo#378]
### Describe the feature you'd like to request

Currently, the eslint is mostly configured under the `next.js` projects (`packages/config/eslint/index.js`). If I want to add other eslint configs, for example, `nest.js`, `vite`, `react`, or for other (meta) frameworks, I need to create a separate configuration file each time and add the same lines of configs as in the `index.js` by extending `turbo` `prettier` `typescript` and so on.

### Describe the solution you'd like to see

Isn't it better to split the eslint into multiple files and extend the base config (`index.js`)?

```bash
create-t3-turbo/
├─ packages/
│  ├─ config/
│  │  ├─ eslint/
│  │  │  ├─ index.js
│  │  │  ├─ package.json
│  │  │  ├─ next.js
│  │  │  ├─ nest.js
│  │  │  ├─ react.js
│  │  │  ├─ ...
```

### Additional information

Maybe the root eslint config also needs some modification, so the project doesn't only consider using `next.js` under the hood, but is ready to support any other (meta) frameworks.

**Comment by juliusmarminge** [comment]
Yes - I do this in many of my other monorepos but haven't gotten to it here

**Comment by Tobjoern** [comment]
Just to clarify, would each specific project in the 'apps' folder have a separate eslintrc.js file, which simply extends the desired 'base' config for the respective framework?
I.e. one has an app 'nest', which has an eslintrc.js file, which extends from @acme/config/eslint/nest?

**Comment by Geebrox** [comment]
> Just to clarify, would each specific project in the 'apps' folder have a separate eslintrc.js file, which simply extends the desired 'base' config for the respective framework?
> 
> I.e. one has an app 'nest', which has an eslintrc.js file, which extends from @acme/config/eslint/nest?

In my projects, I use the structure you described. And I would be glad to see it in t3-turbo, if there is no better alternative.

**Comment by juliusmarminge** [comment]
I quite like how i have it in acme-corp: https://github.com/juliusmarminge/acme-corp/tree/main/packages/config/eslint

**Comment by Geebrox** [comment]
> I quite like how i have it in acme-corp: https://github.com/juliusmarminge/acme-corp/tree/main/packages/config/eslint

It is a little bit different from what I was expecting, base config is needed to be extended by other configs. All base rules, plugins (that should be shared across all configs, e.g. eslint turbo, prettier, etc.) and other configurations should be defined in the base config file, so when you create a new config you just extend and export your new config with package json. In the app's eslint you extend what you have exported in package json. What do you think?

**Comment by juliusmarminge** [comment]
> It is a little bit different from what I was expecting, base config is needed to be extended by other configs. All base rules, plugins (that should be shared across all configs, e.g. eslint turbo, prettier, etc.) and other configurations should be defined in the base config file, so when you create a new config you just extend and export your new config with package json. In the app's eslint you extend what you have exported in package json. What do you think?

I'm not quite sure what you mean... A package extend what it needs.

See the differences here:

https://github.com/t3-oss/create-t3-turbo/blob/69836a890f3a1d652e0678c97335029dbe29ffa7/apps/expo/package.json#L53-L59

https://github.com/t3-oss/create-t3-turbo/blob/69836a890f3a1d652e0678c97335029dbe29ffa7/apps/nextjs/package.json#L46-L53

https://github.com/t3-oss/create-t3-turbo/blob/69836a890f3a1d652e0678c97335029dbe29ffa7/packages/api/package.json#L26-L31
