### ISSUE TITLE
bug: default eas configuration fails to build

### ISSUE THREAD

**Issue by dnishiyama** [t3-oss/create-t3-turbo#382]
### Provide environment information

System:
    OS: macOS 13.3.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 62.58 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.16.0 - ~/.nvm/versions/node/v18.16.0/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.5.1 - ~/.nvm/versions/node/v18.16.0/bin/npm
    Watchman: 2023.03.27.00 - /opt/homebrew/bin/watchman

### Describe the bug

When deploying a new project with `npx create-turbo@latest -e https://github.com/t3-oss/create-t3-turbo` and then deploying the project on expo with `yarn workspace @acme/expo eas build --platform all --profile prod` the build fails due to node version incompatibility. It looks for >= 18.16.0 from package.json, but eas defaults to 16.18.1

The solution I used was to pin the node version in `eas.json` as follows:
```
 "production": {
      "node":"18.16.0",
      "ios": {
        "resourceClass": "m-medium"
      }
    }
```

### Link to reproduction

https://github.com/t3-oss/create-t3-turbo

### To reproduce

Use template with `npx create-turbo@latest -e https://github.com/t3-oss/create-t3-turbo`
Set up expo project via the expo.dev dashboard 
Set up apps in play stores
Set up app.config.ts with app details
Build apps with `yarn workspace @acme/expo eas build --platform all --profile prod` 
The build fails due to node version incompatibility. It looks for >= 18.16.0 from package.json, but eas defaults to 16.18.1

### Additional information

If this seems like a good resolution, I'll go ahead and create a pull request to update `eas.json`. Interested to hear if this was more of a local issue for me, or if there is a better way to resolve.

**Comment by juliusmarminge** [comment]
Sounds good!

**Comment by dnishiyama** [comment]
Ok great just submitted #403
