### ISSUE TITLE
bug: Type error when upgrading @types/webpack-env to 1.18.1

### ISSUE THREAD

**Issue by nkeil** [t3-oss/create-t3-turbo#398]
### Provide environment information

```
  System:
    OS: macOS 13.3.1
    CPU: (8) arm64 Apple M2
    Memory: 63.36 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.16.0 - ~/.nvm/versions/node/v18.16.0/bin/node
    Yarn: 3.5.1 - ~/.nvm/versions/node/v18.16.0/bin/yarn
    npm: 9.5.1 - ~/.nvm/versions/node/v18.16.0/bin/npm
```

### Describe the bug

When upgrading the @types/webpack-env package from 1.18.0 to 1.18.1, I'm getting a type error in `apps/expo/index.tsx`, here:
![untitled](https://github.com/t3-oss/create-t3-turbo/assets/26151586/b2ec5113-0c78-4b01-bdfa-d36e729282ed)

Here's the error copied over:
```
Type '__WebpackModuleApi.RequireContext' is not assignable to type 'import(".../expo-router/build/types").RequireContext'.
  Types of property 'id' are incompatible.
    Type 'ModuleId' is not assignable to type 'string'.
      Type 'number' is not assignable to type 'string'.ts(2322)
```

At first I thought this was an issue with expo-router, but from what a maintainer told me [here](https://github.com/expo/router/issues/633#issuecomment-1575931782), they do not support Webpack bundling. I'm not sure where the problem lies exactly.

I've reverted to 1.18.0 as a temporary solution.

### To reproduce

Upgrade @types/webpack-env to 1.18.1 in the expo app package.

**Comment by nkeil** [comment]
To add onto this, `expo-router` version 1.6.0 or above also causes an error.

```
Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `GestureHandler`.
```

I've listed this as a bug because the newer versions causing errors were installed by default for me when using Yarn due to the versions being `~`. This also occurs in pnpm in some cases.

**Comment by nkeil** [comment]
Good news, src will be supported officially soon https://github.com/expo/router/pull/629

**Comment by juliusmarminge** [comment]
Fixed in Expo 49 and Expo Router 2
