### ISSUE TITLE
Why pnpm over yarn workspaces

### ISSUE THREAD

**Issue by mikefisher84** [t3-oss/create-t3-turbo#40]
I understand the value of pnpm over yarn in most cases. However in an expo app to me it gets a little more complicated. 

From the [expo monorepo docs](https://docs.expo.dev/guides/monorepos/) their example uses yarn workspaces. In the section about using other tools they list out a few rules. One of which is that all dependencies must live in a `node_modules` directory. pnpm by default doesn't do this. 

> The default settings of tools like [pnpm](https://pnpm.io/) do not follow these rules. You can change that by adding an .npmrc file with node-linker=hoisted ([see docs](https://pnpm.io/npmrc#node-linker)). That config option will change the behavior to match these rules.

I know there's a `node-linker=hoisted` option which is what this boilerplate uses. However unless my understanding is incorrect this would mean there is no symlinking. So in our use case we want to have an `apps/mobile` folder with the expo app and a `ui` package that contains many components that will be consumed by the expo app. I think this would mean for the expo app to pull in changes made in the `ui` package we would need to run `pnpm i` every time we make a change in the `ui` folder. This seems like a seriously degraded developer experience. 

The alternative would be using yarn workspaces without the nohoist flag as mentioned in the expo docs. I believe this would allow us to develop packages in the `ui` folder and automatically consume them in the `app` folder without having to run `pnpm i`

This is the first production grade mobile app monorepo project I've setup so I may be misunderstanding something of course.

**Comment by mikefisher84** [comment]
Hmm after doing a bit of testing it seems that `create-t3-turbo` will have instant updates from the packages folder with pnpm even with the `node-linker=hoisted` flag on. 

Whats odd to me is from the [pnpm docs](https://pnpm.io/npmrc#node-linker) 

> hoisted - a flat node_modules without symlinks is created. Same as the node_modules created by npm or Yarn Classic. Legitimate reasons to use this setting:
Your tooling doesn't work well with symlinks. A React Native project will most probably only work if you use a hoisted node_modules.

I would think without the symlink though we wouldn't get instant updates on packages. How is this working then?

**Comment by juliusmarminge** [comment]
I dont know the technicals of this but the packages arent being built and put into nodemodules, they are transpiled by nextjs directly.

Afaik, internal packages like this doesnt work the same as external where you have to publish to npm and download and all that.

You'll notice you have the same excellent dx with trpc for example, where changes are registered without even saving the file

**Comment by ian** [comment]
Have tried the above suggestions and default install is still very broken. Prisma does not like being in a package.

**Comment by juliusmarminge** [comment]
> Have tried the above suggestions and default install is still very broken. Prisma does not like being in a package.

No problems having prisma in a package.

Repo broke on Theos stream yesterday and i havent reverted. Undo the custom output path from his PR and it works.

**Comment by juliusmarminge** [comment]
Closing for now.

pnpm works fine and repo is restored to work on initial install
