### ISSUE TITLE
bug: pnpm installation error

### ISSUE THREAD

**Issue by suchcodemuchwow** [t3-oss/create-t3-turbo#406]
### Provide environment information

Need to install the following packages:
  envinfo@7.8.1
Ok to proceed? (y) y

  System:
    OS: macOS 13.3.1
    CPU: (8) arm64 Apple M2
    Memory: 3.29 GB / 24.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.16.0 - ~/.nvm/versions/node/v18.16.0/bin/node
    npm: 9.5.1 - ~/.nvm/versions/node/v18.16.0/bin/npm

### Describe the bug

`npx create-turbo@latest -e https://github.com/t3-oss/create-t3-turbo`

and selecting pnpm as package manager gives the following error:

https://app.warp.dev/block/YdGgfNG214mJ65sd7vBV6E

It doesn't fail when I choose npm as package manager

### Link to reproduction

https://app.warp.dev/block/YdGgfNG214mJ65sd7vBV6E

### To reproduce

Run:
1. `npx create-turbo@latest -e https://github.com/t3-oss/create-t3-turbo`
2. Select pnpm as package manager

**Comment by suchcodemuchwow** [comment]
8.4.0

**Comment by juliusmarminge** [comment]
Cannot repro: https://app.warp.dev/block/yrdSOtsAdOM7zSKanLJEnw

**Comment by juliusmarminge** [comment]
I don't have time to debug stuff without proper reproduction repos. Feel free to reopen this one when one is provided.
