### ISSUE TITLE
feat: 

### ISSUE THREAD

**Issue by matart15** [t3-oss/create-t3-turbo#408]
### Describe the feature you'd like to request

`npx create-turbo@latest -e https://github.com/t3-oss/create-t3-turbo`
it asks which package manager to use. options are npm, pnpm, yarn

but it requires pnpm
https://github.com/t3-oss/create-t3-turbo/blob/main/apps/nextjs/package.json#L8-L11

### Describe the solution you'd like to see

- not ask package manager 
OR
- make it not dependent on pnpm

**Comment by juliusmarminge** [comment]
It's not my CLI, so I don't have any say in what prompts they show. But as you said, this repo requires PNPM so you should pick PNPM in the prompt.
