### ISSUE TITLE
bug: Package tasks (<package>#<task>) are not allowed in single-package repositories

### ISSUE THREAD

**Issue by Andrew-Pynch** [t3-oss/create-t3-turbo#411]
### Provide environment information

npx envinfo --system --binaries
Need to install the following packages:
  envinfo@7.10.0
Ok to proceed? (y)

  System:
    OS: macOS 13.3.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 580.48 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.3.1 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.6.7 - /opt/homebrew/bin/npm
    pnpm: 8.6.5 - ~/Library/pnpm/pnpm

### Describe the bug

I created a new repo from the template

I added a .env file to the root of the project and filled it out using the template + my values

I attempted to run pnpm dev from the root of the project

Received

```pnpm dev

> create-t3-turbo@ dev /Users/andrewpynch/Github/river/mono
> turbo dev --parallel

 ERROR  run failed: Package tasks (<package>#<task>) are not allowed in single-package repositories: found //#clean
Turbo error: Package tasks (<package>#<task>) are not allowed in single-package repositories: found //#clean
 ELIFECYCLE  Command failed with exit code 1.
```

### Link to reproduction

https://github.com/get-river/mono

### To reproduce

pnpm dev

### Additional information

I am probably stupid and this is probably a really obvious / simple fix, but just in case I did discover a new weird behaviour I wanted to post it and get some opinions from people who know what they are talking about

**Comment by nkeil** [comment]
If you're using pnpm, you should remove the `package-lock.json`. I got the same error when I forgot to delete `yarn.lock` after switching to pnpm.

**Comment by juliusmarminge** [comment]
Your repro repo is probably private, it returns 404. Re-open with a public reproduction repo

**Comment by Andrew-Pynch** [comment]
@juliusmarminge just wanted to come back to this issue. I tried running the template again, got the same error.

Googled the error, found this thread ( I have 0 recollection of making this issue but I guess I did lol )

Saw your fix, and voila! It worked! 

Just wanted to let you know, I saw this and your fix worked. THANK YOU

**Comment by amansharma703** [comment]
> If you're using pnpm, you should remove the `package-lock.json`. I got the same error when not deleting `yarn.lock` after switching to pnpm.

Working solution, thanks mate

**Comment by Yeranosyan** [comment]
> > If you're using pnpm, you should remove the `package-lock.json`. I got the same error when not deleting `yarn.lock` after switching to pnpm.
> 
> Working solution, thanks mate

hello do you know the solution if use npm ?

**Comment by JianXinHuang** [comment]
I also encountered the same problem, and after troubleshooting, I found that it was caused by the `pnpm-lock.json` file being automatically encrypted by the system

**Comment by JianXinHuang** [comment]
I also encountered the same problem, and after troubleshooting, I found that it was caused by the `pnpm-lock.json` file being automatically encrypted by the system
