### ISSUE TITLE
eslint crashes after adding a bunch of more packages

### ISSUE THREAD

**Issue by zcesur** [t3-oss/create-t3-turbo#414]
Adding 8 dummy packages seems to be enough to trigger an OOM (with default memory settings)

```
@acme/package8:lint: FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
```

* Logs: [**zcesur/eslint-oom-repro / CI / build-lint**](https://github.com/zcesur/eslint-oom-repro/actions/runs/5438477324/jobs/9889733580#step:9:184)
* Repro: [**zcesur/eslint-oom-repro**](https://github.com/zcesur/eslint-oom-repro)
* Relevant issue: typescript-eslint/typescript-eslint#1192

Looks like a limitation of using typescript-eslint in large multi-package monorepos. But since I found a workaround that seems to work well with t3-turbo, I thought I'd share

**Comment by nkeil** [comment]
I fixed this by changing the root package.json file "lint" script to this:
```json
"lint": "NODE_OPTIONS=--max_old_space_size=4096 turbo lint --continue --concurrency 1",
```
The concurrency thing may or may not be necessary for all cases.

**Comment by zcesur** [comment]
Adding more memory does resolve the OOM ofc, but it's still extremely slow and seems to scale poorly with the number of packages you have. Plus you might still run into the same issue as you add more packages.

Here are the numbers with your tweak (without the concurrency part):

```
Elapsed (wall clock) time (h:mm:ss or m:ss): 0:48.72
Maximum resident set size (kbytes): 2359660
```

To contrast, here are the numbers with `parserOptions.project = true` as in #415:

```
Elapsed (wall clock) time (h:mm:ss or m:ss): 0:08.46
Maximum resident set size (kbytes): 417172
```

**Comment by nkeil** [comment]
@zcesur Thanks for the tip, I made the change and it was a huge improvement to our lint CI
