### ISSUE TITLE
Why does db:generate have cache set to false in turbo.json?

### ISSUE THREAD

**Issue by dBianchii** [t3-oss/create-t3-turbo#420]
I'm trying to understand, why do we have 

```json
"db:generate": {
      "inputs": ["prisma/schema.prisma"],
      "cache": false <--- Why is this false?
    },
 ```
 
 I thought the entire idea of turbo was to take advantage of caching, and the prisma object could be cached here, right? Or maybe I am misunderstanding something?

**Comment by dBianchii** [comment]
Aayyy, issue 420 🥇

**Comment by juliusmarminge** [comment]
Cause prisma codegen in nodemodules is weird... theres a bunch of issues linked in here where we tried making it work https://github.com/t3-oss/create-t3-turbo/pull/37

Also see the official turbo docs saying you cant: https://turbo.build/repo/docs/handbook/tools/prisma#7-caching-the-results-of-prisma-generate
