### ISSUE TITLE
bug: Adding middleware throws Error: PrismaClient is unable to be run in the browser.

### ISSUE THREAD

**Issue by ace4port** [t3-oss/create-t3-turbo#434]
### Provide environment information

System:
    OS: Windows 10 10.0.19045
    CPU: (16) x64 AMD Ryzen 7 5800H with Radeon Graphics
    Memory: 6.72 GB / 15.86 GB
  Binaries:
    Node: 18.15.0 - C:\Program Files\nodejs\node.EXE
    npm: 9.6.2 - C:\Program Files\nodejs\npm.CMD
    pnpm: 7.29.3 - C:\Program Files\nodejs\pnpm.CMD

### Describe the bug

Adding a `middleware.ts` file and doing as per auth.js docs throws error Error: PrismaClient is unable to be run in the browser.
`export { auth as default } from 'auth'
`

### Link to reproduction

na

### To reproduce

Create a middleware.ts file inside src and add in

```
export { auth as default } from '@acme/auth'

export const config = {
  matcher: [
    // match all starting with /dashboard
    '/dashboard(.*)',
 ],
}
```

**Comment by juliusmarminge** [comment]
You must split your config up and use JWT's since middleware is running on edge runtime and Prisma cant run on edge: https://auth-docs-git-feat-nextjs-auth-authjs.vercel.app/guides/upgrade-to-v5#edge-compatibility

**Comment by ace4port** [comment]
Thanks, but I can't seem to make it work

```
Credentials({
      name: 'credentials',
      credentials: {},
      type: 'credentials',

      async authorize(credentials) {
         const { email, password } = credentials as { email: string; password: string }
         const user = await prisma.user.findUnique({ where: { email: email } })
         if (!user) throw new Error('No user found')

         const passwordMatch = await bcrypt.compare(password, user.password)
         if (!passwordMatch) throw new Error('Invalid password or email')

         return { id: user.id, name: user.name, email: user.email, role: user.role, image: user.image }
})
```

I have this in providers file. While this used to work well with `next-auth/middleware`, maybe I will need a new wrapper for it?
For now I could extract out in a function
```
const authResponse = await fetch("/users/login", {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
          },
          body: JSON.stringify(credentials),
        })
```

Do you have a better solution? 
(I am aware passwords are not the golden solution, but for what I am developing, it is necessary and critical)

**Comment by juliusmarminge** [comment]
Hmm I'm not sure actually. Either add another db lib that you can use on the edge.

Do you need the credentialsprovider in the config you use for middleware? I mean you dont check the password once the JWT is signed? I've never used that provider so not sure but feels Strange if you need that provider to run middleware?
