### ISSUE TITLE
bug: latest version installation TypeError: Cannot read properties of undefined (reading 'GET')

### ISSUE THREAD

**Issue by avrapaulo** [t3-oss/create-t3-turbo#449]
### Provide environment information

System:
OS: Windows 10 10.0.19045
Binaries:
Node: 18.17.0
yarn: 1.22.5

### Describe the bug

![image](https://github.com/t3-oss/create-t3-turbo/assets/62544061/2b188890-4514-4dd7-b3a6-c8261f86b81c)

### Link to reproduction

https://github.com/avrapaulo/mrt

### To reproduce

Installed the latest version of the application and added Discord keys and started the application.

**Comment by juliusmarminge** [comment]
Repro is private.

I don't have time to debug stuff without proper reproduction repos. Feel free to reopen this one when one is provided.

**Comment by paulm17** [comment]
I don't think a repo is needed.  I'm getting this on a fresh installation.

I've done both the install via git clone and npx create.

```
@acme/nextjs:dev: - event compiled client and server successfully in 2.1s (835 modules)
@acme/nextjs:dev: - error ../packages/auth/index.ts (25:14) @ GET
@acme/nextjs:dev: - error Error [TypeError]: Cannot read properties of undefined (reading 'GET')
@acme/nextjs:dev:     at eval (webpack-internal:///(rsc)/../../packages/auth/index.ts:24:21)
@acme/nextjs:dev:     at (rsc)/../../packages/auth/index.ts (/Users/paul/development/src/github/create-t3-turbo/apps/nextjs/.next/server/app/page.js:4106:1)
@acme/nextjs:dev:     at __webpack_require__ (/Users/paul/development/src/github/create-t3-turbo/apps/nextjs/.next/server/webpack-runtime.js:33:43)
@acme/nextjs:dev:     at eval (webpack-internal:///(rsc)/./src/app/page.tsx:8:68)
@acme/nextjs:dev:     at (rsc)/./src/app/page.tsx (/Users/paul/development/src/github/create-t3-turbo/apps/nextjs/.next/server/app/page.js:1734:1)
@acme/nextjs:dev:     at Function.__webpack_require__ (/Users/paul/development/src/github/create-t3-turbo/apps/nextjs/.next/server/webpack-runtime.js:33:43)
@acme/nextjs:dev:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
@acme/nextjs:dev:     at async collectGenerateParams (/Users/paul/development/src/github/create-t3-turbo/node_modules/next/dist/build/utils.js:826:17) {
@acme/nextjs:dev:   digest: undefined
@acme/nextjs:dev: }
@acme/nextjs:dev:   23 |
@acme/nextjs:dev:   24 | export const {
@acme/nextjs:dev: > 25 |   handlers: { GET, POST },
@acme/nextjs:dev:      |              ^
@acme/nextjs:dev:   26 |   auth,
@acme/nextjs:dev:   27 |   CSRF_experimental,
@acme/nextjs:dev:   28 | } = NextAuth({
@acme/nextjs:dev: - wait compiling /_error (client and server)...
@acme/nextjs:dev: - event compiled client and server successfully in 557 ms (945 modules)
```

**Comment by paulm17** [comment]
I have created a repo.

https://github.com/paulm17/create-t3-turbo

If I hit 

> http://localhost:3000/api/auth/signin

I still get the same error.

I've pretty much hit a wall here.  😓

**Comment by paulm17** [comment]
So I'm a little further.

If I do the following and export only handlers and not destructure the result of NextAuth.  I'm able to export the GET and POST.

```
export const handlers = NextAuth({
  adapter: PrismaAdapter(prisma),
  providers: [
    Github({
      clientId: env.GITHUB_CLIENT_ID,
      clientSecret: env.GITHUB_CLIENT_SECRET,
    }),
  ],
  callbacks: {
    session: async ({ session, user }) => {
      session.user.id = user.id;
      return Promise.resolve(session);
    },
  },
});

export { handlers as GET, handlers as POST };
```

If I hit the 

> http://localhost:3000/api/auth/signin

endpoint then it works.

Problem is that auth and CSRF_experimental are not available.  If I destructure the return, it's all undefined.

@juliusmarminge when you get some time, please can you look into this.  Even with a fresh install and using discord provider.  It is the exact same.

**Comment by juliusmarminge** [comment]
You dont have the same next-auth version as the original repo. Since it's experimental, expect breaking changes if you install a different one. Check out the PR over at next-auth for the latest setup.

**Comment by paulm17** [comment]
Thanks for responding.  I've come into this from not using the trpc or next-auth at all.  So I have been using multiple versions and going through the code base of next-auth.  It's just an oversight that I upped with a previous version.

Which pull request are you referring to as well?  Can you please link it.  There are 4 pages.

**Comment by paulm17** [comment]
The repo I posted was 5 hours ago.  When you looked at (probably just now) is out of date.  

See this.  I have been looking at the other versions as well.

![Alt Text](https://i.imgur.com/Bl3LtaF.png).

Doesn't matter what version I use doesn't work out of the box.

So, the OP says out of the box and I also say out of the box.  And yet, you are blaming a mis-configured repo?

**Comment by juliusmarminge** [comment]
I just ran

```sh
gh repo clone t3-oss/create-t3-turbo t3-turbo-auth-issue
cp ../create-t3-turbo/.env .env # just to get my envs over
p i
p db:generate 
p dev
```

and signed in, works:

<img width="1206" alt="CleanShot 2023-08-08 at 21 12 12@2x" src="https://github.com/t3-oss/create-t3-turbo/assets/51714798/141f85e9-8439-4e16-90ea-72a0d99252f9">

**Comment by paulm17** [comment]
I really appreciate you taking the time to do that.

I duplicated your works and I still came up with the same error.

I have recorded via loom, following the instructions in the readme.  Please let me know if there is anything I am missing.

Put it on 1.5x playback and it should go a lot quicker.

https://www.loom.com/share/1454eff5dcd24be4846833a3af424436

**Comment by juliusmarminge** [comment]
> I duplicated your works and I still came up with the same error.

Ok so I can see you used the CLI, I'm guessing that's why we get different versions installed.

Can you run `pnpm -F auth ls next-auth` in your project?

I get `next-auth 0.0.0-manual.b53ca00b` both when using the CLI as well as when cloning, which works for me.

**Comment by paulm17** [comment]
Thanks for taking a look at the loom.

I get

```
dependencies:
next-auth 0.0.0-pr.7214.998286da
```

**Comment by juliusmarminge** [comment]
Ah so that's the issue.

You can set the version exact (which I'll do as well):

```diff
- "next-auth": "^0.0.0-manual.83c4ebd1",
+ "next-auth": "0.0.0-manual.b53ca00b",
```

**Comment by paulm17** [comment]
I set the version to that and I still get the same error.  

![Image](https://i.imgur.com/3YtUtLs.png)

**Comment by juliusmarminge** [comment]
Remove the caret

**Comment by paulm17** [comment]
Finally!  It works!  😄 

Thank you so much for helping out.  

Also sorry about being snarky earlier.  I've been at this for 2 days and attacking this at very angle and just kept losing!  Not a great place to be in.

But now happy I can move on!  Many thanks!
