### ISSUE TITLE
How do I debug inside api package? (For VSCode)

### ISSUE THREAD

**Issue by dBianchii** [t3-oss/create-t3-turbo#451]
Hi, I often have a few questions about how to do things in this repo, so I just wanted to know, is it okay to ask for help in here? Is there a better/other place I can go to get help from the community? Sorry if here is not the place to ask

I need to understand, how do I place working breakpoints inside the /api folder? It's really important to be able to debug, and after running my main project with F5, it says that debugger is attached, however the breakpoints inside /api package are not bound
How to debug it?

**Comment by dBianchii** [comment]
Here is my launch.json:
(My main project that consumes trpc package is _kdx_)

´´´json
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Next.js",
      "type": "node-terminal",
      "request": "launch",
      "command": "pnpm dev",
      "cwd": "${workspaceFolder}/apps/kdx/",
      "skipFiles": ["<node_internals>/**"]
    }
  ]
}
```

**Comment by dBianchii** [comment]
Hi guys, nevermind. It's working. The breakpoints were just not "bound", but it is always hitting them. Thank you!

**Comment by Dewald928** [comment]
I still have this issue. I am able to debug any other package. But it never goes into the api package, but it does execute
