### ISSUE TITLE
bug: @acme/expo:dev:  WARN  [TRPCClientError: JSON Parse error: Unexpected character: <]

### ISSUE THREAD

**Issue by AvIsBeastMC** [t3-oss/create-t3-turbo#453]
### Provide environment information

 System:
    OS: Windows 10 10.0.19045
    CPU: (16) x64 12th Gen Intel(R) Core(TM) i5-1240P
    Memory: 1.51 GB / 7.68 GB
  Binaries:
    Node: 18.17.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 9.6.7 - C:\Program Files\nodejs\npm.CMD

### Describe the bug

Everything was working alright until my TRPC Queries started failing... "bug: @acme/expo:dev:  WARN  [TRPCClientError: JSON Parse error: Unexpected character: <]"
im getting this error in 

### Link to reproduction

https://github.com/AvIsBeastMC/assetwing

### To reproduce

![image](https://github.com/t3-oss/create-t3-turbo/assets/76915068/6521c9f1-db0f-4488-ac18-f9718270fbb5)
![image](https://github.com/t3-oss/create-t3-turbo/assets/76915068/0ac13c9c-93c9-461f-885a-eecffba05695)
![image](https://github.com/t3-oss/create-t3-turbo/assets/76915068/e8a36cd3-d5cb-4691-bdef-db5c2cfa8ad5)

**Comment by juliusmarminge** [comment]
Repro is private.

I don't have time to debug stuff without proper reproduction repos. Feel free to reopen this one when one is provided.

**Comment by saulflores95** [comment]
@AvIsBeastMC  I was having the same issue.

I am using clerk for authentication and modified my middleware.ts to be as the following

```
import { NextResponse } from "next/server";
import { authMiddleware } from "@clerk/nextjs";

export default authMiddleware({
  publicRoutes: [
    "/",
    "/sign-in",
    "/sign-up",
    "/forgot-password",
    "/api",
    "/api/trpc",
  ],
  afterAuth(auth, req) {
    // handle users who aren't authenticated
    if (!auth.userId && !auth.isPublicRoute) {
      const signInUrl = new URL("/sign-in", req.url);
      return NextResponse.redirect(signInUrl.href);
    }
  },
});

// Stop Middleware running on static files
export const config = {
  matcher: [
    /*
     * Match request paths except for the ones starting with:
     * - _next
     * - static (static files)
     * - favicon.ico (favicon file)
     *
     * This includes images, and requests from TRPC.
     */
    "/(.*?trpc.*?|(?!static|.*\\..*|_next|favicon.ico).*)",
  ],
};

``

**Comment by saulflores95** [comment]
@AvIsBeastMC  I got it to work with authMiddleware by adding `/api/:path/:trpc` it looks as such

```
import { NextResponse } from "next/server";
import { authMiddleware } from "@clerk/nextjs";

export default authMiddleware({
  publicRoutes: [
    "/",
    "/sign-in",
    "/sign-up",
    "/forgot-password",
    "/api/:path/:trpc",
  ],
  afterAuth(auth, req) {
    // handle users who aren't authenticated
    if (!auth.userId && !auth.isPublicRoute) {
      const signInUrl = new URL("/sign-in", req.url);
      return NextResponse.redirect(signInUrl.href);
    }
  },
});

// Stop Middleware running on static files
export const config = {
  matcher: [
    /*
     * Match request paths except for the ones starting with:
     * - _next
     * - static (static files)
     * - favicon.ico (favicon file)
     *
     * This includes images, and requests from TRPC.
     */
    "/(.*?trpc.*?|(?!static|.*\\..*|_next|favicon.ico).*)",
  ],
};

```
