### ISSUE TITLE
bug: Import @acme/db types into the apps/nextjs throws Error: PrismaClient is unable to be run in the browser.

### ISSUE THREAD

**Issue by serudda** [t3-oss/create-t3-turbo#454]
### Provide environment information

  System:
    OS: macOS 13.0
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 66.61 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 8.5.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
    pnpm: 7.27.1 - /usr/local/bin/pnpm

### Describe the bug

Since Prisma generates the types from the model of my database... I would like to reuse those types in my apps/nextjs...

But when I import @acme/db, I get the following error:

`Error: PrismaClient is unable to be run in the browser.`

### Link to reproduction

na

### To reproduce

Import @acme/db en alguna page de tu apps/nextjs

<img width="580" alt="Screenshot 2023-07-28 at 3 23 16 PM" src="https://github.com/t3-oss/create-t3-turbo/assets/10075532/606dc7d5-046f-41a9-a56d-112bc47ababe">

**Comment by juliusmarminge** [comment]
See https://github.com/prisma/prisma/issues/13567#issuecomment-1527700788
