### ISSUE TITLE
bug: pnpm remove doesn't work

### ISSUE THREAD

**Issue by AleshaOleg** [t3-oss/create-t3-turbo#467]
### Provide environment information

System:
    OS: Linux 6.2 Ubuntu 22.04.2 LTS 22.04.2 LTS (Jammy Jellyfish)
    CPU: (16) x64 AMD Ryzen 7 4800H with Radeon Graphics
    Memory: 51.45 GB / 62.22 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 18.17.0 - ~/.nvm/versions/node/v18.17.0/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 9.6.7 - ~/.nvm/versions/node/v18.17.0/bin/npm
    Watchman: 20230129.130010.0 - /usr/local/bin/watchman

### Describe the bug

Initialized turbo, and can't remove packages inside `apps/expo` directory. Made already some commits to the repository, but now decided to get rid of `@shopify/flash-list` package, and can't do it.

```
pnpm remove @shopify/flash-list
../..                                    |  WARN  `node_modules` is present. Lockfile only installation will make it out-of-date
 ERR_PNPM_FETCH_404  GET https://registry.npmjs.org/@acme%2Feslint-config: Not Found - 404

This error happened while installing a direct dependency of /home/aleshaoleg/Documents/Projects/wealth-way/apps/expo

@acme/eslint-config is not in the npm registry, or you have no permission to fetch it.

No authorization header was set for the request.
```

With installation, there was no problem at all and all of the `@acme` packages were installed.

### Link to reproduction

https://github.com/solofeed/wealth-way

### To reproduce

`cd apps/expo && pnpm remove @shopify/flash-list`

**Comment by MendyLanda** [comment]
I'm also experiencing this, I got used to deleting it from package.json and then running  `pnpm i` 🙈

**Comment by juliusmarminge** [comment]
Run with `--filter` or `-F` from root and it should work:

<img width="899" alt="CleanShot 2023-08-08 at 21 16 32@2x" src="https://github.com/t3-oss/create-t3-turbo/assets/51714798/2c84b704-0169-4ba8-aba3-5b3e44b30ad0">

**Comment by danielrotaermel** [comment]
Hi I also ran into this issue. Is there a way we could enable running the "remove" from a workspace? Any idea why this is not working?
