### ISSUE TITLE
Is auth branch ready for use ?

### ISSUE THREAD

**Issue by ayoubphy** [t3-oss/create-t3-turbo#47]
I see that there's an auth branch containing next-auth implementation, can I use that branch ?

**Comment by juliusmarminge** [comment]
As Filip says, doesn't work on Expo. Not sure if I should merge it and have it for Next only for the time being

**Comment by ayoubphy** [comment]
I say merge it and have it for Next only. My question was regarding Next, I had no expectation of it working with expo cause I am not planning on using expo for the time being either.

**Comment by riolly** [comment]
```
../../packages/auth/index.ts
Module parse failed: Unexpected token (4:7)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| export { getServerSession } from "./src/get-session";
| 
> export type { Session } from "next-auth";
|
```
I've got loader error when running dev from the auth branch. Any suggestion?

**Comment by juliusmarminge** [comment]
> ```
> ../../packages/auth/index.ts
> Module parse failed: Unexpected token (4:7)
> You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> | export { getServerSession } from "./src/get-session";
> | 
> > export type { Session } from "next-auth";
> |
> ```
> 
> I've got loader error when running dev from the auth branch. Any suggestion?

Just merged #48. Try again

**Comment by riolly** [comment]
`error - Error: ENOENT: no such file or directory, open '/home/alberto/code/sandbox/turbo/apps/nextjs/.next/server/pages/api/auth/schema.prisma'
`

**Comment by juliusmarminge** [comment]
> ```
> 
> error - Error: ENOENT: no such file or directory, open '/home/alberto/code/sandbox/turbo/apps/nextjs/.next/server/pages/api/auth/schema.prisma'
> 
> ```

I'll check it out later today

**Comment by juliusmarminge** [comment]
> error - Error: ENOENT: no such file or directory, open '/home/alberto/code/sandbox/turbo/apps/nextjs/.next/server/pages/api/auth/schema.prisma'

The required Prisma Models were missing, I've added those and it now works for me:

![CleanShot 2022-10-30 at 12 23 36](https://user-images.githubusercontent.com/51714798/198876284-fc7ec353-cb12-417a-832c-745104c9d03a.png)

**Comment by uze** [comment]
@juliusmarminge Need any help testing this or is this good to merge?

**Comment by juliusmarminge** [comment]
> @juliusmarminge Need any help testing this or is this good to merge?

Sorry been busy. If you want to test it out feel free, I'll try to find time soon so i can merge it if not

**Comment by juliusmarminge** [comment]
Auth's merged
