### ISSUE TITLE
bug: blank screen for IOS on production/preview build

### ISSUE THREAD

**Issue by zephaniahong** [t3-oss/create-t3-turbo#471]
### Provide environment information

System:
    OS: macOS 13.4
    CPU: (8) arm64 Apple M1
    Memory: 76.22 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.15.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.6.7 - /usr/local/bin/npm
    Watchman: 2022.12.12.00 - /opt/homebrew/bin/watchman

### Describe the bug

Local development works perfectly fine but Preview/Production build for expo only shows the T3 screen with no errors whatsoever. Tried using Sentry to hopefully see some errors on production but nothing is shown on Sentry as well. 
<img width="371" alt="Screenshot 2023-08-07 at 4 45 40 PM" src="https://github.com/t3-oss/create-t3-turbo/assets/33389011/e98e4b9e-2354-4bdd-b9da-b52e32ead83e">

### Link to reproduction

-

### To reproduce

Clone repo
`eas build:configure`
`eas build --profile preview --platform ios`

**Comment by juliusmarminge** [comment]
Did you change the url for trpc before building? when you're not in dev you no longer have a `debuggerHost` to use to connect to the trpc backend so you need to use a deployed backend and use that for URl

**Comment by zephaniahong** [comment]
I did change it for my project. But did not change it when trying to replicate the issue on a fresh build.

**Comment by maclaine-san** [comment]
Same here, I get a blank screen for production/preview iOS builds.

**Comment by juliusmarminge** [comment]
Hmm I cannot repro that, although my built app is crashing as soon as i interact with it. Data is fetched fine but no clicking allowed without crashing 👀 

https://github.com/t3-oss/create-t3-turbo/assets/51714798/6a58d5cc-b158-4a53-8e24-6c66d4a15e08

**Comment by zephaniahong** [comment]
I tried this command ```eas build --profile preview --platform ios``` with the latest version of this template and I'm still getting the same issue where all i see is the t3 logo... Any ideas on how I might debug this issue?

**Comment by zephaniahong** [comment]
@juliusmarminge
