### ISSUE TITLE
bug: broken (?) links in README

### ISSUE THREAD

**Issue by ghost** [t3-oss/create-t3-turbo#497]
### Provide environment information

Not relevant

### Describe the bug

Links in README behave in weird way

### Link to reproduction

not needed

### To reproduce

https://github.com/t3-oss/create-t3-turbo/assets/128540204/58bd93d9-d3c7-47a0-a4de-0dd6797b9702

**Comment by BogdanGuyAvrahamCom** [comment]
I'd fix it and make a PR but now I don't know how
