### ISSUE TITLE
Should I use this in the "real world"/production yet?

### ISSUE THREAD

**Issue by Andrewjeska** [t3-oss/create-t3-turbo#51]
Sorry for the big noob question here. I know turbopack is the new kid on the block, but if you're deploying on vercel anyways they ought to support that right? In what scenarios should I ignore turbo? 

This question might be less about this template more so "how do I pick a technology thats good and will grow with me" sort of thing. Sorry if that's the case. 

Thanks in advance. 

Edit: Assuming I set up my own auth

**Comment by AshSimmonds** [comment]
Yep - I've been using it as my primary for 2 projects for nearly 2 months - so my projects are about 250 commits ahead of this. However I didn't use Next Auth and am yet to do much with Expo, I chose this base as a native app was going to be necessary down the line.  
  
However, if you don't need that (suspect you won't) I'd go with the https://github.com/t3-oss/create-t3-app which is a bit less complex to get going as it's not split up as much.

**Comment by Andrewjeska** [comment]
I have it set up with supabase auth and eventually we are going to make a mobile app, so this template would be pretty clutch.
