### ISSUE TITLE
Type annotations file for custom env variables

### ISSUE THREAD

**Issue by petdomaa100** [t3-oss/create-t3-turbo#53]
Hey. I was wondering where is the best place is to place a typescript definition file which extends the `process.env` object to include the custom environmental variables used throughout the project. Maybe have one for each packages or app to only specific the env variables that are used in that submodule/app? dunno

This is how it usually looks like:
```ts
declare namespace NodeJS {
	interface ProcessEnv {
		DATABASE_URL: string;
		VERCEL_URL: string;
		NEXTAUTH_URL: string;
		NEXTAUTH_SECRET: string;
		DISCORD_CLIENT_ID: string;
		DISCORD_CLIENT_SECRET: string;
	}
}
```

What do you guys think? Where's the best place to place this file? Or should I have one per submodule? Thanks.

**Comment by juliusmarminge** [comment]
Keep your env in the apps, so stuff for next in next and expo in expo.

Worth mentioning is that API, Auth and DB are all transpiled in the next app so envs from next will automatically be available in the packages
