### ISSUE TITLE
Environment variable not found: DATABASE_URL

### ISSUE THREAD

**Issue by uze** [t3-oss/create-t3-turbo#54]
When I run `npx prisma studio --schema ./packages/db/prisma/schema.prisma` the prisma studio shows all data in my DB correctly, but when I run `npx turbo run dev` I get:

```Message: Error in Prisma Client request: 


Invalid `prisma.post.count()` invocation:


error: Environment variable not found: DATABASE_URL.
  -->  schema.prisma:7
   | 
 6 |   provider = "postgresql"
 7 |   url      = env("DATABASE_URL")
   | 

Validation Error Count: 1
```

Do we need to add another .env in that folder or some other configuration?

**Comment by juliusmarminge** [comment]
The scripts are run with dotenv that pulls the env from the next app.

Check the scripts in db/package.json

**Comment by juliusmarminge** [comment]
https://github.com/t3-oss/create-t3-turbo/blob/main/packages/db/package.json

**Comment by uze** [comment]
Ah yes this fixed my issue, we can close this issue! Hmm. Should we have one global .env to read from instead of it being inside just the next app?

**Comment by uze** [comment]
Aka changing `"with-env": "dotenv -e ../../apps/nextjs/.env"` to `"with-env": "dotenv -e ../../.env"`

**Comment by juliusmarminge** [comment]
> Ah yes this fixed my issue, we can close this issue! Hmm. Should we have one global .env to read from instead of it being inside just the next app?

No I don't think so, you should have the envs in the apps to mirror how it is when you deploy them in production.

**Comment by uze** [comment]
Hmm got it, I guess the way I was thinking about it is since both apps will share the same database, authentication, etc, then there will be lots of duplicates between the environment variables for each app, thus having one single .env that is the source of truth would be beneficial. Let me know what you think, if you like it I can make the PR otherwise we can keep it as is.

**Comment by uze** [comment]
> Hmm got it, I guess the way I was thinking about it is since both apps will share the same database, authentication, etc, then there will be lots of duplicates between the environment variables for each app, thus having one single .env that is the source of truth would be beneficial. Let me know what you think, if you like it I can make the PR otherwise we can keep it as is.


Hmm got it, I guess the way I was thinking about it is since both apps will share the same database, authentication, etc, then there will be lots of duplicates between the environment variables for each app, thus having one single .env that is the source of truth would be beneficial. Let me know what you think, if you like it I can make the PR otherwise we can keep it as is.

**Comment by uze** [comment]
> > Ah yes this fixed my issue, we can close this issue! Hmm. Should we have one global .env to read from instead of it being inside just the next app?
> 
> No I don't think so, you should have the envs in the apps to mirror how it is when you deploy them in production.

Hmm got it, I guess the way I was thinking about it is since both apps will share the same database, authentication, etc, then there will be lots of duplicates between the environment variables for each app, thus having one single .env that is the source of truth would be beneficial. Let me know what you think, if you like it I can make the PR otherwise we can keep it as is.

**Comment by juliusmarminge** [comment]
Gotcha yea sort of makes sense. If the different apps can pull from root that would work I guess

**Comment by uze** [comment]
@juliusmarminge Opened a PR here: https://github.com/t3-oss/create-t3-turbo/pull/55
