### ISSUE TITLE
base tailwind preset / config for expo and next?

### ISSUE THREAD

**Issue by rndy28** [t3-oss/create-t3-turbo#56]
Hey there, i think the template should use base preset / config because we developing the same thing in web and android / ios. just a suggestion : )

**Comment by juliusmarminge** [comment]
yep feel free to pr a `@acme/tailwind-config` package with a

- index.js - tailwind config
- postcss.js - postcss config

**Comment by rndy28** [comment]
hi @juliusmarminge, i have minor problem here can you help me?. When iam requiring postcss config into nextjs it throws this error:
```
error - ../../node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[3].oneOf[8].use[1]!../../node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[3].oneOf[8].use[2]!./src/styles/globals.css
Error: Cannot find module '@acme/postcss.js'
```
it seems package `@acme/tailwind-config` not include postcss config

**Comment by rndy28** [comment]
here's the package.json

```json
{
  "name": "@acme/tailwind-config",
  "version": "0.1.0",
  "main": "index.js",
  "license": "MIT",
  "devDependencies": {
    "autoprefixer": "^10.4.7",
    "tailwindcss": "^3.1.8",
    "postcss": "^8.4.14"
  }
}
```
