### ISSUE TITLE
bug: nextjs error from a fresh install when running on 'edge'

### ISSUE THREAD

**Issue by kaminskypavel** [t3-oss/create-t3-turbo#562]
### Provide environment information

```
  System:
    OS: Windows 10 10.0.22621
    CPU: (16) x64 Intel(R) Core(TM) i7-10870H CPU @ 2.20GHz
    Memory: 52.66 GB / 63.82 GB
  Binaries:
    Node: 18.17.1 - C:\Program Files\nodejs\node.EXE
    npm: 9.6.7 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.6.12 - ~\AppData\Local\pnpm\pnpm.EXE
```

### Describe the bug

following the installation steps, I immediately got an error out of the box

```
@acme/nextjs:dev: - ready started server on [::]:3000, url: http://localhost:3000
@acme/nextjs:dev: - event compiled client and server successfully in 673 ms (20 modules)
@acme/nextjs:dev: - wait compiling...
@acme/nextjs:dev: - event compiled client and server successfully in 459 ms (20 modules)
@acme/nextjs:dev: - wait compiling /page (client and server)...
@acme/nextjs:dev: - event compiled client and server successfully in 19.4s (1006 modules)
@acme/nextjs:dev: - error Error: Invariant: headers() expects to have requestAsyncStorage, none available.
@acme/nextjs:dev:     at Layout (./src/app/layout.tsx:42:79)
@acme/nextjs:dev:     at stringify (<anonymous>)
@acme/nextjs:dev: - warn
@acme/nextjs:dev: metadata.metadataBase is not set for resolving social open graph or twitter images, using "http://localhost:3000". See https://nextjs.org/docs/app/api-reference/functions/generate-metadata#metadatabase
@acme/nextjs:dev: - error TypeError: Cannot read properties of undefined (reading '')
@acme/nextjs:dev: [TypeError: Cannot read properties of undefined (reading '')]
@acme/nextjs:dev: [TypeError: Cannot read properties of undefined (reading '')]
@acme/nextjs:dev: [TypeError: Cannot read properties of null (reading 'default')]`

```

### Link to reproduction

https://github.com/t3-oss/create-t3-turbo

### To reproduce

1. ` pnpx create-turbo@latest -e https://github.com/t3-oss/create-t3-turbo`
2. removed the expo dir
3. pnpx install
4. pnpx dev

**Comment by kaminskypavel** [comment]
update, 

https://github.com/t3-oss/create-t3-turbo/blob/7623791811af0b25407bb38a72eefd3e37565233/apps/nextjs/src/app/page.tsx#L10 

changing the runtime to nodejs seems to fix the problem.

![image](https://github.com/t3-oss/create-t3-turbo/assets/4253088/64593b62-8223-496a-8cd1-4d7c77b7cfa4)

**Comment by kaminskypavel** [comment]
Actually getting more trpc errors because of "edge" , ended up migrating all functions to nodejs

https://github.com/kaminskypavel/create-t3-turbo/commit/eb111f668f53c0e0a85b40a06a6f2817e52dc60b

**Comment by juliusmarminge** [comment]
The issue is you're using the nodejs mysql package: https://github.com/kaminskypavel/create-t3-turbo/commit/ebcf8e7a03fe88563d1ad6c1a24ea84cf8f4b308

That doesn't work on edge.

**Comment by kaminskypavel** [comment]
Silly me. Thank @juliusmarminge

**Comment by nimeshvaghasiya** [comment]
@juliusmarminge I have created fresh project using 
`pnpx create-turbo@latest -e https://github.com/t3-oss/create-t3-turbo`
then follow [quick start guide](https://github.com/t3-oss/create-t3-turbo#quick-start).

Only change I made is: change database url to use my local mysql instance.
`DATABASE_URL=mysql://root:password@localhost:3306/createt3turbo`

I do have same error as @kaminskypavel when run it using `pnpm run dev`

```
@acme/nextjs:dev: - wait compiling /page (client and server)...
@acme/nextjs:dev: - event compiled client and server successfully in 23.3s (1006 modules)
@acme/nextjs:dev: - error Error: Invariant: headers() expects to have requestAsyncStorage, none available.
@acme/nextjs:dev:     at Layout (./src/app/layout.tsx:42:79)
@acme/nextjs:dev:     at stringify (<anonymous>)
@acme/nextjs:dev: - warn
@acme/nextjs:dev: metadata.metadataBase is not set for resolving social open graph or twitter images, using "http://localhost:3000". See https://nextjs.org/docs/app/api-reference/functions/generate-metadata#metadatabase
@acme/nextjs:dev: - error TypeError: Cannot read properties of undefined (reading '')
``` 

Should I need to use Planetscale db url only? OR is there something to do with "nodejs mysql package" (I didn't change any code line except database url on .env).

**Comment by jamesjohnoliver** [comment]
@kaminskypavel please let me know what you decided to do in the end. Did you use runtime nodejs, or migrate away from node mysql2? I'm getting this same symptom without the mysql2 package directly installed or imported.

**Comment by kaminskypavel** [comment]
> @kaminskypavel please let me know what you decided to do in the end. Did you use runtime nodejs, or migrate away from node mysql2? I'm getting this same symptom without the mysql2 package directly installed or imported.

see my comment above
https://github.com/t3-oss/create-t3-turbo/issues/562#issuecomment-1695348599
