### ISSUE TITLE
bug: unable to use getServerSession inside react server components

### ISSUE THREAD

**Issue by Rahul-Palamarthi** [t3-oss/create-t3-turbo#580]
### Provide environment information

 System:
    OS: Windows 10 10.0.22621
    CPU: (12) x64 AMD Ryzen 5 5600H with Radeon Graphics
    Memory: 597.13 MB / 7.86 GB
  Binaries:
    Node: 18.16.0 - C:\Program Files\nodejs\node.EXE
    npm: 9.6.6 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.6.12 - ~\AppData\Roaming\npm\pnpm.CMD

### Describe the bug

```typescript
import { getServerSession } from 'next-auth';
import { authOptions } from '' // options inside NextAuth(authOptions)

export default function Home() {
	const session = getServerSession(authOptions);
        
        return (<p>hello world</p>)

}
```

### Link to reproduction

nope

### To reproduce

go to the auth and import
```typescript
 import { getServerSession } from 'next-auth';
```

**Comment by juliusmarminge** [comment]
https://github.com/t3-oss/create-t3-turbo/blob/448e94d91578d4928b8ec25b95344669d496fe8c/apps/nextjs/src/app/_components/auth-showcase.tsx#L6
