### ISSUE TITLE
NativeWind `Unhandled JS Exception: undefined is not an object`

### ISSUE THREAD

**Issue by filipweilid** [t3-oss/create-t3-turbo#6]
I am unable to get the Expo app running on either iOS or Android. I have also tried different versions of NativeWind with no success.
<img width="379" alt="image" src="https://user-images.githubusercontent.com/4582583/186680477-d79ba999-ca58-444e-ba87-197265bdb470.png">

**Comment by juliusmarminge** [comment]
Oh doesn't `cjs` work? Sorry, switching back 🥶

**Comment by filipweilid** [comment]
> Oh doesn't `cjs` work? Sorry, switching back 🥶

Looks like Nativewind is specifically looking for a `.js`. I thought I was going crazy when I couldn't get it to work at first 😅

**Comment by juliusmarminge** [comment]
Reverted!
