### ISSUE TITLE
bug: Blank screen for IOS production/preview build

### ISSUE THREAD

**Issue by zephaniahong** [t3-oss/create-t3-turbo#605]
### Provide environment information

System:
OS: macOS 13.4
CPU: (8) arm64 Apple M1
Memory: 76.22 MB / 16.00 GB
Shell: 5.9 - /bin/zsh
Binaries:
Node: 18.15.0 - /usr/local/bin/node
Yarn: 1.22.19 - /opt/homebrew/bin/yarn
npm: 9.6.7 - /usr/local/bin/npm
Watchman: 2022.12.12.00 - /opt/homebrew/bin/watchman

### Describe the bug

Same issue as #471
Still facing the same issues even after using the latest template.
Used a fresh repo.

Any steps I could take to debug this issue? 

### Link to reproduction

-

### To reproduce

-

**Comment by sonipranjal** [comment]
Going through the same issue! Let me know if you have resolved it 🙏

**Comment by zephaniahong** [comment]
@sonipranjal Are you using an m1 mac as well?

**Comment by juliusmarminge** [comment]
I'll try to have a look in the coming days - just got a lot going on right now...

Maybe backtrack what deps renovate has made since i know it was working when i closed the previous issue

**Comment by sonipranjal** [comment]
Sorry for late reply but it worked, I was not returning the  base URL correctly 

```js
const getBaseUrl = () => {
  /**
   * Gets the IP address of your host-machine. If it cannot automatically find it,
   * you'll have to manually set it. NOTE: Port 3000 should work for most but confirm
   * you don't have anything else running on it, or you'd have to change it.
   *
   * **NOTE**: This is only for development. In production, you'll want to set the
   * baseUrl to your production API URL.
   */

  const debuggerHost = Constants.expoConfig?.hostUri;
  const localhost = debuggerHost?.split(":")[0];

  if (!localhost) {
    return "https://clubofcoders.com";
    // throw new Error(
    //   "Failed to get localhost. Please point to your production server.",
    // );
  }
  return `http://${localhost}:3000`;
};

**Comment by sonipranjal** [comment]
I think this issue can be closed!

**Comment by zephaniahong** [comment]
@sonipranjal before you changed the base url, was all you saw a blank screen? I.e. you didn't even have a chance to see any text or click any button?

**Comment by sonipranjal** [comment]
Yes, because we were throwing an error if the URL didn't exists 

```js
// throw new Error(
    //   "Failed to get localhost. Please point to your production server.",
    // );

**Comment by juliusmarminge** [comment]
> I'm not sure if it can be closed. Because if we use a fresh template, you should be able to see the text and buttons just that clicking them would cause an error. But if you don't even see anything then something is wrong.

That's not correct - when not in dev, you need a hosted URL since the debugger won't give you an ip adress you can use. The tRPC fetches things on load so the error will be thrown immediately and not wait until you press a button. I'm just a bit sad that they don't show you what error was thrown in a better way :/

**Comment by juliusmarminge** [comment]
preview build works just fine on my app if you make sure to change the URL:

![CleanShot 2023-09-25 at 20 48 26@2x](https://github.com/t3-oss/create-t3-turbo/assets/51714798/bf021047-f7ea-433a-b392-c6edbb745974)
