### ISSUE TITLE
Would you consider supporting/using Bun?

### ISSUE THREAD

**Issue by 413n** [t3-oss/create-t3-turbo#616]
### Describe the feature you'd like to request

Would you consider supporting/using Bun?
I'm talking mainly for Bun as package manager here, but also for all the other nice features that Bun offers.

### Describe the solution you'd like to see

It's actually more a question than a feature request

**Comment by juliusmarminge** [comment]
#609

**Comment by 413n** [comment]
Ah sorry, I haven't seen that! Thanks
