### ISSUE TITLE
feat: Using lucia instead of next auth

### ISSUE THREAD

**Issue by Bekacru** [t3-oss/create-t3-turbo#618]
### Describe the feature you'd like to request

Lucia has recently published several guides on implementing authentication beyond web, including one for Expo.  Since Lucia also supports Electron, I think using Lucia instead of Next Auth aligns well with the project goals, which aim to demonstrate the use of the T3 stack in a monorepo with multiple apps.

### Describe the solution you'd like to see

Here is a link to the guides
https://preview.lucia-auth.com/guidebook/github-oauth-native/expo/
https://preview.lucia-auth.com/guidebook/github-oauth-native/electron/

### Additional information

I would love to help with implementation if you decide to give it a shot :)

**Comment by zokins** [comment]
+1

Lucia is less opinionated than Next Auth, true it has more setup but with that comes so much more flexibility. Even as a set-up option for those who want that while still retaining Next Auth for people who prefer that as an option I don't see impossible to do.

**Comment by juliusmarminge** [comment]
I wasn't too keen on Lucia when I tried it but if there is a clean implementation maybe? They are using namespaces for module augmentation though which isn't too monorepo friendly - I opened an issue and they might change it to ES module syntax in the next major.

I had an implementation for NextAuth on Expo a while back but paused and waited for v5 and integration in authjs core - but the development over there has been slow so it's taking longer than anticipated...

**Comment by hobo1618** [comment]
Out of curiosity, @juliusmarminge  was there something in particular (other than the namespaces issue) that made you 'not too keen'?

**Comment by juliusmarminge** [comment]
Back then i thought the abstractions were a bit weird and didnt see any added value over using NextAuth, but I've been using it in a project now and it's growing on me.

I think we might have to raise the issue in create-t3-app first though so we dont drift out of "the t3 stack" too much in this repo

**Comment by Bekacru** [comment]
I think next-auth is still the better option for ct3 app. The lucia use case is much more relevant on this repo. But, it has been a while since I last used ct3 app, so if the cli now allows you to choose between providers, then it would make sense to consider it there first.

**Comment by juliusmarminge** [comment]
Got a pretty clean next-auth solution going in #720

**Comment by raphaelm-gioa** [comment]
Looked at the PR, looks amazing ! Thank you so so much ! Will this be authjs retrocompatible?

**Comment by juliusmarminge** [comment]
> Looked at the PR, looks amazing ! Thank you so so much ! Will this be authjs retrocompatible?

This repo is already using authjs :)

**Comment by amkayondo** [comment]
Is there a better step by step next auth implementation for react native and tauri Js

**Comment by swarajbachu** [comment]
but I feel the main problem is with implementing Apple auth with custom flow
