### ISSUE TITLE
Any suggestions to help vscode recognize imports? 

### ISSUE THREAD

**Issue by Andrewjeska** [t3-oss/create-t3-turbo#62]
<img width="716" alt="Screen Shot 2022-11-08 at 10 55 47 AM" src="https://user-images.githubusercontent.com/11382084/200613310-441fe365-ce04-40c1-9a5c-6da478fa9284.png">

**Comment by juliusmarminge** [comment]
???

- where are you importing from?
- what do you expect to happen?

**Comment by Andrewjeska** [comment]
I got it working, sorry for the crappy issue

**Comment by juliusmarminge** [comment]
> I got it working, sorry for the crappy issue

Happy to hear, please provide a bit more context next time so it's easier to understand ☺️
