### ISSUE TITLE
bug:  `Error: Module not found: Can't resolve 'net'` when using postgres

### ISSUE THREAD

**Issue by christo8989** [t3-oss/create-t3-turbo#634]
### Provide environment information

```
  System:
    OS: macOS 13.0
    CPU: (8) arm64 Apple M1
    Memory: 1.07 GB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.18.0 - ~/.nvm/versions/node/v18.18.0/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 9.8.1 - ~/.nvm/versions/node/v18.18.0/bin/npm
    pnpm: 7.27.1 - /opt/homebrew/bin/pnpm
```

### Describe the bug

iOS runs fine. But I get an issue with nextjs.

`Error: Module not found: Can't resolve 'net'`

```
[Import](https://nextjs.org/docs/messages/module-not-found) trace for requested module:
../../node_modules/postgres/src/index.js
../../packages/db/index.ts
../../packages/auth/index.ts
./src/app/_components/auth-showcase.tsx
./src/app/page.tsx
../../node_modules/next/dist/build/webpack/loaders/next-edge-ssr-loader/index.js?absolute500Path=&abs
```

Seems this is related to "use client" when used with postgres?

### Link to reproduction

None

### To reproduce

Replace the db with postgres.
Run `yarn dev`

**Comment by christo8989** [comment]
Related? https://github.com/drizzle-team/drizzle-orm/issues/753

**Comment by juliusmarminge** [comment]
You're trying to use a Nodejs package on edge runtime. Remove the `export const runtime = "edge"` from all pages and api routes and you should be good

**Comment by christo8989** [comment]
Nice. That did it.

There's a note in the README:

> **Note**
> The [db](./packages/db) package is preconfigured to use PlanetScale and is edge-ready with the [database.js](https://github.com/planetscale/database-js) driver. If you're using something else, make the necesary modifications to the [schema](./packages/db/schema) as well as the [client](./packages/db/index.ts) and the [drizzle config](./packages/db/drizzle.config.ts).

A light suggestion to include this potential update?

However, thank you very much. You saved me a ton of time.

**Comment by adarshaacharya** [comment]
@juliusmarminge i've not used `export const runtime = "edge" ` anywhere in my codebase but still getting same error

**Comment by adarshaacharya** [comment]
> maybe middleware?

I haven't used middleware as well.

Just difference is that I've imported drizzle from postgres-js instead of vercel.

```
import { drizzle } from "drizzle-orm/postgres-js";
import postgres from "postgres";
```

**Comment by torchsmith** [comment]
Same error for me @adarshaacharya

**Comment by austinbiggs** [comment]
I'm also receiving this error; you're not alone @adarshaacharya ...
