### ISSUE TITLE
enhancement: extend `localhost`-getter beyond dev lifecycle

### ISSUE THREAD

**Issue by angelprzz** [t3-oss/create-t3-turbo#636]
### Provide environment information

  System:
    OS: macOS 13.5.2
    CPU: (10) arm64 Apple M1 Max
    Memory: 341.61 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.17.1 - ~/.nvm/versions/node/v18.17.1/bin/node
    npm: 9.6.7 - ~/.nvm/versions/node/v18.17.1/bin/npm

### Describe the bug

This is a similar problem @johnslemmer  had a few months ago (https://github.com/t3-oss/create-t3-turbo/pull/300).

Basically, if you build and run your app using `expo run:ios`, the hostUri becomes unaccessible. Manifest & Manifest2 are also null (and deprecated). 

There must be a way to get the localhost address without Expo Go.

### Link to reproduction

https://github.com/t3-oss/create-t3-turbo/pull/300

### To reproduce

1. Create a t3 turbo project and set db & server.
2. Inside the expo folder, run `npx expo run:ios` and wait for the project to build inside the simulator
3. At this moment, `Constants.expoConfig.hostUri` is null and there's no way to access the local host.

### Additional information
Expo 49.0.11

_No response_

**Comment by johnslemmer** [comment]
FYI

I think in expo 49 some more things changed. That line to figure out `debuggerHost` now looks like this in my project.

```js
  const debuggerHost =
    Constants.expoConfig?.hostUri ??
    Constants.manifest2?.extra?.expoGo?.debuggerHost;
```

Hope this helps.

**Comment by angelprzz** [comment]
Thank you @johnslemmer 
Unfortunately the debuggerHost is still undefined when running the app on bare workflow.
I'm using Expo 49.0.11, but I had the same problem on previous versions too.

**Comment by juliusmarminge** [comment]
Open for improvements here - I'm not really in the Expo ecosystem a whole ton so unsure what best practices / all the APIs are...

The current solution was meant to work for dev and then you'd point it to an actual URL when building - but if there is a way to extend the getter to work for other lifecycle scripts I'm open to include those!

**Comment by angelprzz** [comment]
@juliusmarminge Yeah, I'm trying to find a solution too. 
The reason why this is important is because in order to test things like push notifications you need to run the app locally with `npx expo run:ios` on a physical device, so Expo Go wouldn't work in these kind of situations.

**Comment by juliusmarminge** [comment]
You could use ngrok or something

**Comment by angelprzz** [comment]
Hey guys! I was able to solve the issue after installing `the expo-dev-client` package. This package brings some of the capabilities of Expo Go to bare projects, including the ability to access the debuggerHost. 

Here's my pull request. Please let me know if there are any issues:
https://github.com/t3-oss/create-t3-turbo/pull/938
