### ISSUE TITLE
VSCode ESLint severity override 

### ISSUE THREAD

**Issue by miikebar** [t3-oss/create-t3-turbo#638]
Is this override intentional? I found it quite confusing as I usually set the exhaustive-deps rule to error, but I was still getting warning underlines in VSCode. If not, could you consider removing it?

https://github.com/t3-oss/create-t3-turbo/blob/ea6e7fe5ee223fb4be70d9681e72c0381fd5dce5/.vscode/settings.json#L5

**Comment by juliusmarminge** [comment]
It's intentional to keep ts errors and lint errors separate. If you don't like it you can change it on your end
