### ISSUE TITLE
Enable migrations

### ISSUE THREAD

**Issue by SorenHolstHansen** [t3-oss/create-t3-turbo#64]
I tried setting up migrations but with no luck, seems it might be a problem with pnpm.

I wanted to add a `db-migrate-dev` script with a corresponding one in the `db` package. Something like `pnpm with-env prisma migrate dev`. However when I ran it from the repo root, it never prompted me for a migration name, and the command never ended, it just hanged. Even with the `--name <some_name>` parameter it would not finish.

However I managed to make a migration if i `cd` into the db package and ran it from there. I also got it to work with npm in turborepo's own with-prisma example.

I tried some hoisting with no luck either.

I suspect it might be a problem with pnpm, prisma and that it is in a monorepo.

I saw some issues in the prisma repo about some issues with pnpm and node_modules, but was unable to get any wins from it.

Anyone have a solution for this?

**Comment by juliusmarminge** [comment]
Turborepo's terminal output isn't interactive. I've raised an issue on this on their side previously.

For now, I'd recommend `pnpm --filter db db-migrate-dev`
