### ISSUE TITLE
bug: Unable to resolve "expo-router/entry" from "index.tsx"

### ISSUE THREAD

**Issue by saulflores95** [t3-oss/create-t3-turbo#656]
### Provide environment information

  System:
    OS: macOS 12.5.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 601.38 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.18.0 - ~/.nvm/versions/node/v18.18.0/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 9.8.1 - ~/.nvm/versions/node/v18.18.0/bin/npm
    pnpm: 8.8.0 - ~/Library/pnpm/pnpm

###  Unable to resolve "expo-router/entry" from "index.tsx"

1. Start create-t3-turbo
2. pnpm i
3. pnpm db:push
4. pnpm dev

The nextjs project runs as expected
![image](https://github.com/t3-oss/create-t3-turbo/assets/10928178/cfe4b01f-2b01-465f-a0f2-08c5f1e74767)

but the expo app does not run throwing the following error `Unable to resolve "expo-router/entry" from "index.tsx"`

![image](https://github.com/t3-oss/create-t3-turbo/assets/10928178/5b4fdced-7f2b-4686-8feb-26b7aa71c887)
![image](https://github.com/t3-oss/create-t3-turbo/assets/10928178/48bfa62f-b3a8-42ea-8821-c654f8c98117)

If I go into `/apps/expo/index.tsx` I see the following

![image](https://github.com/t3-oss/create-t3-turbo/assets/10928178/d70fdd2b-ded5-42c5-afb9-ba26ed8e92ef)

and if expanded I see the following

![image](https://github.com/t3-oss/create-t3-turbo/assets/10928178/9a0b8e52-2def-42d6-be17-974784b3826d)

I am not sure what is wrong.

### Link to reproduction

*

###  Unable to resolve "expo-router/entry" from "index.tsx"

1. Start create-t3-turbo
2. pnpm i
3. pnpm db:push
4. pnpm dev

### Additional information

I also attempted to run everything with nvm using 18.18.0 and had the same results. Attempting to run in the iPhone 14 simulator with iOS 16.2

I also got an error for @expo/config where the module was not being resolved. I ran `pnpm add @expo/config --filter @acme/expo`

but while it did remove the error on the `app.config.ts`  file this did not solve the issue.

**Comment by saulflores95** [comment]
Not sure if this might be related

![image](https://github.com/t3-oss/create-t3-turbo/assets/10928178/309316bb-b338-4e9f-9bd6-f37d4b986bd7)

**Comment by saulflores95** [comment]
I got it to work, but by no means did it feel right

1. On metro config I modified `config.resolver.disableHierarchicalLookup = true;` to `config.resolver.disableHierarchicalLookup = false;`
2. On root, I added a .npmrc file containing 
`node-linker=hoisted`
3. ran `pnpm clean:workspaces`
4. deleted pnpm-lock.yml
5. ran `pnpm i`

**Comment by juliusmarminge** [comment]
Should hopefully be fixed.

**Comment by kotar0** [comment]
@saulflores95 
Thanks a lot, I fixed by your way.
