### ISSUE TITLE
schema.prisma not found when using React Server Components

### ISSUE THREAD

**Issue by DavideCarvalho** [t3-oss/create-t3-turbo#67]
I started migration a side project of mine to react-t3-turbo

When I try to access a page that fetches data using prisma on a React Server Component, it gives an error of schema.prisma not found

Below is the code

![image](https://user-images.githubusercontent.com/15630886/201490592-b8899a6e-5508-42b6-8f1b-edf1108affc8.png)

and Below here is the error

![image](https://user-images.githubusercontent.com/15630886/201490609-f93255e5-5269-4a67-8d88-6ed41185f3b9.png)

If I copy the schema.prisma to ".nextjs/server/app/product" the error goes away

**Comment by ernestoresende** [comment]
From the Next.js Beta documentation on: https://beta.nextjs.org/docs/api-reference/next.config.js#servercomponentsexternalpackages

> If a dependency is using Node.js specific features, you can choose to opt-out specific dependencies from the Server Components bundling and use native Node.js `require`

So, for this use case, under the experimental property on the `next.config.mjs` file:

```javascript
experimental: {
  // Enables hot-reload and easy integration for local packages
  serverComponentsExternalPackages: ["@prisma/client"],
  transpilePackages: ["@acme/api", "@acme/auth", "@acme/db"],
  appDir: true,
},
```

Tested locally under the latest changes on `main` branch and it seems to work okay.

Altough Server Components enables database querying directly from the component, I don't actively encourage it in detriment of just using the tRPC layer provided by the template, but I don't think the core maintainers will integrate tRPC with Next's `/app` directory until it's out of beta and becomes stable.

**Comment by DavideCarvalho** [comment]
![image](https://user-images.githubusercontent.com/15630886/201737253-ebf59842-68e3-4171-9b35-8fbce58fce20.png)
Changing from using prisma directly to tRPC server side caller looks great. Thanks!
