### ISSUE TITLE
bug: error An unexpected error occurred: "https://registry.yarnpkg.com/@acme%2fprettier-config: Not found".

### ISSUE THREAD

**Issue by swebreza** [t3-oss/create-t3-turbo#674]
### Provide environment information

 System:
    OS: Windows 10 10.0.25967
    CPU: (12) x64 Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
    Memory: 4.24 GB / 15.76 GB
  Binaries:
    Node: 18.18.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 9.7.2 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.7.6 - ~\AppData\Roaming\npm\pnpm.CMD

### Describe the bug

PS C:\Users\mywindow\OneDrive\Desktop\app> pnpm install
Scope: all 10 workspace projects
Lockfile is up to date, resolution step is skipped
Packages: +1481
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 ERR_PNPM_LINKING_FAILED  Error: ENOENT: no such file or directory, scandir 'C:\Users\mywindow\OneDrive\Desktop\app\node_modules\node-plop_tmp_23296\node_modules'
Progress: resolved 0, reused 1341, downloaded 0, added 44

PS  C:\Users\mywindow\OneDrive\Desktop\app> yarn install
yarn install v1.22.19
info No lockfile found.
[1/5] Validating package.json...
[2/5] Resolving packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/@acme%2fprettier-config: Not found".
info If you think this is a bug, please open a bug report with the information provided in "C:\\Users\\mywindow\\OneDrive\\Desktop\\app\\arn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

### Link to reproduction

https://github.com/swebreza/ambulance

### To reproduce

for pnpm
`pnpm i`

for yarn
`yarn install`

**Comment by dBianchii** [comment]
Hi, did you run `pnpm i`/`yarn install` inside a certain package/app? Or was it on the root?

**Comment by swebreza** [comment]
> Hi, did you run `pnpm i`/`yarn install` inside a certain package/app? Or was it on the root?

I did it on the root.
`pnpm i `
 
and got this,

`ERR_PNPM_LINKING_FAILED  Error: EPERM: operation not permitted, rename C:\Users\mywindow\OneDrive\Desktop\app\node_modules\turbo-windows-64_tmp_30124' -> 'C:\Users\mywindow\OneDrive\Desktop\app\node_modules\turbo-windows-64'
Progress: resolved 0, reused 1341, downloaded 0, added 59
PS C:\Users\mywindow\OneDrive\Desktop\app> `

where as yarn install on the root

`yarn install`
yarn install v1.22.19
info No lockfile found.
[1/5] Validating package.json...
[2/5] Resolving packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/@acme%2fprettier-config: Not found".
info If you think this is a bug, please open a bug report with the information provided in C:\\Users\\mywindow\\OneDrive\\Desktop\\app\\yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.


package.json on the root 
`
{
  "name": "create-t3-turbo",
  "private": true,
  "engines": {
    "node": ">=v18.18.0"
  },
  "packageManager": "pnpm@8.7.5",
  "scripts": {
    "build": "turbo build",
    "clean": "git clean -xdf node_modules",
    "clean:workspaces": "turbo clean",
    "db:push": "pnpm -F db push",
    "db:studio": "pnpm -F db studio",
    "dev": "turbo dev --parallel",
    "format": "turbo format --continue -- --cache --cache-location='node_modules/.cache/.prettiercache'",
    "format:fix": "turbo format --continue -- --write --cache --cache-location='node_modules/.cache/.prettiercache'",
    "lint": "turbo lint --continue -- --cache --cache-location 'node_modules/.cache/.eslintcache' && manypkg check",
    "lint:fix": "turbo lint --continue -- --fix --cache --cache-location 'node_modules/.cache/.eslintcache' && manypkg fix",
    "typecheck": "turbo typecheck"
  },
  "dependencies": {
    "@acme/prettier-config": "^0.1.0",
    "@manypkg/cli": "^0.21.0",
    "@turbo/gen": "^1.10.15",
    "prettier": "^3.0.3",
    "turbo": "^1.10.15",
    "typescript": "^5.2.2"
  },
  "prettier": "@acme/prettier-config"
}
`

**Comment by crimson-med** [comment]
From looking at the npm the package doesnt exist anymore. I get the same issue. all the @acme repos apear to be gone this includes:     "@acme/api": "^0.1.0" and many more.

Are they needed?

**Comment by swebreza** [comment]
is there any workaround for this?

**Comment by juliusmarminge** [comment]
i've never seen it, maybe you have an old PNPM version?

**Comment by swebreza** [comment]
> i've never seen it, maybe you have an old PNPM version?

PNPM version 
8.7.6

**Comment by crimson-med** [comment]
If you look at registries like npm those packages just done exist at all

**Comment by juliusmarminge** [comment]
> If you look at registries like npm those packages just done exist at all

Like i said, it's a local package in the monorepo, it's not published to any registry n'or is it meant to be. Your pnpm should resolve it locally though, if it doesnt that's weird...

**Comment by crimson-med** [comment]
In which folder is it? I don't see it in packages

**Comment by juliusmarminge** [comment]
> In which folder is it? I don't see it in packages

https://github.com/t3-oss/create-t3-turbo/blob/main/tooling/prettier/package.json

**Comment by juliusmarminge** [comment]
btw repro works fine for me:

![CleanShot 2023-10-28 at 09 05 29@2x](https://github.com/t3-oss/create-t3-turbo/assets/51714798/da1b2fd7-6ea6-46be-adae-41d1c1906508)

**Comment by dnishiyama** [comment]
Did anyone ever figure this out? I'm running into the same problem
