### ISSUE TITLE
feat: Can I convince this repo to use yarn instead of pnpm?

### ISSUE THREAD

**Issue by christo8989** [t3-oss/create-t3-turbo#675]
### Describe the feature you'd like to request

I think this repo should use yarn instead of pnpm. This is a loose conviction but here's my reasoning.

1. React, React Native, and Yarn are all maintained by Meta. When things go wrong, we can rely on that team to fix them. Also, react native can have weird problems.
2. Aside from that, is it a big deal to use the second-best package manager?
3. Lastly, personal opinion, yarn's user experience is the best.

Hopefully, I've convinced ya'll but if not, no worries. pnpm is awesome.

### Describe the solution you'd like to see

Use yarn instead of pnpm.

**Comment by juliusmarminge** [comment]
Nope. Will move to bun eventually
