### ISSUE TITLE
bug: Unable to resolve "uuid/v5" in PNPM monorepo

### ISSUE THREAD

**Issue by zokins** [t3-oss/create-t3-turbo#676]
### Provide environment information

  System:
    OS: macOS 14.0
    CPU: (12) arm64 Apple M2 Pro
    Memory: 114.39 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.5.1 - ~/.nvm/versions/node/v20.5.1/bin/node
    npm: 9.8.0 - ~/.nvm/versions/node/v20.5.1/bin/npm
    Watchman: 2023.10.09.00 - /opt/homebrew/bin/watchman

### Describe the bug

Whenever I start the dev in expo go i get the following error:
Unable to resolve "uuid/v5" from "../../node_modules/expo/build/environment/getInstallationIdAsync.js"

I've seen some conversation about this issue but it was a long time ago and was apparently fixed so I'm kinda at a lost

### Link to reproduction

https://github.com/t3-oss/create-t3-turbo/pull/165

### To reproduce

In feat pull

**Comment by zokins** [comment]
setting `config.resolver.disableHierarchicalLookup` in the `metro.config.js` fixes things but that's not the recommended way to have things in a monorepo

**Comment by by14** [comment]
Same problem - any fixes besides commenting out config.resolver.disableHierarchicalLookup?

**Comment by juliusmarminge** [comment]
> setting `config.resolver.disableHierarchicalLookup` in the `metro.config.js` fixes things but that's not the recommended way to have things in a monorepo

It is actually the recommended way, but I've had mixed results with it in the past... https://docs.expo.dev/guides/monorepos/#modify-the-metro-config

**Comment by juliusmarminge** [comment]
Hopefully it's resolved for everybody now with Expo 50 introduced in #795
