### ISSUE TITLE
bug: The next-auth package is set to a weird version that is a one off build with vulnerabilities.

### ISSUE THREAD

**Issue by akutruff** [t3-oss/create-t3-turbo#689]
### Provide environment information

n/a

### Describe the bug

Look here: 

https://github.com/t3-oss/create-t3-turbo/blob/f9d88368f1afed5a0c1f218d0adbc0e623b5bb80/packages/auth/package.json#L20C19-L20C40

That version has several vulnerabilities in it. 
https://deps.dev/npm/next-auth/0.0.0-manual.b53ca00b

The next-auth package is set to some non-standard version.  When trying to update to the latest version there are errors.  

### Link to reproduction

https://github.com/t3-oss/create-t3-turbo/blob/f9d88368f1afed5a0c1f218d0adbc0e623b5bb80/packages/auth/package.json#L20C19-L20C40

### To reproduce

look at the file

**Comment by juliusmarminge** [comment]
It's not a vulnerable package as it's a v5 beta that's just using a different versioning system.

They did however just release a "proper beta" marked as `5.0.0-beta` so I'll update to that
