### ISSUE TITLE
Expo tsconfig.json

### ISSUE THREAD

**Issue by digoburigo** [t3-oss/create-t3-turbo#69]
I have a question.
What is `tsconfig.base` in the `extends` property in the `tsconfig.json` on the  `expo app` ?

**Comment by juliusmarminge** [comment]
It's expo's default config, haven't looked into what it enables tbf. It comes when you scaffold with their cli

**Comment by juliusmarminge** [comment]
> Ok, thanks for the information. It's coming from their package in the `node_modules` then? 

Yes

**Comment by digoburigo** [comment]
Oh ok, sorry for opening a issue about this. I should just look at the documentation of expo. Thankf for the info!
