### ISSUE TITLE
TailwindCSS with Radix UI + Headless UI

### ISSUE THREAD

**Issue by digoburigo** [t3-oss/create-t3-turbo#71]
I'm trying to add some UI package in my [fork](https://github.com/digoburigo/create-t3-turbo) of this repo. 

I used this [example](https://github.com/vercel/turbo/tree/main/examples/with-tailwind) from turborepo to create one with TailwindCSS and added [Radix UI](https://www.radix-ui.com/) and [Headless UI](https://headlessui.com/) in it. 
But I'm not getting the expected result, running the fork you will see that the behavior aspect it's not working properly. I tried a number of things to make it work, but with no success.
Someone with more experience or has gone through this can help me with this?

**Comment by juliusmarminge** [comment]
Checked out your repo and found 2 things missing:

1. You are using radix tailwind utility classes, but you haven't installed the plugin:

```js
// tailwind config
...
plugins: [require("tailwindcss-radix")]
```

2. You're not importing the UI's stylesheet in your app:
```ts
// _app.tsx
import "@acme/ui/dist/styles.css";
```

With these two changes, I got the Dialog working:

![CleanShot 2022-11-17 at 00 01 23](https://user-images.githubusercontent.com/51714798/202313472-5820a4b6-3502-4976-8329-c33972275a70.png)

**Comment by digoburigo** [comment]
Oh ok. That was a really dumb move from my part haha. 
Yeah, I got it working now. But for me I just import the `styles.css` directly like this and it worked
```typescript
// _app.tsx
import "@acme/ui/styles.css";
//          
```
I think it's because it's already mapped in the `package.json` of the `ui` package
```json
 "exports": {
    ".": "./dist",
    "./styles.css": "./dist/styles.css"
  },
```
Feel free to close this issue!

**Comment by juliusmarminge** [comment]
> Oh ok. That was a really dumb move from my part haha. 
> 
> Yeah, I got it working now. But for me I just import the `styles.css` directly like this and it worked
> 
> ```typescript
> 
> // _app.tsx
> 
> import "@acme/ui/styles.css";
> 
> //          
> 
> ```
> 
> I think it's because it's already mapped in the `package.json` of the `ui` package
> 
> ```json
> 
>  "exports": {
> 
>     ".": "./dist",
> 
>     "./styles.css": "./dist/styles.css"
> 
>   },
> 
> ```
> 
> Feel free to close this issue!
> 
> 

Cool must've missed that. Glad you got it working
