### ISSUE TITLE
Alternative to using expo on the mobile side

### ISSUE THREAD

**Issue by markdesouza** [t3-oss/create-t3-turbo#72]
Is it possible to have a standard react native app without the expo component? With create-t3-app we have the alternative pathway of deploying not just to vercel but to any number of hosts. I would be nice if create-t3-turbo was able to run a pure react native app to optionally remove the dependancy.

**Comment by mgehrls** [comment]
What alternative's are there? I'm new to native, but expo seemed like the only game in town.

**Comment by juliusmarminge** [comment]
We're not recommending you run react native as is. Expo is the way imo

**Comment by uze** [comment]
I agree with @juliusmarminge here. Expo is far better by every standard.

**Comment by nrcaz** [comment]
@markdesouza what would be your need ? Since expo released configs plugins a few years ago, you can install any native dependencies outside of the expo ecosystem, and in worst case scenario you can create an expo module much easier now.

**Comment by alzalabany** [comment]
imo expo is not for every project, bundle size / baggage can sometimes be a burden or considered bloat.
would be nice to include react-native as an optional

**Comment by juliusmarminge** [comment]
> imo expo is not for every project, bundle size / baggage can sometimes be a burden or considered bloat.
> would be nice to include react-native as an optional

Check out the FAQ where I explained why libs like Solito isn't included either. This repo is not made for mobile apps. It's main purpose is to demonstrate the codesplit - on top of which you can add whatever app you like. I chose Expo as I think that's a common use case but you are free to swap it out for any other app you may need. The process should be similar and the backend part is already in place.

https://github.com/t3-oss/create-t3-turbo#can-you-include-solito
