### ISSUE TITLE
PrismaClient is unable to be run in the browser

### ISSUE THREAD

**Issue by Rykuno** [t3-oss/create-t3-turbo#75]
This issue occurs when attempting to import a type(enum in this case) from the prisma client in `@acme/db` into `@acme/nextjs`

Error
`Error: PrismaClient is unable to be run in the browser.
In case this error is unexpected for you, please report it in https://github.com/prisma/prisma/issues`

To reproduce, simply create an enum in Prisma and import said enum within NextJS. 

`schema.json`
```
enum ExampleEnum {
    One
    Two
}
```

`index.tsx`
```
import { ExampleEnum } from '@acme/db`
```

**Comment by juliusmarminge** [comment]
Pretty sure this isnt related to this setup. Prisma can never run in the browser and when you import from "@prisma/client" you violate that.

**Comment by juliusmarminge** [comment]
Yea i also make a custom generator that outputs the enums to a separate entrypoint.

The rest of the types i infer from trpc

**Comment by juliusmarminge** [comment]
I'll close this for now. If it gets requested again I might add built in support for this but for now, I'll leave this for the developer to implement on their own.

Building a generator which takes all the enums and outputs to a separate entry point isn't very hard, or you can just do as you pointed out and output your types to a separate entry point and use those.

**Comment by jordiup** [comment]
@Rykuno, thanks for sharing your solution to this 😊 Would love to see your custom Prisma plugin if you're happy to share!
