### ISSUE TITLE
bug: unable to use edge runtime in next

### ISSUE THREAD

**Issue by thoo0224** [t3-oss/create-t3-turbo#754]
### Provide environment information

  System:
    OS: Windows 11 10.0.22621
    CPU: (16) x64 AMD Ryzen 7 3700X 8-Core Processor
    Memory: 14.63 GB / 31.92 GB
  Binaries:
    Node: 18.16.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 9.8.1 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.6.11 - ~\AppData\Local\pnpm\pnpm.EXE

### Describe the bug

When I'm trying to use `export const runtime = "edge";` in nextjs I'm getting this error:

```
⨯ Internal error: TypeError: Cannot read properties of undefined (reading '')
    at resolveClientReference (../../node_modules/next/dist/compiled/react-server-dom-webpack/cjs/react-server-dom-webpack-client.edge.development.js:53:55)
    at resolveModule (../../node_modules/next/dist/compiled/react-server-dom-webpack/cjs/react-server-dom-webpack-client.edge.development.js:1588:35)
    at processFullRow (../../node_modules/next/dist/compiled/react-server-dom-webpack/cjs/react-server-dom-webpack-client.edge.development.js:1648:25)
    at processBinaryChunk (../../node_modules/next/dist/compiled/react-server-dom-webpack/cjs/react-server-dom-webpack-client.edge.development.js:1751:21)
    at progress (../../node_modules/next/dist/compiled/react-server-dom-webpack/cjs/react-server-dom-webpack-client.edge.development.js:1819:17)
[TypeError: Cannot read properties of undefined (reading '')]
 ⨯ [TypeError: Cannot read properties of undefined (reading '')]
 ⨯ [TypeError: Cannot read properties of null (reading 'default')]
```
 
 I'm not using any libraries just a blank layout and page, removed auth and database but I'm still getting this error. (Seems to work fine on Vercel but not locally)

### Link to reproduction

https://github.com/t3-oss/create-t3-turbo

### To reproduce

1. `pnpm dlx create-turbo@latest -e https://github.com/t3-oss/create-t3-turbo`
2. Remove database and auth package from nextjs
3. Remove all other components so the layout and page is blank
4. `pnpm i` and `pnpm dev`

**Comment by teddybee** [comment]
Same issue here. I have started today a t3 turbo app with default settings.

**Comment by juliusmarminge** [comment]
Provide a reproduction please, you've just linked the whole repo and then list some things you did, how should I help if i cant check and see if you did something wrong?

**Comment by thoo0224** [comment]
@juliusmarminge You don't have to do the list to reproduce it, I did that just to make sure there are no node packages being used, which is not the case because the project builds fine. You can just clone and run it.

**Comment by teddybee** [comment]
@thoo0224 @juliusmarminge 
I have just cloned the repo and started with "pnpm dev".
The issue is gone when I removed all the const runtime = "edge"; rows in the code.
The OS is Windows 11.

**Comment by juliusmarminge** [comment]
> P.S: If that matters, the db is a self hosted mysql(not Planetscale).

That's it then, I guess you're using the node mysql package, and that is not edge ready. Read https://github.com/t3-oss/create-t3-turbo#quick-start

**Comment by thoo0224** [comment]
create-t3-turbo uses planetscale which does support edge, and there is still an error even if no packages are used.

**Comment by 2-fly-4-ai** [comment]
Just rain into the same issue. Disable edge and it works, but now my drizzle queries obviously not working properly. 

Why does the  `export const runtime = "edge"` cause an internal server error?

I am trying the t3TurboSupaBase Starter template.

**Comment by 2-fly-4-ai** [comment]
Just to add this issue should not be closed. I have just downloaded t3 turbo and got the exact same issue. This starter is supposed to work as is with the supabase setup. The export const runtime = "edge"; is supposed to work. 

The error is a internal server error, removing the edge runtime export allows the app to run, but the trpc queries to drizzle fail. 

Think there is a high chance this is a windows OS issue with this template. Since not many are running into this exact issue.

**Comment by Lukem121** [comment]
I am experiencing the same issue. Currently, I am using the following as a workaround:

`export const runtime = isDev ? "nodejs" : "edge";`

**Comment by nick-solly** [comment]
Also experiencing this issue on Windows. Are we able to get the issue reopened please?
