### ISSUE TITLE
bug: format script breaks on windows

### ISSUE THREAD

**Issue by spenceradolph** [t3-oss/create-t3-turbo#755]
### Provide environment information

  System:
    OS: Windows 10 10.0.19045
    CPU: (12) x64 Intel(R) Core(TM) i7-7800X CPU @ 3.50GHz
    Memory: 22.23 GB / 31.68 GB
  Binaries:
    Node: 21.1.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.2.0 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.10.3 - ~\AppData\Local\pnpm\pnpm.EXE

### Describe the bug

Running the format scripts from the root package.json results in .prettiercache files generating in /'node_modules/.cache/.prettiercache'

It probably shouldn't have the single quotes in it.

Unsure if due to windows, but I am removing the single quotes since there are no spaces in the paths anyways.

### Link to reproduction

https://github.com/t3-oss/create-t3-turbo

### To reproduce

Run format script and see files created with single quotes surrounding the path.

### Additional information

Installed repo using `npx create-turbo@latest -e https://github.com/t3-oss/create-t3-turbo`

Was trying to understand the prettier config and how to adjust it to my liking. I expected saving the config file with new values to automatically 'work' when formatting other files in the monorepo, but I wasn't getting it to work. I tried to re-run `pnpm i`, and restarting VSCode. Then I tried to run the format commands in the root package.json. This created the cache file, but in a weird location.

I have removed the single quotes from the --cache-location path in order to fix it.

**Comment by spenceradolph** [comment]
I have switched to wsl and was unable to reproduce, so perhaps this is exclusively a windows problem.

**Comment by juliusmarminge** [comment]
if removing quotes works for all platforms let's do that!
