### ISSUE TITLE
NEXTAUTH_SECRET doesn't work in production

### ISSUE THREAD

**Issue by justinfriebel** [t3-oss/create-t3-turbo#77]
I tried getting the stack working all the way through but kept getting an error where NextAuth would say I didn't have a secret in production even though I had `NEXTAUTH_SECRET` set in prod for my app.

It seems like I have it working by adding `secret: process.env.NEXTAUTH_SECRET,` in `auth-options.ts`.

It's a small change but I can't seem to create a branch or PR.

**Comment by juliusmarminge** [comment]
The deployed version of this project has working sign in so not sure what you're doing wrong:

https://create-t3-turbo.vercel.app

Did you follow the setup guide in the readme?

**Comment by justinfriebel** [comment]
Yes I did follow all of the instructions besides the expo stuff so I'm not sure why it seems to need this.
