### ISSUE TITLE
Prisma Studio schema path

### ISSUE THREAD

**Issue by justinfriebel** [t3-oss/create-t3-turbo#78]
I tried getting Prisma Studio working, but it seemed like it couldn't find the DATABASE_URL. Since the `schema.prisma` file is not in the expected location, it seems to cause issues.

I was able to connect by adding the below to the `package.json`:

```
  "prisma": {
    "schema": "packages/db/prisma/schema.prisma"
  }
```

I'm also wondering if the `db-generate` and `db-push` inputs for `turbo.json` need to be updated?

**Comment by juliusmarminge** [comment]
The prisma studio launches when you run pnpm dev from root, or just pnpm --filter db dev.

If you look at the db package.json, those scripts are run with a dotenv wrapper so that we don't need a separate env file in the db package.
