### ISSUE TITLE
bug: tailwind not hot reloading in dev

### ISSUE THREAD

**Issue by soya-miruku** [t3-oss/create-t3-turbo#79]
First of all, great work guys! this is amazing, really loving it so far.
I am not sure if this is a known issue or more on my side, but yeah as the title suggests, when i make changes to my tailwind config file i would like to have these changes hot reloaded, is this possible? 
i wasn't sure if i needed to make changes to the package.json file or just include it as a transpile package.

thanks!

**Comment by juliusmarminge** [comment]
Is this working in a normal Next.js app?

**Comment by soya-miruku** [comment]
@juliusmarminge yes, i was previously using the normal t3 stack repo, but now i need to create another app, so thought to use t3-turbo

**Comment by jeevanpillay** [comment]
I have an implementation of this already. I'll come back here tomorrow to add some comments on how I achieved it and we can discuss whether its worth a PR.

**Comment by juliusmarminge** [comment]
> I have an implementation of this already. I'll see if I have time in the next couple days to add some comments on how I achieved it and we can discuss whether its worth a PR :)

Hey, mind sharing your solution?

**Comment by teddybee** [comment]
As far as I know it is a nextjs 13.x bug.
[https://github.com/vercel/next.js/issues/43878](https://github.com/vercel/next.js/issues/43878)

**Comment by LukaHietala** [comment]
> As far as I know it is a nextjs 13.x bug. [vercel/next.js#43878](https://github.com/vercel/next.js/issues/43878)

I also had this issue with next 13, but it was only when I was using the `app` directory

**Comment by BrightonMboya** [comment]
@soya-miruku Is it still an issue? Just tried to change the tailwind config and worked well on my end.
