### ISSUE TITLE
bug: TRPCClientError when pointing at local Mysql 8.1.0 

### ISSUE THREAD

**Issue by Handfish** [t3-oss/create-t3-turbo#798]
### Provide environment information

```
  System:
    OS: macOS 12.7.1
    CPU: (8) x64 Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz
    Memory: 56.05 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 21.2.0 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
    pnpm: 8.9.2 - ~/Library/pnpm/pnpm
```

### Describe the bug

After cloning the repo and configuring the `.env` to use a local database Mysql 8.1.0
```
>>> tRPC Request from rsc by undefined
 << query  #1 post.all  {
  input: undefined,
  result:  [TRPCClientError: fetch failed] {
  meta: undefined,
  shape: undefined,
  data: undefined,
  name: 'TRPCClientError'
},
  elapsedMs: 116
}
 ⨯ TRPCClientError: fetch failed
    at eval (./src/trpc/server.ts:59:98)
Cause:  [TRPCError: fetch failed] {
  code: 'INTERNAL_SERVER_ERROR',
  name: 'TRPCError'
}
 ⨯ TRPCClientError: fetch failed
    at eval (./src/trpc/server.ts:59:98)
digest: "3067733176"
```

I would like to locally develop as I don't always have internet connection. I am having trouble getting a working solution.

### Link to reproduction

N/A

### To reproduce

1. Clone the repo.
2. Point the env at a local copy of MySQL 
```
DB_HOST=localhost
DB_NAME='test'
DB_USERNAME=test 
DB_PASSWORD=password
```
3. seed via `pnpm db:push`
4. `pnpm dev` at the root
5. Navigate to the nextjs app

### Additional information

![image](https://github.com/t3-oss/create-t3-turbo/assets/7737624/a280870d-5a91-479f-9757-c4d16bc05be3)

**Comment by Handfish** [comment]
Nevermind I see the [blurb about edge-bound](https://github.com/t3-oss/create-t3-turbo?tab=readme-ov-file#quick-start). Sorry!

**Comment by juliusmarminge** [comment]
You can use https://github.com/mattrobenolt/ps-http-sim as a development layer to run planetscale http api connected to a local mysql database.

I've been using this for a project now lately and will probably add to this repo soon

**Comment by Handfish** [comment]
@juliusmarminge 

Thank you for going out of your way to share this on the closed issue. Much appreciated!

**Comment by Handfish** [comment]
@juliusmarminge 
Awesome tip on `ps-http-sim`. I have t3-turbo working locally for myself now. Cheers.
