### ISSUE TITLE
Old client support

### ISSUE THREAD

**Issue by smartinio** [t3-oss/create-t3-turbo#81]
Hi,

I'm curious about the combination of tRPC and native apps. What is the recommended strategy for making sure previous client releases don't break when making changes to tRPC procedures?

It would be nice to be able to catch in dev or CI that a tRPC change "breaks" the type contract of an earlier release, maybe through some kind of contract snapshot generation that could be stored in the repo.

Apologies in advance if this already exists or somehow isn't necessary.

**Comment by juliusmarminge** [comment]
If uii oh I just modify a procedure you should be able to send out an instant update with Expo code push and not have to worry about old clients

https://blog.expo.dev/eas-update-is-now-generally-available-6532d25e750

**Comment by smartinio** [comment]
Interesting. Thanks!
