### ISSUE TITLE
bug: IDE Complaining about a missing compiler option

### ISSUE THREAD

**Issue by FleetAdmiralJakob** [t3-oss/create-t3-turbo#827]
### Provide environment information

  System:
    OS: Windows 11 10.0.22631
    CPU: (12) x64 AMD Ryzen 5 5600X 6-Core Processor
    Memory: 11.10 GB / 31.93 GB
  Binaries:
    Node: 20.9.0 - D:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 10.2.3 - D:\Program Files\nodejs\npm.CMD
    pnpm: 8.14.0 - ~\AppData\Local\pnpm\pnpm.EXE

### Describe the bug

My IDE is complaining about a missing typescript compiler option inside of the UI package

![image](https://github.com/t3-oss/create-t3-turbo/assets/77451351/cbfda6fc-85e5-433f-a8df-138ecb87bd70)

### Link to reproduction

https://github.com/t3-oss/create-t3-turbo

### To reproduce

Go inside IntelliJ (don't know about other IDEs) into the button.tsx of the UI package

**Comment by noxify** [comment]
tested it quickly with my current VSC setup and i can't reproduce it

**Comment by FleetAdmiralJakob** [comment]
Actually somehow the error got away, now. Idk why, but now he is gone
