### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by FleetAdmiralJakob** [t3-oss/create-t3-turbo#833]
Maybe this question would fit better in a GH Discussion, but:

Why has this repo not next/core-web-vitals in his ESLint config, but the basic T3 has.

![image](https://github.com/t3-oss/create-t3-turbo/assets/77451351/ebbc76a6-da8f-4106-b97c-e35b325e0001)

**Comment by juliusmarminge** [comment]
Probably should. The reason it's using the plugin instead of config is that we apply the react rules and basic tslint in the other presets, so the next preset in t3-turbo only needs to care about nextjs stuff.

PR accepted to change to core-web-vitals from the plugin though1
