### ISSUE TITLE
bug: Downloading the template and running prebuild leads to an error

### ISSUE THREAD

**Issue by HonestCodeWasTaken** [t3-oss/create-t3-turbo#838]
### Provide environment information

  System:
    OS: macOS 13.2
    CPU: (8) arm64 Apple M1 Pro
    Memory: 41.41 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.7.0 - ~/.nvm/versions/node/v18.7.0/bin/node
    npm: 8.15.0 - ~/.nvm/versions/node/v18.7.0/bin/npm
    pnpm: 7.25.1 - ~/Library/pnpm/pnpm
    

### Describe the bug

⚠️  Something went wrong running `pod install` in the `ios` directory.
Command `pod install` failed.
└─ Cause: CocoaPods could not find compatible versions for pod "React-FabricImage":
  In Podfile:
    React-FabricImage (from `../../../node_modules/react-native/ReactCommon`)

Specs satisfying the `React-FabricImage (from `../../../node_modules/react-native/ReactCommon`)` dependency were found, but they required a higher minimum deployment target.

### Link to reproduction

https://github.com/HonestCodeWasTaken/test-t3-auth

### To reproduce

pnpm installed the packages, then went into expo folder and ran:

npx expo prebuild --clean

**Comment by dominikwozniak** [comment]
@HonestCodeWasTaken Hey, the same problem occurs for me. Did you manage to fix it? Any update?

**Comment by HonestCodeWasTaken** [comment]
> @HonestCodeWasTaken Hey, the same problem occurs for me. Did you manage to fix it? Any update?

I used an older version of t3 turbo instead. Here's my current package.json:

`json
{
  "scripts": {
    "with-env": "dotenv -e ../../.env --",
    "start": "expo start",
    "android": "expo run:android",
    "ios": "expo run:ios",
    "web": "expo start --web",
    "eject": "expo eject",
    "test": "jest --watchAll",
    "dev2": "npm run with-env expo start --ios --clear",
    "dev": "expo run:ios --device"
  },
  "jest": {
    "preset": "jest-expo"
  },
  "dependencies": {
    "@acme/api": "*",
    "@acme/tailwind-config": "*",
    "@expo/vector-icons": "^13.0.0",
    "@react-native-async-storage/async-storage": "1.18.2",
    "@react-native-community/netinfo": "9.3.10",
    "@react-native-google-signin/google-signin": "9.0.2",
    "@react-navigation/bottom-tabs": "^6.5.7",
    "@react-navigation/native": "^6.1.6",
    "@react-navigation/stack": "^6.3.16",
    "@shopify/flash-list": "1.4.3",
    "@shopify/mime-types": "^2.1.0",
    "babel-preset-expo": "^9.5.2",
    "expo": "~49.0.7",
    "expo-application": "~5.3.0",
    "expo-asset": "~8.10.1",
    "expo-av": "~13.4.1",
    "expo-blur": "~12.4.1",
    "expo-constants": "~14.4.2",
    "expo-file-system": "~15.4.5",
    "expo-font": "~11.4.0",
    "expo-image-picker": "~14.3.2",
    "expo-linear-gradient": "~12.3.0",
    "expo-linking": "~5.0.2",
    "expo-notifications": "~0.20.1",
    "expo-splash-screen": "~0.20.5",
    "expo-status-bar": "~1.6.0",
    "expo-web-browser": "~12.3.2",
    "lodash": "^4.17.21",
    "nativewind": "^2.0.11",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-intl": "^6.5.5",
    "react-native": "0.72.6",
    "react-native-calendars": "^1.1303.0",
    "react-native-dropdown-picker": "^5.4.6",
    "react-native-gesture-handler": "~2.12.0",
    "react-native-get-random-values": "~1.9.0",
    "react-native-keyboard-aware-scroll-view": "~0.9.5",
    "react-native-safe-area-context": "4.6.3",
    "react-native-screens": "~3.22.0",
    "react-native-typography": "1.4.1",
    "react-query": "^3.39.3",
    "typescript": "^5.3.3"
  },
  "resolutions": {
    "expo": "48.0.20"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@babel/plugin-proposal-export-namespace-from": "^7.18.9",
    "@babel/preset-env": "^7.19.3",
    "@babel/runtime": "^7.19.0",
    "@expo/config-plugins": "~7.2.2",
    "@types/react": "~18.2.14",
    "@types/react-native-vector-icons": "^6.4.13",
    "eslint": "^8.30.0",
    "postcss": "8.4.23",
    "react-native-codegen": "^0.70.7",
    "tailwindcss": "3.3.2",
    "typescript": "^5.1.3"
  }
}
`

**Comment by HonestCodeWasTaken** [comment]
![image](https://github.com/t3-oss/create-t3-turbo/assets/59506416/ded954b9-4800-45c4-85ff-5c53c5fbd74d)

managed to launch the expo app:
https://github.com/HonestCodeWasTaken/test-t3-auth

Might have been that I only needed to install new macOS update, since before that it didn't work. With new update, I also updated my xCode to 15.2

**Comment by dominikwozniak** [comment]
@HonestCodeWasTaken I was able to do a prebuild on your app (xcode 15.1). I will try to compare packages on my app.

**Comment by dominikwozniak** [comment]
Using `expo-doctor` helps me to install SDK 49.0.0 compatible native modules.

If it helps anyone, it was necessary to downgrade `react-native` to `0.72.6`. I don't think this is an ideal solution, but at this point I see no other option.
