### ISSUE TITLE
Incorrect main in package.json of auth 

### ISSUE THREAD

**Issue by RhysSullivan** [t3-oss/create-t3-turbo#84]
Currently the auth package has this as it's main / types:

`
  "main": "./src/index.ts",
  "types": "./src/index.ts",
`

The index.ts file however isn't in the src/ folder, it's in the root folder of the auth package.

This caused an issue for me when referencing this repository for my project however. Moving index.ts inside the src folder fixed this problem for me.

**Comment by juliusmarminge** [comment]
Feel free to PR a fix 🙏

**Comment by dominikvrbic** [comment]
I opened a pr for it https://github.com/t3-oss/create-t3-turbo/pull/86 (had the same problem)
