### ISSUE TITLE
How to use client-side session

### ISSUE THREAD

**Issue by shayant98** [t3-oss/create-t3-turbo#842]
Currently in the repo i only see an implementation for using auth() which can only be used on server side components.

How would I go about using the session hook "useSession" while keeping type inference. When i try to use just the import from next-auth I lose my custom user object. Same thing happens when i export useSession from the index.ts.

I would love to see how one would go about implementing this in a monorepo

**Comment by juliusmarminge** [comment]
It looks like the `SessionContextValue` returned from `useSession` is using the type from `@auth/core/types`, and not from `next-auth`. This means our module augmentation of `next-auth` wont have any effect on the useSession hook.

To fix this, you need to augment `@auth/core/types` too :/

```diff
  declare module "next-auth" {
    interface Session {
      user: {
        id: string;
      } & DefaultSession["user"];
    }
  }

+ declare module "@auth/core/types" {
+   interface Session {
+     user: {
+       id: string;
+     } & DefaultSession["user"];
+   }
+ }
```

I wonder if we could get next-auth to change so the useSession hook uses the type from next-auth instead.

### Screenshot

![CleanShot 2024-01-16 at 09 46 35](https://github.com/t3-oss/create-t3-turbo/assets/51714798/75a915a7-9844-41a5-89d3-d228738194cc)

**Comment by juliusmarminge** [comment]
Although testing it out again it does work when just augmenting next-auth for me?

![CleanShot 2024-01-16 at 09 50 19](https://github.com/t3-oss/create-t3-turbo/assets/51714798/0e27aaf0-9e46-4915-924c-b409d4b83339)

**Comment by shayant98** [comment]
Hmm.. you make a good point about moving session handling to the RSC. But i'll check to to maybe modify the type for now while i work on a migration plan to move my ui components to use server session.

Thank you

**Comment by dBianchii** [comment]
@shayant98 I did exactly that myself, making all session calls come from the RSC.

https://github.com/dBianchii/kodix-turbo/pull/40

This does mean you need to drill the session deep into your client components always, but is better than needing to fetch from client side after initial load.

**Comment by juliusmarminge** [comment]
If you have a deep tree of CCs you could mount a SessionProvider and pass the initialSession prop from the RSC session and then use useSession below. This will avoid drilling the prop too deep whilst not having the useSession data flicker, but for just one or two layers i dont think it’s an issue to pass as prop

**Comment by dBianchii** [comment]
> If you have a deep tree of CCs you could mount a SessionProvider and pass the initialSession prop from the RSC session and then use useSession below. This will avoid drilling the prop too deep whilst not having the useSession data flicker, but for just one or two layers i dont think it’s an issue to pass as prop

Do you mean a local session provider for a part of the tree or a global in layout.tsx?

**Comment by juliusmarminge** [comment]
No a ”local” one if you have a part of the tree that’s deep in CCs - I wouldnt await the session at the top layout

maybe there’s a better way to have a global one without awaiting but as i said i havent had the issue where I’ve drillen the session deep enough where i felt it was necessary
