### ISSUE TITLE
bug: https://turbo.t3.gg/ down after latest commits

### ISSUE THREAD

**Issue by srizvi** [t3-oss/create-t3-turbo#845]
### Provide environment information

I'm on a Mac, tried in Chrome, Firefox, and Safari.

Howdy! Just a heads up, I happened to be integrating the awesome Create T3 Turbo into my project so I noticed. After the last two commits to the main branch, the https://turbo.t3.gg/ site has an **Application error: a server-side exception has occurred**.

### Describe the bug

`Application error: a server-side exception has occurred (see the server logs for more information).
Digest: 2005531772`

`Error: An error occurred in the Server Components render. The specific message is omitted in production builds to avoid leaking sensitive details. A digest property is included on this error instance which may provide additional details about the nature of the error. window.console.error @ 568-81c095348dda3b0e.js:1`

### Link to reproduction

https://turbo.t3.gg/

### To reproduce

**Current behavior:**
- Go to https://turbo.t3.gg/
- Application crashes on load as per the above

**Expected behavior:**
- Go to https://turbo.t3.gg/
- Application rocks, like it usually does 

### Additional information

Thanks for your contributions to the OSS community and making the rest of us look so bad!

**Comment by juliusmarminge** [comment]
Closed in https://github.com/t3-oss/create-t3-turbo/commit/cea783769692a5d5911a372209aef74dedccf4a3
