### ISSUE TITLE
feat: Disallow pnpm workspaces hoisted node_modules packages to be used by all other 'child' sub @acme packages

### ISSUE THREAD

**Issue by dBianchii** [t3-oss/create-t3-turbo#849]
### Describe the feature you'd like to request

I came across this problem multiple times, where... if you have a dependency inside `@acme/packageA` and then you have a `@acme/packageB` which depends on `@acme/packageA`, then immediatelly all `@acme/packageA` dependencies are allowed to be used and imported by `@acme/packageB`. This makes the project slightly harder to understand, and also breaks some dependecy principles.

I believe this is being caused by pnpm workspaces, where it will hoist all node_modules to the top, and somehow allow for this to happen.

In my opinion, if I install 'dayjs' inside `@acme/api` for example, then it shouldn't be accsessible in `@acme/nextjs` until I explicitly install it for this package

### Describe the solution you'd like to see

Some kind of configuration to disallow this behaviour

### Additional information

You can see an example of this in my forked project, where I have momentjs being imported in a nextjs application, that has no momentjs explicitly depended upon.
https://github.com/dBianchii/kodix-turbo/blob/main/apps/kdx/src/app/_components/apps/calendar/create-event-dialog.tsx#L6
https://github.com/dBianchii/kodix-turbo/blob/main/apps/kdx/package.json#L16

**Comment by juliusmarminge** [comment]
Upgrading to expo 50 will allow us to remove the node_linker hoisted so this will be solved by that.

I believe someone started the upgrade but then closed the PR, unsure if they intend to finish it
