### ISSUE TITLE
creating UI folder for sharing UI components in Package folder leads to error , how we can achieve that

### ISSUE THREAD

**Issue by sleman-safiah** [t3-oss/create-t3-turbo#85]

**Comment by sleman-safiah** [comment]
it is private code , i am sorry for that , but it is running on next 12.1.4 not next 13 , if that does not related to the problem can you share the repo

**Comment by juliusmarminge** [comment]
> it is private code , i am sorry for that , but it is running on next 12.1.4 not next 13 , if that does not related to the problem can you share the repo

mine's private too - but there was an issue a while back with a public repo: https://github.com/t3-oss/create-t3-turbo/issues/71

**Comment by juliusmarminge** [comment]
Did you get this working?
