### ISSUE TITLE
bug: EAS build not working with hoisting

### ISSUE THREAD

**Issue by EuanMorgan** [t3-oss/create-t3-turbo#867]
### Provide environment information

  System:
    OS: macOS 14.2.1
    CPU: (8) arm64 Apple M2
    Memory: 179.27 MB / 24.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.11.0 - /usr/local/bin/node
    Yarn: 1.22.21 - ~/Library/pnpm/yarn
    npm: 10.2.4 - /usr/local/bin/npm
    pnpm: 8.15.0 - /usr/local/bin/pnpm
    Watchman: 2023.12.04.00 - /opt/homebrew/bin/watchman

### Describe the bug

After the recent Expo 50 upgrade, running EAS build no longer works.

This is the error message:
`Cannot find 'expo-modules-autolinking' package in your project, make sure that you have 'expo' package installed`

I think it's because of the removal of .npmrc and the hoisting changes,
if I re-add `node-linker=hoisted` it works.

### Link to reproduction

https://github.com/EuanMorgan/expo-50-test

### To reproduce

Try to run an EAS build:
`pnpm i`
`cd apps/expo`
`eas build -p ios`

**Comment by juliusmarminge** [comment]
Hoisting should work in Expo 50.

cc @VaniaPopovic mind having a look?

**Comment by akashdevcc** [comment]
Why this issue only happens with `eas build -p ios` and not with `eas build -p android`?
