### ISSUE TITLE
Drizzle that bad ?

### ISSUE THREAD

**Issue by romain-sen** [t3-oss/create-t3-turbo#874]
We are starting a new project (mobile app) and we want to try this stack with create-t3-turbo.

We had planned to use Supabase with Prisma, but with this stack it's Drizzle. Why not if in the end it's the same functionalities and performance, but I'm not reassured by the product when on their official site, the comments are negative... 
Is it just a joke, a bad advertising or is Drizzle really that bad?

<img width="1280" alt="image" src="https://github.com/t3-oss/create-t3-turbo/assets/58177664/0c8bf721-4406-4d64-b37f-68e632ecf595">

**Comment by dBianchii** [comment]
I will say I laughed out lout reading this. Maybe we should make a collection of such comments
It's just drizzle marketing, as you said. It's not bad marketing, it's just genius IMO. You can also see how their twitter looks: https://twitter.com/DrizzleORM

Drizzle is awesome and you can totally use it!
If you want you can checkout my example of how to setuo create-t3-trubo with prisma
https://github.com/dBianchii/kodix-turbo

**Comment by romain-sen** [comment]
> I will say I laughed out lout reading this. Maybe we should make a collection of such comments It's just drizzle marketing, as you said. It's not bad marketing, it's just genius IMO. You can also see how their twitter looks: https://twitter.com/DrizzleORM

I laughed too, but then I remembered I had to present this stack to my client and I wanted to be sure it was all marketing. Thanks !

> Drizzle is awesome and you can totally use it! If you want you can checkout my example of how to setuo create-t3-trubo with prisma https://github.com/dBianchii/kodix-turbo

I'll be sure to take a look at it too!

**Comment by psycho-baller** [comment]
Fell into the same trap few months ago and actually [made an issue in drizzle](https://github.com/drizzle-team/drizzle-orm-docs/issues/177)

Anyways I've been loving my drizzle experience so far. I even convinced my team in IBM to move from Prisma to Drizzle

**Comment by dBianchii** [comment]
> Fell into the same trap few months ago and actually [made an issue in drizzle](https://github.com/drizzle-team/drizzle-orm-docs/issues/177)
> 
> 
> 
> Anyways I've been loving my drizzle experience so far. I even convinced my team in IBM to move from Prisma to Drizzle

It's starting to dawn on me I might need to change to drizzle as well. What made you switch?

**Comment by noxify** [comment]
> What made you switch? 

I'm too lazy to port the turbo repo back to prisma and change everything 🙈

Currently I do not use it in production at work, but the time will come.
