### ISSUE TITLE
bug: "Error: This action with HTTP GET is not supported."

### ISSUE THREAD

**Issue by trevorpfiz** [t3-oss/create-t3-turbo#878]
### Provide environment information

System:
    OS: Linux 5.15 Ubuntu 20.04.6 LTS (Focal Fossa)
    CPU: (16) x64 AMD Ryzen 7 3700X 8-Core Processor
    Memory: 6.34 GB / 9.72 GB
    Container: Yes
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 20.11.0 - ~/.nvm/versions/node/v20.11.0/bin/node
    npm: 10.2.4 - ~/.nvm/versions/node/v20.11.0/bin/npm
    pnpm: 9.0.0-alpha.1 - ~/.local/share/pnpm/pnpm
    bun: 1.0.14 - ~/.local/share/pnpm/bun
    Watchman: 2024.01.22.00 - /home/linuxbrew/.linuxbrew/bin/watchman

### Describe the bug

when I visit `http://localhost:3000/api/auth/providers` right after I clone the repo I get the error `"Error: This action with HTTP GET is not supported."`. curious if this is just on my end or not.

### Link to reproduction

https://github.com/t3-oss/create-t3-turbo

### To reproduce

clone this repo. visit `http://localhost:3000/api/auth/providers`. see error `"Error: This action with HTTP GET is not supported."`.

**Comment by juliusmarminge** [comment]
should be fixed in beta.9 of next-auht

**Comment by ThusharaX** [comment]
> seems like it is still giving an error if I set `AUTH_URL='http://localhost:3000'`. if I don't set an `AUTH_URL` or use `AUTH_URL='http://localhost:3000/api/auth'` it works.

@trevorpfiz thanks 🔥🚀
