### ISSUE TITLE
Issue with next-auth while signIn (Generic Error page)

### ISSUE THREAD

**Issue by kuroski** [t3-oss/create-t3-turbo#88]
Heello, first of all, thanks for all work in this repo 😄 

I started a blank project and encountered this issue while trying to auth

https://user-images.githubusercontent.com/1855125/206151080-c80f1295-857b-4547-899f-59d6109ecdbc.mov

I don't know why exactly that happened, and no errors were being logged (even with next-auth `debug` mode on).

After exploring it a bit, I managed to solve it by changing the `[...nextauth].ts` API route and just spread the `authOption` variable

```typescript
import NextAuth from "next-auth";
import { authOptions } from "@acme/auth";

export default NextAuth({
  ...authOptions,
});
```
https://user-images.githubusercontent.com/1855125/206151125-3bea27d7-abfa-477e-9d19-c4e05f77d224.mov

I don't know if someone else faced the same issue, if that is the case I can create a PR with the change 😅 

---

- Node: v18.12.1
- pnpm: 7.18.0
- Brave: 1.45.133

**Comment by juliusmarminge** [comment]
Might be the same bug as https://github.com/t3-oss/create-t3-app/pull/932

Can pin the nextauth to 4.17

**Comment by balazsorban44** [comment]
https://github.com/t3-oss/create-t3-app/pull/932#issuecomment-1341907346 should be fixed in `next-auth@latest`! Let me know.
