### ISSUE TITLE
Add shared UI package

### ISSUE THREAD

**Issue by JMRBDev** [t3-oss/create-t3-turbo#9]
Hi, I am trying to add a new package for using shared components amongst all the packages available in the app, but whenever I try to import the ui package from NextJS or Expo I get <ins>**ts(2307)**</ins> error (<ins>**Cannot find module**<ins/>).

Of course I am more than aware of me not knowing much about Turborepo as it's the first time I get to play with it 😥.

However, in short I would like to make a shared package to use the same React Native components in both the NextJS app (using React Native Web) and in React Native.

The steps I am currently following to do this are:
- Clone [create-t3-turbo](https://github.com/t3-oss/create-t3-turbo)
- `cd packages && mkdir ui`
  - `npm init -y`
  - Add `"react": "^18.2.0"`, `"react-native": "^0.69.5"` to package.json
  - Change project name to "@acme/ui" in package.json to comply with the rest of the packages and apps naming convention
  - Create a `src/index.tsx` file and export a React component (neither React or React-Native are working)
  - Create `tsconfig.json` file and add:
```json
{
  "extends": "../../tsconfig.json",
  "include": ["src"]
}
```
- `cd ../../apps/nextjs`
  - Add `"@acme/ui": "*"` to package.json
  - Add `"@acme/ui"` to next.config.mjs inside `withTM`'s array attribute so it now looks like this:
```ts
export default withTM(["@acme/api", "@acme/db", "@acme/ui"])(
  defineNextConfig({
    reactStrictMode: true,
    swcMinify: true,
  })
);
```
- `cd ../.. && npm i` (root folder)

Now every `@acme/ui` components should be visible from the NextJS app but when I import them as: `import {Button} from "@acme/ui"` I get that "*Cannot find module*" TypeScript error.

Thanks so much for your help.

**Comment by juliusmarminge** [comment]
It looks like the import path would be incorrect. If you want to do `import { Button } from "@acme/ui";` you would need to create `index.ts` in `@acme/ui` root and barrel it out:
```ts
// packages/ui/index.ts
export { Button } from "src/button";
```
or change the import path to `import { Button } from "@acme/ui/src/button";`.

**Comment by JMRBDev** [comment]
Holy crap mate, I'm completely useless... That's right 😅, I wasn't exporting it correctly so creating a `index.ts` file in the root folder of @acme/ui was enough.

Thank you so much, this was just me being dumb about how monorepos work 🤡😂.

**Comment by juliusmarminge** [comment]
> Holy crap mate, I'm completely useless... That's right 😅, I wasn't exporting it correctly so creating a `index.ts` file in the root folder of @acme/ui was enough.
> 
> 
> 
> Thank you so much, this was just me being dumb about how monorepos work 🤡😂.

No worries!
