### ISSUE TITLE
[README] "just run pnpm dev and scan the QR-code" - fails because package.json dev specifies iOS

### ISSUE THREAD

**Issue by bcjordan** [t3-oss/create-t3-turbo#90]
Love this template!!

One small issue with the getting started guide - `README` notes:

> Note: If you want to use a physical phone with Expo Go, just run pnpm dev and scan the QR-code.

`apps/expo/package.json` contains:

```
"scripts": {
    "start": "expo start",
    "dev": "expo start --ios",
    "clean": "rm -rf .expo .turbo node_modules",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "lint": "eslint . --ext ts,tsx"
  },
```

Running `pnpm dev` tries to launch iOS, which on non-iOS platforms prompts for Xcode install

Possible solutions: 
- Change readme
- Change apps/expo/package.json to not default to --ios

Thoughts on approach if I were to make the edit?

**Comment by juliusmarminge** [comment]
Delete the note. It doesn't work without it due to turbo's terminal not being interactive
