### ISSUE TITLE
feat: Discussion tab

### ISSUE THREAD

**Issue by foodornt** [t3-oss/create-t3-turbo#900]
### Describe the feature you'd like to request

The **Discussion** tab on github

### Describe the solution you'd like to see

A community where we can share our experiences with markup issues and how we resolved them, making it easier for future developers

**Comment by dBianchii** [comment]
This ^

Or maybe just a different issue format is fine. I just sometimes want to discuss things here but find there's no easy way to do it

**Comment by juliusmarminge** [comment]
It's open now
