### ISSUE TITLE
bug: nativewind styles are not being applied

### ISSUE THREAD

**Issue by ghry5** [t3-oss/create-t3-turbo#910]
### Provide environment information

  System:
    OS: macOS 14.2.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 986.19 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.11.1 - ~/.local/share/rtx/installs/node/20.11/bin/node
    npm: 10.2.4 - ~/.local/share/rtx/installs/node/20.11/bin/npm
    pnpm: 8.10.5 - ~/Library/pnpm/pnpm
    Watchman: 2023.12.04.00 - /opt/homebrew/bin/watchman

### Describe the bug

Nativewind styling is not being applied. 

### Link to reproduction

https://github.com/t3-oss/create-t3-turbo/commit/262bacf7169866fdcd3fab80fe6729a4420ef611

### To reproduce

- git clone https://github.com/t3-oss/create-t3-turbo.git
- cd create-t3-turbo && pnpm i
- pnpm -F expo dev
- hit i for ios or a for android

### Additional information

A quick manual search through the most recent commits revealed the breaking commit as https://github.com/t3-oss/create-t3-turbo/commit/262bacf7169866fdcd3fab80fe6729a4420ef611
Further investigation on the last working commit: https://github.com/t3-oss/create-t3-turbo/commit/4dc3a406569cfd7af59ee470e1064cd1d9a0d965 showed that updating nativewind from ~4.0.23 -> ~4.0.36 seems to be the cause.

![Screenshot 2024-03-01 at 16 20 48](https://github.com/t3-oss/create-t3-turbo/assets/32223782/705dd88c-9857-4739-8aa4-c9d3537dd37d)

**Comment by ghry5** [comment]
Looks like a issue was posted on nativewind repo regarding this at nearly the exact same time as this one.
https://github.com/marklawlor/nativewind/issues/836

**Comment by jisunglim** [comment]
The version 4.0.22 works. (See https://github.com/t3-oss/create-t3-turbo/pull/795)

Try this.

```
pnpm update nativewind@4.0.22 --filter expo
```

**Comment by zxcvbnmmohd** [comment]
Reverting nativewind back to `"nativewind": "4.0.1",` seemed to fix it for me.

**Comment by adriangonzy** [comment]
I think I found a fix. 
Upgrade the "react-native-css-interop": "~0.0.34" in the apps/expo/package.json file and things should work correctly. Struggle for a few hours before I found the fix. 
Hope this helps !

**Comment by benrbowers** [comment]
@adriangonzy That doesn't seem to work on android (emulator, ubuntu). Reverting to 4.0.1 seems to be the only fix for me.

**Comment by adriangonzy** [comment]
I tested on expo go and I made sure to clear metro cache.

**Comment by msagerup** [comment]
I get a diffent error, 

warn - No utility classes were detected in your source files. If this is unexpected, double-check the `content` option in your Tailwind CSS configuration.

and no styles are being applied.

this is my tailwind config 

import type { Config } from "tailwindcss";
// @ts-expect-error - no types
import nativewind from "nativewind/preset";

import baseConfig from "@acme/tailwind-config/native";

export default {
  content: ["./src/**/*.{ts,tsx}"],
  presets: [baseConfig, nativewind],
} satisfies Config;


Do I need to add something here or change something?

**Comment by adriangonzy** [comment]
I have no warnings on my side. 
Here is my tailwind.config.ts in `apps/expo`
```
import type { Config } from "tailwindcss";
// @ts-expect-error - no types
import nativewind from "nativewind/preset";

import baseConfig from "@acme/tailwind-config/native";

export default {
  content: ["./src/**/*.{js,ts,jsx,tsx}"],
  presets: [baseConfig, nativewind],
  theme: {
    extend: {},
  },
  plugins: [],
} satisfies Config;

```

**Comment by adriangonzy** [comment]
> @adriangonzy That doesn't seem to work on android (emulator, ubuntu). Reverting to 4.0.1 seems to be the only fix for me.

I tested on android emulator + macos (sonoma 14.4 Apple M1) and it works for me.

**Comment by benrbowers** [comment]
> > @adriangonzy That doesn't seem to work on android (emulator, ubuntu). Reverting to 4.0.1 seems to be the only fix for me.
> 
> I tested on android emulator + macos (sonoma 14.4 Apple M1) and it works for me.

Ah, that's actually great to know. Can I ask what your node version is?

**Comment by adriangonzy** [comment]
Its `v20.11.1`

**Comment by benrbowers** [comment]
Doesn't seem to want to work for me on mac/ios either, I'm not really sure what's going on. Running the tailwind CLI manually works as expected, it just doesn't want to work during the build process. The issue likely lies in my metro.config.js and the path to my config but so far nothing seems to work.

**Comment by benrbowers** [comment]
Ok, working version for me seems to be `4.0.14`

Literally the bare minimum version for because this is the version `gap-x` starts working.

And lo and behold, there seems to be a commit that deals with the tailwind cli between 14 and 15. I tried passing 'npx tailwindcss' and 'yarn tailwindcss' to the `cliCommand` option in the metro.config, but nothing seems to work for version 4.0.15 and onward.

**Comment by brandonfancher** [comment]
> I think I found a fix. Upgrade `"react-native-css-interop"` to `"~0.0.34"` while using `"nativewind":"4.0.36"` in the apps/expo/package.json file and things should work correctly. Struggled for a few hours before I found the fix. Hope this helps !

This worked for me.

**Comment by juliusmarminge** [comment]
A recent dependency bump seems to have fixed this for me atleast:

![CleanShot 2024-03-24 at 15 16 41](https://github.com/t3-oss/create-t3-turbo/assets/51714798/a77fb164-7258-464c-9ebe-6dd55320da4a)

**Comment by benrbowers** [comment]
Got 4.0.36 working! The problem was yarn. I got away with using yarn v1 for far too long, but this seems to be the straw that broke the camel's back. Upgrading to yarn v4 seems have fixed everything. nativewind@4.0.36 now working on my intel mac with the iOS simulator, as well as on Ubuntu with android simulator. 

Upgraded yarn like this:
```
> npx npkill
> yarn set version berry
> yarn install
```

**Comment by Flammae** [comment]
I had the same problem after upgrading to v4 of Nativewind. In my case I had forgotten to add the CSS import in my root `_layout.tsx` file:

```js
import "../styles.css"
```

This file initializes tailwind styles, but I absolutely ignored it because I thought it did not have any effect on IOS and Android builds.

Contents of the CSS file in case you've deleted it:
https://github.com/t3-oss/create-t3-turbo/blob/main/apps/expo/src/styles.css
