### ISSUE TITLE
chore: change default DB provider to one with a free plan

### ISSUE THREAD

**Issue by matteobad** [t3-oss/create-t3-turbo#915]
### Describe the feature you'd like to request

Planetscale is removing the hobby tier. Since this is a public template should a change in the DB provider be made?

### Describe the solution you'd like to see

A possible solution could be Neon, Postgres and offers a branching model similar to PS

### Additional information

I would be willing to create a PR if a change is required

**Comment by dBianchii** [comment]
Create t3 app has a create-database.sh

Maybe we could use that?
If we want to support specific database drivers then we would be forced to have to use a init tool for the user to specify what they want in the repo, which isn't ideal

**Comment by juliusmarminge** [comment]
Could write a codemod - I still think planetscale is the best recommendation one can make, although not ideal for hobbyists ofc

**Comment by matteobad** [comment]
I agree with @juliusmarminge we he says that PScale is still one of the best recommendations, unfortunately, I think most of the people using this starting point probably don't want to pay to have a DB.

Codemod is a good idea, clean, simple, and easy to document. Are we sure that PScale should still be the default and not vice-versa though?

**Comment by dBianchii** [comment]
I think we shouldn't make the default something that has to be paid. I tried today integrating a local MySQL with the current code but it was failing. I then tried to do the same connection but with PScale and it worked perfectly. I think it's best for the default to be something that works with any provider, and if wanted, have options to use other serverless drivers.

**Comment by theclaymethod** [comment]
I agree, picking something paid as a starting point. How about integrating in the work from the Supabase fork?

**Comment by juliusmarminge** [comment]
I think the best solution going forward is to switch to Supabase as the default DB provider, with a codemod to revert back to PlanetScale for folks "who have users™️" and can justfiy paying for Scaler Pro plan. Anyone up for making a PR?

**Comment by VaniaPopovic** [comment]
Can pick up this tomorrow in the afternoon!

**Comment by DivMode** [comment]
Im testing xata atm, they have a very generous free tier with 15gb of data.  It seems like they use AWS Aurora Postgress under the hood.

**Comment by Kotyarishka** [comment]
Hi! No sure if it's the right place for this question, but seems reasonable to post it here.

Is there any alternatives to planescale that support edge enviroments? To be clear, I'm not asking for a ready sollution, just for alternatives that I can look into.

**Comment by juliusmarminge** [comment]
Supabase or Neon 

Inspo: https://github.com/juliusmarminge/t3-supaedge

**Comment by w7tf** [comment]
> Hi! No sure if it's the right place for this question, but seems reasonable to post it here.
> 
> Is there any alternatives to planescale that support edge enviroments? To be clear, I'm not asking for a ready sollution, just for alternatives that I can look into.

Turso is another one. SQLite though.

**Comment by TheBeeL** [comment]
An Edge DB option could be interesting, seeing the typescript support it has and are now offer a free hosting plan.

But would also be best to use their libraries instead of drizzle.
