### ISSUE TITLE
question: Shouldn't we use react/cache with auth() function? 

### ISSUE THREAD

**Issue by dBianchii** [t3-oss/create-t3-turbo#916]
### Describe the feature you'd like to request

It seems like calling auth() in multiple components causes multiple requests to the database. This doesn't seem correct.
Shouldn't we export the following snipeed inside nextjs somewhere?

```ts
import { cache } from "react";

import { auth as acmeAuth } from "@acme/auth";

export const auth = cache(async () => await acmeAuth());
```

And then we can use it in multiple RSCs with no problem

### Describe the solution you'd like to see

-

### Additional information

-

**Comment by juliusmarminge** [comment]
Yes - not sure why there isnt already xd. Feel free to PR

**Comment by dBianchii** [comment]
https://github.com/t3-oss/create-t3-turbo/pull/919

**Comment by dBianchii** [comment]
Resolved by https://github.com/t3-oss/create-t3-turbo/pull/919
