### ISSUE TITLE
bug: Error Launching with iOS simulator

### ISSUE THREAD

**Issue by SeeRich** [t3-oss/create-t3-turbo#921]
### Provide environment information

  System:
    OS: macOS 14.4
    CPU: (10) arm64 Apple M1 Max
    Memory: 328.48 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.11.1 - ~/.nvm/versions/node/v20.11.1/bin/node
    npm: 10.4.0 - ~/.nvm/versions/node/v20.11.1/bin/npm
    pnpm: 8.15.3 - ~/.nvm/versions/node/v20.11.1/bin/pnpm
    bun: 1.0.31 - /opt/homebrew/bin/bun
    Watchman: 2024.01.22.00 - /opt/homebrew/bin/watchman

### Describe the bug

I receive the following when running `npx expo start`
 
iOS Bundling failed 15ms (node_modules/expo/AppEntry.js)
Unable to resolve "../../App" from "node_modules/expo/AppEntry.js"

### Link to reproduction

https://github.com/t3-oss/create-t3-turbo

### To reproduce

1. Clone the repo
2. Fill in some fake environment variables
3. Open macOS iphone simulator
4. Run `npx expo start`

### Additional information

I am using iPhone 15 Pro Max (iOS 17.4) simulator

**Comment by juliusmarminge** [comment]
what prompted you to running `npx expo start` from the monorepo root in the first place?

you either need to run the script with a workspace filter or just run the entire monorepo using `pnpm dev` in root. This is already listed in readme:

![CleanShot 2024-03-24 at 15 26 40](https://github.com/t3-oss/create-t3-turbo/assets/51714798/6c3d7082-c9ef-4786-8bb3-a1d1c091fd3a)

**Comment by juliusmarminge** [comment]
Oh my bad then. Feel free to PR a wording fix for that!
