### ISSUE TITLE
Slow Typescript VSCode Intellisense

### ISSUE THREAD

**Issue by andrewdoro** [t3-oss/create-t3-turbo#924]
### Provide environment information

```
  System:
    OS: macOS 14.0
    CPU: (10) arm64 Apple M1 Max
    Memory: 1.03 GB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.11.1 - ~/Library/pnpm/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 10.2.4 - ~/Library/pnpm/npm
    pnpm: 8.14.1 - ~/Library/pnpm/pnpm
    bun: 1.0.31 - ~/.bun/bin/bun
```

### Describe the bug

I need some help with handling this TS issue. Some things that I am not sure about:

- [ ] Zod too slow for TS, I have a lot of validations also comming from drizzle-zod but also using .omit or .extend
- [ ] Other dependecies like Stripe and Firebase might cause the slowdon
- [ ] Should I split the trpc routers in smaller packages ?

### Problem
Typescript Intellisense is very slow in my project. The project was boostrapped from this template. It currently has 17 trpc routers with logic from drizzle, zod, stripe and firebase. I don't think the current size should justify the slow ts. 

https://github.com/t3-oss/create-t3-turbo/assets/17547035/c74c9f79-cac5-4f1b-af19-cee0f02fd590

I know this template uses `incremental` option in the `tsconfig.json` which should make sure that packages type inference are cached .cache, but it looks like when I use a trpc router it's always type-checking.
https://github.com/t3-oss/create-t3-turbo/blob/ae8f4477484b59e40e304d1fc0b02e403fe1bce5/tooling/typescript/base.json#L17

### Investigation
I've also generated a trace from tsc. Seeing some stuff from `@acme/db` and `@acme/auth` but I am not sure if I am looking at the right things.
[trace.json](https://github.com/t3-oss/create-t3-turbo/files/14693752/trace.json)

Output from  `npx tsc --extendedDiagnostics` for the nextjs app

<img width="378" alt="Screenshot 2024-03-21 at 12 29 01" src="https://github.com/t3-oss/create-t3-turbo/assets/17547035/764927b4-b6a2-406b-a001-17e92735715b">

### Link to reproduction

https://github.com/tabtick/tabtick

### To reproduce

- run `pnpm install`
- press cmd + space 
- takes a few seconds to get intellisense

**Comment by juliusmarminge** [comment]
Can you try if something's like this works for you? https://github.com/juliusmarminge/acme-corp/pull/225

**Comment by dBianchii** [comment]
I also have terrible vscode performance. It's crazy how deep these inferences get.

**Comment by estubmo** [comment]
I know it doesn't solve the issue for those who want to keep using ESlint and Prettier, but I moved to Biome.js and it's much, much more performant. There's even starter repo for it here: https://github.com/rajatsandeepsen/t3-turbo-biome

**Comment by juliusmarminge** [comment]
Probably because Biome doesnt have rules that require type information.

**Comment by andrewdoro** [comment]
@juliusmarminge implementing your recommendation seems to have helped a lot. I've split the @acme/api in two packages:
- @acme/base where routes are defined and tsc -w command is running
- @acme/api where the appRouter is created and then re-exported to client

I am still not sure if drizzle was the culprit, I am seeing .dts file of 3000 lines >.

//Also added `declarationMap:true` so I can still navigate directly to the router.
https://github.com/tabtick/tabtick/pull/16

**Comment by trevorpfiz** [comment]
> I know it doesn't solve the issue for those who want to keep using ESlint and Prettier, but I moved to Biome.js and it's much, much more performant. There's even starter repo for it here: https://github.com/rajatsandeepsen/t3-turbo-biome

thinking about migrating. anything you are missing from ESLint+Prettier?

**Comment by juliusmarminge** [comment]
> > I know it doesn't solve the issue for those who want to keep using ESlint and Prettier, but I moved to Biome.js and it's much, much more performant. There's even starter repo for it here: https://github.com/rajatsandeepsen/t3-turbo-biome
> 
> 
> 
> thinking about migrating. anything you are missing from ESLint+Prettier?

Typed linting

**Comment by ya-s-u** [comment]
I've created a repository for my own.
https://github.com/ya-s-u/t3-turbo-biome
