### ISSUE TITLE
bug(expo): Root html file does not work for React Native for Web

### ISSUE THREAD

**Issue by k2on** [t3-oss/create-t3-turbo#936]
### Provide environment information

  System:
    OS: macOS 14.0
    CPU: (12) arm64 Apple M2 Pro
    Memory: 114.03 MB / 16.00 GB
    Shell: 3.6.1 - /opt/homebrew/bin/fish
  Binaries:
    Node: 18.18.2 - ~/.nvm/versions/node/v18.18.2/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.8.1 - ~/.nvm/versions/node/v18.18.2/bin/npm
    pnpm: 8.15.4 - /opt/homebrew/bin/pnpm
    bun: 1.0.0 - /opt/homebrew/bin/bun

### Describe the bug

The [Root HTML](https://docs.expo.dev/router/reference/static-rendering/#root-html) file (`+html.tsx`) is not working for me.

### Link to reproduction

https://github.com/k2on/ct3-web

### To reproduce

After enabling react native for web, adding a `+html.tsx` file does not affect the html output.

**Comment by juliusmarminge** [comment]
i am unfamiliar with react native for web and it isn't really the target for this repo. you have a nextjs app for that.
