### ISSUE TITLE
bug: run well local but deploy to vercel got error

### ISSUE THREAD

**Issue by phungvansyhb** [t3-oss/create-t3-turbo#937]
### Provide environment information

development : win 11 , node 21 , pnpm 
prod : vercel , node 20

### Describe the bug

I started with create-t3-turbo, that work well on development but when deploy to vercel my website can't call api and show error like img bellow. Anybody can help me, pls
![image](https://github.com/t3-oss/create-t3-turbo/assets/54164578/3d835c29-cc5f-420e-a151-4a79821c231c)

### Link to reproduction

https://github.com/t3-oss/create-t3-turbo

### To reproduce

...

**Comment by juliusmarminge** [comment]
the repro you linked is deployed on vercel. if you have issues i'll need a more detailed repro with what you did and didn't set up.

there's been some changes since you opened too. gonna close this but if you still experience issues reopen with proper steps
