### ISSUE TITLE
Expo erroring out when trying to run pnpm on fresh clone

### ISSUE THREAD

**Issue by kgudipati** [t3-oss/create-t3-turbo#94]
Config:
Node - v19.3.0
PNPM - 7.19.0
Expo - 6.0.8

I've cloned a new repo and following the setup instructions to install the node_modules and push the prisma schema to a sqlite db. Running `pnpm dev` is giving the following error and 

> @acme/expo:dev: › Opening exp://192.168.1.101:19000 on iPhone 13
@acme/expo:dev: - Fetching Expo Go
@acme/expo:dev: <PROJECT-PATH>/node_modules/@expo/cli/build/src/utils/downloadExpoGoAsync.js:78
@acme/expo:dev:                     bar.update(progress, total);
@acme/expo:dev:                         ^
@acme/expo:dev:
@acme/expo:dev: TypeError: Cannot read properties of null (reading 'update')
@acme/expo:dev:     at Object.onProgress (<PROJECT-PATH>/node_modules/@expo/cli/build/src/utils/downloadExpoGoAsync.js:78:25)
@acme/expo:dev:     at onProgress (<PROJECT-PATH>/node_modules/@expo/cli/build/src/api/rest/wrapFetchWithProgress.js:52:61)
@acme/expo:dev:     at PassThrough.<anonymous> (<PROJECT-PATH>/node_modules/@expo/cli/build/src/api/rest/wrapFetchWithProgress.js:44:21)
@acme/expo:dev:     at PassThrough.emit (node:events:525:35)
@acme/expo:dev:     at addChunk (node:internal/streams/readable:324:12)
@acme/expo:dev:     at readableAddChunk (node:internal/streams/readable:297:9)
@acme/expo:dev:     at Readable.push (node:internal/streams/readable:234:10)
@acme/expo:dev:     at node:internal/streams/transform:182:12
@acme/expo:dev:     at PassThrough._transform (node:internal/streams/passthrough:46:3)
@acme/expo:dev:     at Transform._write (node:internal/streams/transform:175:8)
@acme/expo:dev:
@acme/expo:dev: Node.js v19.3.0
@acme/expo:dev:  ELIFECYCLE  Command failed with exit code 1.
@acme/expo:dev: ERROR: command finished with error: command (<PROJECT-PATH>/apps/expo) pnpm run dev exited (1)
@acme/db:dev:  ELIFECYCLE  Command failed.
@acme/db:dev:  WARN   Local package.json exists, but node_modules missing, did you mean to install?
@acme/db:dev:  ELIFECYCLE  Command failed.
@acme/db:dev:  WARN   Local package.json exists, but node_modules missing, did you mean to install?

Not sure what I'm missing as I've followed the instructions as is. I see this step in the instructions but didn't know what action was required as the changes to the expo dev config for iOS has been updated:
`Note: If you want to use a physical phone with Expo Go, you need to run dev without turbo (e.g. pnpm --filter expo dev). `

**Comment by mvaleriani** [comment]
@kgudipati Can I ask why you closed this? I'm experiencing the same issue

**Comment by juliusmarminge** [comment]
> @kgudipati Can I ask why you closed this? I'm experiencing the same issue

Can you provide a repro repo?

**Comment by bredfield** [comment]
I'm getting this from a fresh clone as well

**Comment by heesungjang** [comment]
@bredfield I faced the same issue and for me It was because expo go was not downloaded. Make sure you have XCode and XCommand Line Tools installed and run 'npx expo start' on terminal and 'I' to launch Expo Go. and then try 'pnmp dev' again!

**Comment by bredfield** [comment]
> @bredfield I faced the same issue and for me It was because expo go was not downloaded. Make sure you have XCode and XCommand Line Tools installed and run 'npx expo start' on terminal and 'I' to launch Expo Go. and then try 'pnmp dev' again!

Yep, got it! I wonder if this can be automated, or whether the docs need an update

**Comment by JacobWennebro** [comment]
@heesungjang I have this exact issue, however when I try to run 'npx expo start' I'm greeted with this. I have just installed XCode and XCommand Line Tools, I've ran the simulator inside of XCode and I have restarted my terminal, still I get this error
![image](https://user-images.githubusercontent.com/36081266/214921861-a245b0ff-2047-47d8-bbff-f78110477a2f.png)
