### ISSUE TITLE
feat: Create default shadcn configuration inside packages/ui

### ISSUE THREAD

**Issue by alananisimov** [t3-oss/create-t3-turbo#952]
### Describe the feature you'd like to request

When i'm running `pnpm run add (some component)` inside packages/ui folder, shadcn gives me this error: 
> Configuration is missing. Please run init to create a components.json file.

And then im running `pnpm dlx shadcn-ui init` it creates another one tailwind.config.js that isn't normal.

### Describe the solution you'd like to see

Maybe you need to provide default shadcn configuration inside packages/ui

**Comment by trevorpfiz** [comment]
#956

**Comment by kwiss** [comment]
Hey i have a working version here: https://github.com/t3-oss/create-t3-turbo/pull/957 @juliusmarminge, please take a look @trevorpfiz 

no path modification in the app for the component, i only modified the one for the lib

**Comment by trevorpfiz** [comment]
> Hey i have a working version here: #957 @juliusmarminge, please take a look @trevorpfiz
> 
> no path modification in the app for the components, i only modified the path for the lib

@kwiss I am getting errors with the paths. I am pretty sure you have to modify the `tsconfig.json` as mentioned here https://github.com/dan5py/turborepo-shadcn-ui/issues/20.

**Comment by kwiss** [comment]
Oh my bad i didn't changed the import for the lib everywhere in the app, but i should work without any other modification, i use it like that in another repository, i'll fix my pull request soon

**Comment by juliusmarminge** [comment]
Cool workaround with the self-referencing!

**Comment by kpripper** [comment]
Is the problem solved or not? Because I still have the same error.
