### ISSUE TITLE
feat: add electron app

### ISSUE THREAD

**Issue by mariomeissner** [t3-oss/create-t3-turbo#97]
I love this repository. I've been looking at monorepo resources and this has been extremely useful.
I would like to see Electron included in the monorepo, similar to the [yerba example repo](https://github.com/t3dotgg/yerba).

The three main deployment environments are web, mobile and desktop. Currently we cover two with Next.js and Expo, so Electron would perfectly close the gap. I think there's a lot of value in seeing all three playing together in a single monorepo.

At some point we could let the CLI ask the user which deployment environments are desired and then include or exclude parts as necessary.

I would love to contribute, but I'm quite new to this so I would need guidance.

**Comment by juliusmarminge** [comment]
I don't see anything special in the electron setup so not sure if we need to add it - given that it should be pretty straight forward for someone to add it if they want to build a desktop app? 

Did you run into issues trying to add this yourself?

**Comment by mariomeissner** [comment]
I haven't personally tried yet but I do believe there are some intricacies in getting electron to work in this setup, hence why yerba exists in the first place. 

I see the value in having electron here to cover the last environment axis, but I understand if you think it's not valuable enough. I do not yet know how easy or difficult it would be to add for users by themselves.

**Comment by juliusmarminge** [comment]
I'll close this for now as not planned. If you have any troubles setting this up in the future you can re-open and we can revisit if we should include it by default or not
