### ISSUE TITLE
bug: `drizzle-orm/expressions` does not include `sql`, `count`, `sum`, etc.

### ISSUE THREAD

**Issue by ahkhanjani** [t3-oss/create-t3-turbo#979]
### Provide environment information

-

### Describe the bug

There's been a change to the `db` package recently that exports `*` from `drizzle-orm/expressions` instead of `drizzle-orm`. This doesn't include some of the necessary functions from `drizzle-orm/sql`.

### Link to reproduction

-

### To reproduce

-

**Comment by juliusmarminge** [comment]
Feel free to PR - I felt like it was a good change so you dont export everything including all the table and column definitions.

But the sql function is definetely useful

**Comment by dBianchii** [comment]
You can export those from "drizzle-orm/sql" I believe. We should do a PR for it. Are there other implicit helpers that exist elsewhere in drizzle that you are missing?

**Comment by ahkhanjani** [comment]
I inspected the source code. Here's how things are exported:

`./sql`: Contains `/expressions`, `/functions` subdirectories and a `sql.js` and exports all three.
`./expressions`: Re-exports `/sql/expressions`.

`functions` contains aggregation functions. So Everything in it is necessary. `sql.js` seems to have some unnecessary objects in it.

I'll make a PR for the most minimal export possible.
