### ISSUE TITLE
bug: Client component - Drizzle schema - env error

### ISSUE THREAD

**Issue by john093e** [t3-oss/create-t3-turbo#988]
### Provide environment information

turbo dev

### Describe the bug

inside a client component:

import { schema } from "@acme/db"

Seems to load the whole index.ts and so return env error as env can't be use in client.

### Link to reproduction

-

### To reproduce

import {schema} from "@acme/db"

schema.post.status.enumValues.map((status) => ({
// do somthing with it

**Comment by dBianchii** [comment]
Why do you need your schema in client components?

**Comment by dBianchii** [comment]
@andrewdoro , I still think you can't use schemas that came from drizzle-zod in client components. I tried it recently myself.

See: https://github.com/t3-oss/create-t3-turbo/discussions/966

**Comment by andrewdoro** [comment]
@dBianchii this was introduced by this https://github.com/andrewdoro/create-t3-turbo/commit/5db63fbaf5fbfebd1209e89bf345aa1d018c540e
@juliusmarminge saw your PR, was thinking about a simpler solution
https://github.com/t3-oss/create-t3-turbo/pull/990
