### ISSUE TITLE
bug: Xcode installed, but returns error `Xcode must be fully installed before you can continue`

### ISSUE THREAD

**Issue by datasalaryman** [t3-oss/create-t3-turbo#993]
### Provide environment information

```
  System:
    OS: macOS 14.4.1
    CPU: (8) arm64 Apple M1
    Memory: 279.61 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.12.2 - ~/.nvm/versions/node/v20.12.2/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 10.5.0 - ~/.nvm/versions/node/v20.12.2/bin/npm
    pnpm: 8.11.0 - /opt/homebrew/bin/pnpm
    bun: 1.0.2 - ~/.bun/bin/bun
    Watchman: 2024.04.08.00 - /opt/homebrew/bin/watchman
```

### Describe the bug

I've already installed Xcode, already confirmed that the iphone simulator works, but for some reason, expo won't track my Xcode installation. 

![image](https://github.com/t3-oss/create-t3-turbo/assets/87289753/090adba3-980c-4968-a4a8-ecf39e99e7dc)

### Link to reproduction

https://github.com/t3-oss/create-t3-turbo/assets/87289753/090adba3-980c-4968-a4a8-ecf39e99e7dc

### To reproduce

```
bunx expo start
```
then click option `i`

**Comment by juliusmarminge** [comment]
Try running:

```sh
sudo xcode-select -s /Applications/Xcode.app/Contents/Developer
```

**Comment by juliusmarminge** [comment]
Also make sure you allow your terminal to send system events:

![CleanShot 2024-04-16 at 20 26 40@2x](https://github.com/t3-oss/create-t3-turbo/assets/51714798/40807a89-d846-44ed-b550-04aa248c962d)

**Comment by juliusmarminge** [comment]
Stale
